### ISSUE TITLE
Address validation

### ISSUE THREAD

**Issue by sammy007** [BTCGPU/BTCGPU#105]
```
./src/bgold-cli validateaddress 3CjLoKt9KYcfjf4MWAbGz8xnpfJvzvMxMi
{
  "isvalid": false
}
```
Confusing. Could you publish a scriptPubKey for both mainnet and testnet premine addresses?

**Comment by h4x3rotab** [comment]
Fixed at: https://github.com/BTCGPU/BTCGPU/pull/104/commits/cb74c1026b83ab6bc60f55bcbd1fb11bcd93d2c3

**Comment by h4x3rotab** [comment]
BTW this is a placeholder for premine whitelist. I will publish the full script when it's replaced by the actual addresses.

**Comment by sammy007** [comment]
Thanks. May I assume there will be just one coinbase address allowed until height X or any weird zcash-like bullshit schedule?

**Comment by h4x3rotab** [comment]
LOL. There will be zcash-like bullshit until height X but after that nothing will be different with Bitcoin. My idea about premine whitelist is like this:

- Every mined blocks within the premine window have a corresponding address.
- The output address is chosen by the height of the coinbase tx.
- The output addresses of the first 40% blocks are 2-of-3 multisig addresses.
- The output addresses of the remaining 60% blocks are time-lock 2-of-3 multisig addresses, with each address have its lock time calculated by the block height.
- To prove these address are actually HODL addresses, all the addresses should be generated with public keys on-the-fly.

**Comment by sammy007** [comment]
The mining incentive needed during this period otherwise you will mine all these blocks yourself. Take 10 BCG and allow 2.5 for miners.

**Comment by sammy007** [comment]
Well since you are going to reset difficulty you can do premine with CPU indeed, then adjustment and normal mining period.

**Comment by h4x3rotab** [comment]
Exactly. I'm going to close the issue.
