### ISSUE TITLE
PoW/ GBT/ PowLimit

### ISSUE THREAD

**Issue by sammy007** [BTCGPU/BTCGPU#106]
* Since coin is going to utilise equihash, are you going to adjust powLimit also?
* Is code ready for block submissions via RPC already?
* Is `getblocktemplate` ready or we have to expect modifications soon?

**Comment by sammy007** [comment]
> are you going to adjust powLimit also?
Okay I see powLimit PR https://github.com/BTCGPU/BTCGPU/pull/104

**Comment by h4x3rotab** [comment]
> Is code ready for block submissions via RPC already?
> Is getblocktemplate ready or we have to expect modifications soon?
Yes, we tested them by a modified z-nomp. `getblocktemplate` has already been compatible with Zcash pools.

**Comment by sammy007** [comment]
Any specific changes except premine address vs founder reward scheme?

**Comment by h4x3rotab** [comment]
Actually not. Just submitting blocks in new block serialization format is fine. I've made some changes to allow to submit legacy blocks for regtest but that's only for testing purpose.

**Comment by h4x3rotab** [comment]
We've already changed it to the same powLimit as Zcash. However as the block interval is 4x of Zcash, I think it's better to have a 1/4 powLimit. Thoughts?

**Comment by sammy007** [comment]
I have no idea why it's necessary, it's always good and not confusing to follow the powLimit of first coin on this algo. All coins chose powLimit based on algo, scrypt, x11, etc uses same always.

**Comment by h4x3rotab** [comment]
Thank you. We have finally kept the same powLimit as Zcash and this results in it's possible to compare the hashrate with other coins with Equihash algo.
