### ISSUE TITLE
Getmininginfo hashspersec confusing

### ISSUE THREAD

**Issue by sammy007** [BTCGPU/BTCGPU#107]
I am running private testnet with adjusted HF block number, after I mined a few blocks I see:

```
`"networkhashps":3.159099143390523e-06`
```

Actually it's not expected and this value must be reset right after fork and likely follow zcash formula.

Maybe I got this number because I modified `BTGHeight`.
Same with `difficulty`.

**Comment by h4x3rotab** [comment]
You are right. Will check this today.

**Comment by h4x3rotab** [comment]
Done.
