### ISSUE TITLE
Build problem: Several functions 'not declared in this scope'

### ISSUE THREAD

**Issue by hrosspet** [BTCGPU/BTCGPU#110]
I tried to build this repo on an EC2 AWS instance with Amazon Linux. I installed all the dependencies using yum. I compiled boost from source (v 1_61_0). These are the final lines of the output of `./configue` command:
```
Options used to compile and link:
  with wallet   = yes
  with gui / qt = no
  with zmq      = no
  with test     = yes
  with bench    = yes
  with upnp     = auto
  debug enabled = no
  werror        = no

  target os     = linux
  build os      =

  CC            = gcc
  CFLAGS        = -g -O2
  CPPFLAGS      =  -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS
  CXX           = g++ -std=c++11
  CXXFLAGS      = -g -O2 -Wall -Wextra -Wformat -Wvla -Wformat-security -Wno-unused-parameter
  LDFLAGS       =
  ARFLAGS       = cr
```

And here is the make command which fails:
```
[ec2-user@*** BTCGPU]$ make
Making all in src
make[1]: Entering directory `/home/ec2-user/data/BTCGPU/src'
make[2]: Entering directory `/home/ec2-user/data/BTCGPU/src'
  CXX      bgoldd-bitcoind.o
In file included from ./uint256.h:15:0,
                 from consensus/params.h:9,
                 from chainparams.h:10,
                 from bitcoind.cpp:10:
./crypto/common.h: In function ‘int init_and_check_sodium()’:
./crypto/common.h:120:65: error: ‘crypto_sign_detached’ was not declared in this scope
     crypto_sign_detached(sig, NULL, message, sizeof(message), sk);
                                                                 ^
In file included from ./crypto/common.h:12:0,
                 from ./uint256.h:15,
                 from consensus/params.h:9,
                 from chainparams.h:10,
                 from bitcoind.cpp:10:
./crypto/common.h:122:73: error: ‘crypto_sign_verify_detached’ was not declared in this scope
     assert(crypto_sign_verify_detached(sig, message, sizeof(message), pk) == 0);
                                                                         ^
make[2]: *** [bgoldd-bitcoind.o] Error 1
make[2]: Leaving directory `/home/ec2-user/data/BTCGPU/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/ec2-user/data/BTCGPU/src'
make: *** [all-recursive] Error 1 
```

Does anybody have an idea what could be wrong here?

**Comment by francois007** [comment]
./configure -with-gui
...
configure: error: PROTOC not found

**********************************************************

./configure
...
configure: WARNING: PROTOC not found; bitcoin-qt frontend will not be built
...
Options used to compile and link:
  with wallet   = yes
  with gui / qt = no
  with zmq      = yes
  with test     = yes
  with bench    = yes
  with upnp     = yes
  debug enabled = no
  werror        = no

  target os     = linux
  build os      = 

  CC            = gcc
  CFLAGS        = -g -O2
  CPPFLAGS      =  -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS
  CXX           = g++ -std=c++11
  CXXFLAGS      = -g -O2 -Wall -Wextra -Wformat -Wvla -Wformat-security -Wno-unused-parameter
  LDFLAGS       = 
  ARFLAGS       = cr

**********************************************************

make
...
make[2]: *** [bgoldd-bitcoind.o] Error 1
make[2]: Leaving directory `/usr/src/BTCGPU/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/usr/src/BTCGPU/src'
make: *** [all-recursive] Error 1

**Comment by hrosspet** [comment]
Installing libsodium from source instead of sudo yum install solved my issue.
```
wget https://download.libsodium.org/libsodium/releases/libsodium-1.0.15.tar.gz
tar -xzvf libsodium-1.0.15.tar.gz
cd libsodium-1.0.15
./configure --prefix=/usr/local
make && make check
sudo make install
```
