### ISSUE TITLE
Windows builds are broken due to errors caused by path variable

### ISSUE THREAD

**Issue by thexder1** [BTCGPU/BTCGPU#113]
This issue tracker is only for technical issues related to bitcoin-core.

General bitcoin questions and/or support requests and are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).

For reporting security issues, please see the official [Bitcoin Gold website](https://btcgpu.org/).

### Describe the issue
When building the dependencies for Windows getting errors from /bin/sh saying 'Unexpected "("'.
After troubleshooting found that due to the PATH variable being prepended to the configure and make commands on windows systems the directories like C:\Program Files (x86) generate those errors if there are any in the path.

#### If so, please list the steps to reproduce below:
1. Using a windows system add a directory under C:\Program Files (x86) to your system PATH variable
2. Follow process for Windows builds. Error will happen during dependency builds

### Expected behaviour
Those variables should be correctly quoted or escaped, or modified to not throw the errors so that Windows builds can run.

### Actual behaviour
Errors as described above, and build fails every time.

### What version of bitcoin-core are you using?
44c991856a7fb93596bef5db5177a538cfe5fc1d building it myself

### Machine specs:
- OS: Windows 10-64 bit
- CPU: AMD fx-8320
- RAM: 16GB
- Disk size: 120GB
- Disk Type (HD/SDD): SSD

### Any extra information that might be useful in the debugging process.
I entered a new path variable inline excluding the paths that are causing problems and the build works.

**Comment by srmo** [comment]
Can verify this, same problem in a similar environment. Manually removed all "space containing" entries from PATH and it works

**Comment by DarthJahus** [comment]
Thank you for finding this issue.

Removed all entries from PATH (both from CMD and from System Settings, both on User-level and System-level). Now, it's working.

Question: We should not have to rebuild for main-net, or should we? I think we just need to change settings and add peer addresses. Can someone confirm this?

**Comment by h4x3rotab** [comment]
This is the same as Bitcoin Core. You'd better to cross-compile in Ubuntu 16.04.

Please see: https://github.com/BTCGPU/BTCGPU/issues/136
