### ISSUE TITLE
When bitcoingold exchanger avaible to deposit and withdraw ? any chance back to 0.1btc? 

### ISSUE THREAD

**Issue by haidarsukses** [BTCGPU/BTCGPU#121]
When bitcoingold exchanger avaible to deposit and withdraw ? any chance back to 0.1btc?

**Comment by nimburkx** [comment]
no chance it was just advertising to let users get confused and looze their money:))))

**Comment by D3m0nKingx** [comment]
Github is not for creating issues that have nothing to do with the code development @haidarsukses please close this matter, and contact the dev through slack, or other appropriate channels.

@h4x3rotab I've made an abuse report with github support, I think it's time to get this addressed.

**Comment by h4x3rotab** [comment]
As @D3m0nKingx said, I'm going to close this issue.
