### ISSUE TITLE
Questions about address format

### ISSUE THREAD

**Issue by DarthJahus** [BTCGPU/BTCGPU#128]
Question: If we send funds to a Bitcoin address on Bitcoin Gold network (i.e. Send BTG to an adress starting with 1), can we access the funds with the Bitcoin Gold wallet by importing the private key?

Also. What is the BTG address format?

**Comment by evadogstar** [comment]
I guess now at test net you can use any new bitcoin address. On the mainnet it will be changed and announced.

**Comment by h4x3rotab** [comment]
BTG testnet address format is same as Bitcoin testnet3 (starts with "n", "m", or "2").If you send coins from BTG testnet wallet to a Bitcoin wallet, you should be able to receive your coins in the same address if you can import the private key.

BTG mainnet address format is not same as Bitcoin. It starts with "G" or "A".
