### ISSUE TITLE
bgold-cli importprivkey returns error code -5 with bitcoin priv key

### ISSUE THREAD

**Issue by MrHillss** [BTCGPU/BTCGPU#131]
### Describe the issue

bgold-cli importprivkey returns "error code -5" when fed with a regular bitcoin private key created before the fork. Idk if it is normal.

#### If so, please list the steps to reproduce below:
1. Turn node on with sudo bgoldd -printtoconsole -testnet
2. run "bgold-cli importprivkey /bitcoin priv key/ /label/"
3. Error message returned:
error code: -5
error message:
Invalid private key encoding

### Expected behaviour
Bitcoin private key should be added to the node and the related address should be accessible

### Actual behaviour
Bitcoin private key is not added

### Screenshots.

![](https://i.gyazo.com/e61b72438c28199c2d0adfe1e4664342.png)

### What version of bitcoin-core are you using?

![](https://i.gyazo.com/e1dab861f2e291ea95db31c86d1ad9f8.png)

### Machine specs:
VM created with virtualbox

**Comment by bilbobits** [comment]
Seriously BTCGPU uses is own 'custom' address mechanism, why would an 'import' be relevant here??

U need to 'cli getnewaddress', then 'cli dumpprivkey', and then you can import a BTCGPU priv key.

BTCGPU is NOT compatible with old blockchain (BTC), nor are the addresses compatible,  BTCGPU(DEV) team claims they will provide a 'converter' to convert BTC ADDRESSES to BTCGPU, but honestly from what I see so far is 100% of BTCGPU is VIRGIN, and you must start all from scratch.

**Comment by MrHillss** [comment]
Ty for your answer. I thought the address mechanism was the same. Now it turns out the addresses are going to be differentiated as well, which is a plus in my mind. I'll close the issue.

**Comment by Emendiz** [comment]
Sorry, not sure I understand and I am having the same issue...
Is there a specific BTG command to import private keys?

Thanks.

**Comment by h4x3rotab** [comment]
Are you trying to import Bitcoin mainnet private key to BTG testnet? The privkey of mainnet and testnet is not compatible. You can import mainnet or testnet privkey between Bitcoin Core and BTG client but not cross.

**Comment by Emendiz** [comment]
No, it was something even more basic: I installed all the daemon and CLI succesfully (it took me a while), and I am now able to do everything, even I am mining on the testnet.
The only thing "failing" is that I created a new address, then deleted the wallet.dat, and then with a new wallet tried to import that same address and I get the error shared above:
"error code -5"

I am following the SAME steps that I have done for BTC thousand of times, and this issue is marked as resolved... so how do I import a private key to the bgold node wallet?

Is there an "alternative" CLI command for this? (In ZCash you use other command, so BTG might also be different).

**Comment by h4x3rotab** [comment]
I'm trying to reproduce your problem.

**Comment by h4x3rotab** [comment]
My command line:
```
./src/bgold-cli -testnet importprivkey cQAMc2tcoVfYFHdbbKG4KrPBdDikEEFywDxTkP4TXe31u8akdFjy "from-btc" false
```

The privkey is generated by a Bitcoin Core testnet client. @Emendiz, can you try the same command?

**Comment by Emendiz** [comment]
Your command worked perfectly fine... so I deep dived... and I think I know what happened... I might not have used a testnet address! Could that be?

What is strange is that now the address I generated with the CLI commands, are now able to re-import after deletion of the wallet.dat file... and that was not happening!

So, please "re-mark" as resolved, and if I see this error I will again reach out here.
