### ISSUE TITLE
How to 'testnet' right-now, ... Why is pool.gold the only 'working' miner? 

### ISSUE THREAD

**Issue by bilbobits** [BTCGPU/BTCGPU#132]
Say you want to mine 'testnet' bitch btc clone?

Here is how

ccminer/ccminer -a equihash -o stratum+tcp://eu.pool.gold:3044 -u mu5cjbSbE879MK5DtRnS3B1MnBvSfrHMQJ -p x

Note I'm not using 'miner' ewbf fuck his fee's ( even though they can be disabled for --fee 0.0 ),

Above I'm using ccminer, current build, its a bitch, will not compile easily, but just as fast as ewbf without the SHIT-FEE BS, build by editing 'makefile' to computer_20 to compute_50, then will build, must use cuda-8.0.

Right now this is the only way you can testnet mine BTCGPU, the code that we minions get ( public ) doesn't work, its clear that BTCGPU is either running a mining-scam and re-directing the HASH, or they're the only scammers ( btcgpu family+yobit.net+china-asic) who have a working source-code, because the code we have will NOT let you solo mine.

***

If you play the pool.gold game and download the ewbf script they include a start.sh file that runs the ewbf miner, and that is fine, but that miner has many problems WRT to stability and use with large mining farms, for a NOOB I suggest ccminer ( most current ), it works just fine, 

Another issue FYI for people here is that this is just '-testnet' mining, any HASH you throw to BTCGPU POOL, your just tossing your HASH into the cesspool.

I have put a 10k sol/sec hash on this pool for 30 minutes, my result at the current difficulty 800 was luck is about 5/day. Right now there are only 250k sols/sec on the test, once this WHORE goes mainnet it will go to 250MH, ,which means the profit will drop to 0.005/day, which is $10 at current BTG(yobit.net $200) if it holds, I can mine zencash and make $200/day today.

All along BTCGPU has been a fraud, lies, bullshit, scams to assume this shit will change??? Not likely, they keep pulling new scams out of their ass daily, and offering the mea-culpa ( forgive me I have sinned ), now we know that they're passing us shit code, ,and somebody at pool.gold is either re-directing HASH, or in the only kid in the sandbox with working code.

Lastly, I follow the github release hourly, I have script  that rebuilds the git everytime there is a new commit, and it stops the testnet and restarts the daemon, and it will NOT let me solo mine, and the results I see on pool.gold are completely different. Also note that pool.gold is only gettting about 20% of the blocks, thus somebody else is mining this testnet, and it isn't the little people. Also I have tested all the other pools that support BtcGPU, and only pool.gold is working, they're the only pool with this source.

I suspect that a LARGE GPU farm in CHINA has the real code and is pre-mining/testnet and working this code and testing their farms.

IMHO once again the chinese will OWN bitcoin mining albeit GPU, and will perpetuate the myth that BTC mining is not owned by ASIA.

Lastly, NOMP-Z there is a release that allows pool mining to BTCGPU, but the problem is this code doesn't work, NOMP-Z wants "GetblockSubsidy", and BTCGPU doesn't include the ZCASH CLI, as btcgpu is 100% BTC source.

Another large FUCK, is why doesn't this code support ZADDRESS??? This means that GOV can track these coins and there is NO PRIVACY, again this is probably a CHINA-NSA plan.

**Comment by barrystyle** [comment]
are you drunk?

**Comment by evadogstar** [comment]
1) they announced that premine will be accumulated and used for dev needs and bounty programs. 
2) Original bitcoin have this privacy? :)

**Comment by h4x3rotab** [comment]
pool.gold is not the only working pool. Ask at slack #dev channel.

**Comment by bilbobits** [comment]
You can't call any of these pools "working' as the payouts never reach the 'bgold-cli getbalance'

on pool 'pool.gold' U must use a -G address to get a virtual payout, but you disabled the -testnet to generate 'g' addresses so people can't even test, and if you do hack the code to generate a 'g' address, and you do manage to get pool.gold to generate a payout, it doesn't mean anything because explorer will always show zero

**Comment by achaykin** [comment]
Because no mining software for this coin. And they cannot add the RPC getblocksubsidy function. This is trivial they says. We add this in the future lolz. But coin and bitcoin source code with getblocksubsidy is 1:1. No getblocksubsidy - no payments. Implement this function yourself they says. Maybe i can write my own coin and have no problems? Why i can f*ck with your coin with translation c++ to java and write patch for my pool to work without getblocksubsidy?

**Comment by StarbuckBG** [comment]
This is not true, again.
When you issue command for taking header format all of this information is returned there.
Please educate and then post here.

There are too many running pools to blame us for this. If there was a problem there won’t be any pools up and running (:

**Comment by achaykin** [comment]
You are the developers, not I. I dont like educate. I need to use finished product :)

**Comment by StarbuckBG** [comment]
You can ask “educating” questions in Slack - https://join.slack.com/t/bitcoin-gold/shared_invite/enQtMjY1MzkzMzUxNjY4LWM1YmQ4MjZhZTQxMWE1ZDQyNjA4N2QwZTkyZjYzMjhiMzdlMmVkNjQ3NzZlZDdmMDE4NWIyY2JmYzdjYmE2MzA <https://join.slack.com/t/bitcoin-gold/shared_invite/enQtMjY1MzkzMzUxNjY4LWM1YmQ4MjZhZTQxMWE1ZDQyNjA4N2QwZTkyZjYzMjhiMzdlMmVkNjQ3NzZlZDdmMDE4NWIyY2JmYzdjYmE2MzA>

This kind of questions are making our work with github hard. We need to have clean GitHub issues section.
Thanks!
