### ISSUE TITLE
Windows build failing with automake-1.14: command not found

### ISSUE THREAD

**Issue by DarthJahus** [BTCGPU/BTCGPU#134]
```
root@Sandy:/mnt/d/Softworks/BTCGPU-master/depends# make HOST=x86_64-w64-mingw32
Building native_protobuf...
make[1]: Entering directory '/mnt/d/Softworks/BTCGPU-master/depends/work/build/x86_64-w64-mingw32/native_protobuf/2.6.1-38b82cbb6fc/src'
make[2]: Entering directory '/mnt/d/Softworks/BTCGPU-master/depends/work/build/x86_64-w64-mingw32/native_protobuf/2.6.1-38b82cbb6fc'
 cd . && /bin/bash /mnt/d/Softworks/BTCGPU-master/depends/work/build/x86_64-w64-mingw32/native_protobuf/2.6.1-38b82cbb6fc/missing automake-1.14 --foreign
/mnt/d/Softworks/BTCGPU-master/depends/work/build/x86_64-w64-mingw32/native_protobuf/2.6.1-38b82cbb6fc/missing: line 81: automake-1.14: command not found
WARNING: 'automake-1.14' is missing on your system.
         You should only need it if you modified 'Makefile.am' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'automake' program is part of the GNU Automake package:
         <http://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <http://www.gnu.org/software/autoconf>
         <http://www.gnu.org/software/m4/>
         <http://www.perl.org/>
Makefile:612: recipe for target 'Makefile.in' failed
make[2]: *** [Makefile.in] Error 1
make[2]: Leaving directory '/mnt/d/Softworks/BTCGPU-master/depends/work/build/x86_64-w64-mingw32/native_protobuf/2.6.1-38b82cbb6fc'
Makefile:1222: recipe for target 'Makefile.in' failed
make[1]: *** [Makefile.in] Error 1
make[1]: Leaving directory '/mnt/d/Softworks/BTCGPU-master/depends/work/build/x86_64-w64-mingw32/native_protobuf/2.6.1-38b82cbb6fc/src'
funcs.mk:242: recipe for target '/mnt/d/Softworks/BTCGPU-master/depends/work/build/x86_64-w64-mingw32/native_protobuf/2.6.1-38b82cbb6fc/./.stamp_built' failed
make: *** [/mnt/d/Softworks/BTCGPU-master/depends/work/build/x86_64-w64-mingw32/native_protobuf/2.6.1-38b82cbb6fc/./.stamp_built] Error 2
```
automake is installed, so I don't understand where the error can come from.

**Comment by bilbobits** [comment]
surely your joking? right??

This thing was ported to an OS MAC, where some guy in a coffee shop in czech republic ( prof starbuck ) did a very poor BTC clone, then he dumped 70% of working code on github/btcgpu

So U want to build the bitch on windows ?? ming??

First of all you need to have ALL YOUR DEPENCY's in place, and that means all,

Then you need to run the build, the only one I found on linux that works is this one I wrote, as 2 weeks even on linux this bitch was impossible to build,

***
./autogen.sh

./configure CPPFLAGS="-I/usr/local/BerkeleyDB.4.8/include -O2" LDFLAGS="-L/usr/local/BerkeleyDB.4.8/lib"


make -j 1 
***

Exactly like above, is your Berkeley DB correctly installed to this path? Is all your depends installed?

automake don't work, U must autogen, and configure, and make, this is called STANDARD BTC BUILD

ls shit in the build folder don't work, its just shit that carried over on the btc-bitch clone, but it was never tested like everything else in this bitch-clone

**Comment by bilbobits** [comment]
when u run automake do u get this? 1.15 is it in your path?

R U sure you pre-installed ALL your depends?

I suggest U first go the BTC core and install that on your MINGZ, then U will know that U know that all your depends R working, cuz that is a stable BTC build, this BTC-GPU is SHIT, its unstable, no way in hell U can build this, if U cannot build the STANDARD BTC

https://github.com/bitcoin/bitcoin

 automake --version
automake (GNU automake) 1.15
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl-2.0.html**

**Comment by h4x3rotab** [comment]
Please see: https://github.com/BTCGPU/BTCGPU/issues/136

**Comment by DarthJahus** [comment]
Correctly built Bitcoin Core [here](https://github.com/bitcoin/bitcoin/issues/10269#issuecomment-342018061).

Tried to build BTG with the same steps, added `sudo apt-get install libdb++-dev` after getting `configure: error: libdb_cxx headers missing` error.

I had to use [this](https://github.com/bitcoin/bitcoin/issues/3686) to get rid of `configure: error: libdb_cxx headers missing`.

After this, I had this error: `configure: error: No working boost sleep implementation found.`

**Comment by DarthJahus** [comment]
Finally built correctly for Windows, used Ubuntu 14. I ran through all of the issues above, except the last error (boost-sleep), and make worked correctly.

**Comment by h4x3rotab** [comment]
Awesome! My suggestion is always to follow “build-windows.md” and cross-compile from Ubuntu 16.04.
