### ISSUE TITLE
How to Generate your own "G" address right now ... & Mine on Pool.Gold

### ISSUE THREAD

**Issue by bilbobits** [BTCGPU/BTCGPU#135]
src/bgold-cli getnewaddress
GYCnQdKHBEFWLezZeVk1qQmMU5mx6zPU7Z

***

Just don't run in -testnet mode, then you can generate a 'G' address, and it works just fine in pool.gold.

 ccminer/ccminer -a equihash -o stratum+tcp://eu.pool.gold:3044 -u GYCnQdKHBEFWLezZeVk1qQmMU5mx6zPU7Z  -p x

***

If you want to know how to enable 'mainnet' to turn on this just ask, otherwise I will assume you know how to disable the -testnet about message. Just a few cpp lines to kill the throw-abort when your not running in -testnet mode.

**Comment by bilbobits** [comment]
U don't need a 'g' address to mine, the default -testnet address from getaddress works just fine, but somebody here asked how to make 'G' addresses, so I'm answering the question.

**Comment by h4x3rotab** [comment]
"G" addresses are for mainnet and can't be used in testnet pools, though some pool didn't validate the payment addresses.
