### ISSUE TITLE
For fellow developers; if you fail building this;  fatal error: sodium.h: No such file or directory

### ISSUE THREAD

**Issue by wjcloud** [BTCGPU/BTCGPU#137]
Making all in src
make[1]: Entering directory '/mnt/c/Users/User/test/BTCGPU/src'
make[2]: Entering directory '/mnt/c/Users/User/test/BTCGPU/src'
  CXX      bgoldd-bitcoind.o
In file included from ./uint256.h:15:0,
                 from consensus/params.h:9,
                 from chainparams.h:10,
                 from bitcoind.cpp:10:
./crypto/common.h:16:20: fatal error: sodium.h: No such file or directory
compilation terminated.
Makefile:8091: recipe for target 'bgoldd-bitcoind.o' failed
make[2]: *** [bgoldd-bitcoind.o] Error 1
make[2]: Leaving directory '/mnt/c/Users/User/test/BTCGPU/src'
Makefile:9349: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/mnt/c/Users/User/test/BTCGPU/src'
Makefile:741: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

-------------------------------------------------------------------------------------------------------------------

INSTALL libboost1.58-all-dev!!!

**Comment by brandonhuddle** [comment]
For those on Fedora install libsodium-devel

**Comment by jagottsicher** [comment]
better build libsodium from the scratch. you can find a guide from me in #46
