### ISSUE TITLE
'Wed Nov  8 19:00:00 2017' is current set date for launch of main-net according to new testnet code fork

### ISSUE THREAD

**Issue by bilbobits** [BTCGPU/BTCGPU#140]
https://github.com/BTCGPU/BTCGPU/tree/testnet1

New code-fork appears main is no longer being used, most notable is they now have a hard-wired target for main-net.

-221,6 +222,7 @@ class CTestNetParams : public CChainParams {
         consensus.BIP66Height = 330776; // 000000002104c8c45e99a8853285a3b592602a3ccde2b832481da85e9e4ba182
         consensus.BTGHeight = 1210320;
         consensus.BTGPremineWindow = 50;
**+        consensus.BTGTestnetEndDate = 1510142400;**
         consensus.BitcoinPostforkBlock = uint256S("00000000ef93c2d9bac8da61ff11a699a5b815f77a194c567c5de0dbdf0bf28b");
         consensus.BitcoinPostforkTime = 1508111338;

>>> time.ctime(int(t))
'Wed Nov  8 19:00:00 2017'
>>> t
1510142400
>>>

**Comment by h4x3rotab** [comment]
Please read our announcement and the technical details doc here:
https://bitcoingold.org/bitcoin-gold-daily-update-testnet-participation-launch/

Basically we will reset testnet v1 and launch testnet v2 before the difficulty bomb date.

**Comment by bilbobits** [comment]
Your public comment says 1200 @7NOV2017

Now your telling us there will be a testnet2 ( another fork in the btc-gpu code base )

There is only one working pool, and it isn't even paying out  test coins, yet in 24 hours your going "MAIN-NET"

I don't think so, and neither do you, I concur that this thing may takes MONTHS, to get code working, the TESTNET has too many problems, hell we'll need to test the MAIN-NET code for months just to shake out the bugs there, as its clear we're not even running the same same code, which means TESTNET is not testing the real code ( Address gen/test code for instance, not same ).

I the meantime people expend 500K sol/sec to your pool.gold, which could be mining anywhere else on the EQUIHASH planet, and who is to know, as it doesn't payout TESTNET COIN.

I quit mining on the bitch, after 24 hours of mining at 10Ksol's and not even getting 0.01 BTG I realized that I wasn't testing shit. If the test is to confirm that things WORK, then we have confirmed that you can mine all day long and always collect 0.0 BTG, and it will be same for MAIN-NET.

**Comment by bilbobits** [comment]
Solo is same, I noticed 4 days ago 50% of blocks mined were NOT pool.gold, now last 24 hours 99% of blocks 'mined' are pool.gold, when I run SOLO-MINING, same-same I never get a PAYOUT.

It's clear there are MAJOR problems, how long will people PISS THEIR HASH-RATE into the wind and just say "FUCK-IT"???

Sort of like the boy who cried "WOLF", so many promises and dates have come and gone that everyone in the eco-sphere will have a sour taste for this coin, all because it was "PUMPED&DUMPED" before it had working code.

**Comment by h4x3rotab** [comment]
Please submit problems related to pool.gold to its own repo. It's just a reference implementation of a z-nomp modification and it's open sourced. You can feel free to change it to whatever you like or develop your own pool. You didn't say anything true about Bitcoin Gold development. So I'm going to close this issue.
