### ISSUE TITLE
Solo Mining Solved - Dev's Consider "Where is Real Source" ??? Why some mining-pool "More Equal"

### ISSUE THREAD

**Issue by bilbobits** [BTCGPU/BTCGPU#141]
Ok,

Got all the solo mining stuff working and done,

Observations for the DEV's...

[ Note I'm running https://github.com/BTCGPU/BTCGPU/tree/testnet1, as it appears that the main is no longer updated by dev-team. ]

1.) validate address has BIG problems on testnet, very odd that pool.gold supports 'G', but the TESTNET us 'lowlife' get to use  doesn't this means that I can't use a proxy or a client with 'G', I note that "G" can't be created with testnet, so I hacked the main-net code to gen G's, interesting that my client's can pass G's, and the pool.gold is recording G's, but the testnet say's  NOGO to G, just something to think about. Obviously this causes ALL proxy's to fail, as they always validate an address for coinbase ( deposit lottery winnings  ).

 **src/bgold-cli validateaddress GJFcekhtrKCuPD4YDwFKet1tHFXPGUxXM8
{
  "isvalid": false
}**

2.) This begs the question? What is YOUR pool.gold running? They as a proxy are not validating any address, they're just using the address as a bookkeeping tag, just like the SCUM-SCAM at nicehash. They're taking the submitted shares,  and mining the test-net, but they're not running a normal system, they're not running the TEST-NET we're using, as ours will not accept "G" address, anybody can go to pool.gold and see they have lots 'G' addresses running, thus I"M not the only person who figure out how to hack the main-net code to generate 'g' address.

3.) A few days ago pool.gold was finding 50% of the blocks, now its 90% so it appears that the testnet is consolidating to just one pool. Given that all this stuff is so secret and not shared, its not surprising  that the DEV-TEAM will OWN 100% of the BTCGPU world, the entire premise of BTCGPU was to make things more equitable, but IMHO it appears that "CHINA-ASIC" just wants to get out of hardware and control the software world. ( can't let this happen people must open-source 100% of all BTC forks/clones, and all client/proxy shitware (fen-coin) )

4.) As of a few days ago pool.gold was still the ONLY working pool, this is expected as they're internal to FEN-COIN (BTCGPU), its VERY clear the software server-testnet they're running is NOT same as the one on github ( various forks ).

***

Sammy for 25 BTC I will teach you how to solo mine BTCGPU. :)

 Note here that this is just one GPU, note that I'm using the "G", as it get's passed to the miner, but I cannot use the "G" in the coinbase because it causes the software to abort as its not valid in this testnet. ( no problem I just use testnet 'getnewaddress' for coinbase and it is valid )

 miner34 --server 0.0.0.0 --port 9999 --user GJFcekhtrKCuPD4YDwFKet1tHFXPGUxXM8 --pass x
+-------------------------------------------------+
|         EWBF's Zcash CUDA miner. 0.3.4b         |
+-------------------------------------------------+
INFO: Current pool: 0.0.0.0:9999
INFO: Selected pools: 1
INFO: Solver: Auto.
INFO: Devices: All.
INFO: Temperature limit: 90
INFO: Api: Disabled
---------------------------------------------------
INFO: Target: 00ffffffffffffff...
CUDA: Device: 0 Selected solver: 0
INFO 10:44:08: GPU0 Accepted share 0ms [A:1, R:0]
Temp: GPU0: 60C 
GPU0: 680 Sol/s 
Total speed: 680 Sol/s
INFO 10:44:51: GPU0 Accepted share 1ms [A:3, R:0]
INFO 10:44:52: GPU0 Accepted share 1ms [A:4, R:0]
INFO 10:44:52: GPU0 Accepted share 2ms [A:5, R:0]
INFO 10:44:56: GPU0 Accepted share 1ms [A:6, R:0]
INFO 10:44:58: GPU0 Accepted share 1ms [A:7, R:0]
INFO 10:45:01: GPU0 Accepted share 1ms [A:8, R:0]

**Comment by bilbobits** [comment]
Here is the ccminer, I prefer this, its just as fast, its OPEN-SOURCE, and EWBF "miner" is no longer supported, as it appears he just dissapeared, him & claymore are said to be making $10k/day on "FEES". Of course ccminer has no fees, and 100's of dev are working on optimizing the ALGO, myself included.

***

./ccminer -a equihash -o stratum+tcp://127.0.0.1:9999  -u GJFcekhtrKCuPD4YDwFKet1tHFXPGUxXM8 -p x

**Comment by h4x3rotab** [comment]
Testnet doesn’t use “G” addresses. Instead you should generate addressses directly in testnet mode. You will get “n” or “m” addresses.

**Comment by h4x3rotab** [comment]
I believe the problem is that pool.hold doesn’t validate the address at all. So it will fail when trying to pay the miners. Martin should be working on this.

**Comment by StarbuckBG** [comment]
Actually I’m validating it. 
I use validation upon sending payments. If the address is invalid the payment is sent to a wallet that I have pointed out.
There is a validation in the start of the mining that will be enabled on main net, but for the testing these coins worth nothing, so I have stopped this check as most of the people don’t have mining address.

**Comment by StarbuckBG** [comment]
@bilbobits 

I think that you got really sharp in some of your statements, blaming the people that have spent a lot of time on this project. I think that you shall consider some “Sorry guys, my bad” for the words, because as you can see everything is good. Currently pool.gold has most hash rate it is normal that it is finding large part of the blocks - it is the first operating pool, as few people have been working on it for more of a month, it has clean and smooth design, really good servers and is providing really good service. The modified for bitcoin gold z-nomp code is in the github repo, so everyone can download it and make a local z-nomp server and do solo mine.

**Comment by shakilmia** [comment]
wy
