### ISSUE TITLE
Is possible to use private key in Testnet Network ? 

### ISSUE THREAD

**Issue by virtualrobotix** [BTCGPU/BTCGPU#142]
Hi Guys,
i have a question i try to use my private key on BTC Gold Testnet , i only susbstitue my walle.dat to wallet.dat in the BTC Gold Desktop Wallet but i don't found my Bitcoin in tesnet Blockchain. 
Is possible to simulate this process with some kind of utility for understand how happen when you fork in the mainnet ? I try to mine for some time on  pool.goold but i don't recive money and don't see update on the pool.gold web pool interface  there is a way for have fake money for test ? By a faucet as in other system ? 
Thanks
Rob

**Comment by h4x3rotab** [comment]
If you have Bitcoin testnet UTXOs before the testnet fork height, you can definitely import the private key to BTG client. And you can even test the replay protection with your UTXO.

However if you don't have one, you can leave a testnet address here and I can send you 0.1 for testing. We should build a testnet faucet site but currently we don't have bandwidth to do that. It will be more than welcome if you'd like to help with this :)

**Comment by virtualrobotix** [comment]
Hi @h4x3rotab thanks for your reply .... no the private key that i have is on the btc main net and not on btc testnet so that is the reason that don't work , now i understand . So this is the blockchain of BTC  testnet and not of BTC Main net.
This is my address.
mmWT8iBE1qYEfgVJPMPcPizV4CYMwLynnw
Why if i mine in the pool don't see update balance of my work . How is the value set for the payout on testnet ? 
best
Rob

**Comment by virtualrobotix** [comment]
"  It will be more than welcome if you'd like to help with this :) " if you have some info about this task i can try to understand if i can help on it ? I don't know what could be the starting point for this dev.

**Comment by virtualrobotix** [comment]
@h4x3rotab 
thank i recived the 0.1 as you promised 👍

**Comment by h4x3rotab** [comment]
TX: 4d1d92fc95d02b34cf856824e415f400bfb1175ebb0b157ed0caefac1d70199d

Seems there are some problems of the pool payment but I'm not sure.

**Comment by shakilmia** [comment]
Thanks for halp

**Comment by h4x3rotab** [comment]
@virtualrobotix I mean the testnet coin faucet website. Just like this: https://testnet.coinfaucet.eu/en/
