### ISSUE TITLE
how to install wallet on Ubuntu 17.10?

### ISSUE THREAD

**Issue by tigdav2004** [BTCGPU/BTCGPU#143]
This issue tracker is only for technical issues related to bitcoin-core.

General bitcoin questions and/or support requests and are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).

For reporting security issues, please see the official [Bitcoin Gold website](https://btcgpu.org/).

#### If so, please list the steps to reproduce below:
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of bitcoin-core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.

### Machine specs:
- OS:
- CPU:
- RAM:
- Disk size:
- Disk Type (HD/SDD):

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by przemekh10** [comment]
Everything is explained here: https://github.com/BTCGPU/BTCGPU/blob/master/doc/build-unix.md

**Comment by bilbobits** [comment]
https://github.com/BTCGPU/BTCGPU/issues/136

Already addressed, U first must validate your system can compile btc-CORE, then U need to add libsnark and sodium,

If U can't compile run CORE, then it is impossible for you to build BTG

There are 1,000's of examples of building core on stack-exchange, so there is much to hold your hand, there is nothing for BTG, it is assumed that your are an expert when building BTG.

U become an expert by building btc-core.

**Comment by Raja4Shekar** [comment]
OS - Ubuntu 16.04 LTS
PS: It got succeeded when tried with https://github.com/bitcoin/bitcoin.git and failed when using https://github.com/BTCGPU/BTCGPU.git with the below error

Getting following error while tried to "make check". Let me know if you need the full log

=============================================
   Bitcoin Gold 0.15.0: src/test-suite.log
=============================================

# TOTAL: 2
# PASS:  1
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: test/test_bitcoin
=======================

test_bitcoin: ./crypto/common.h:138: int init_and_check_sodium(): Assertion `crypto_sign_verify_detached(sig, message, sizeof(message), pk) != 0' failed.
Running 264 test cases...
unknown location(0): fatal error in "basic_sanity": signal: SIGABRT (application abort requested)
test/sanity_tests.cpp(18): last checkpoint
test_bitcoin: key.cpp:292: void ECC_Start(): Assertion `secp256k1_context_sign == nullptr' failed.
unknown location(0): fatal error in "sign": signal: SIGABRT (application abort requested)
test/scheduler_tests.cpp(112): last checkpoint
test_bitcoin: key.cpp:292: void ECC_Start(): Assertion `secp256k1_context_sign == nullptr' failed.
unknown location(0): fatal error in "norecurse": signal: SIGABRT (application abort requested)
test/scheduler_tests.cpp(112): last checkpoint
test_bitcoin: key.cpp:292: void ECC_Start(): Assertion `secp256k1_context_sign == nullptr' failed.
unknown location(0): fatal error in "set": signal: SIGABRT (application abort requested)
test/scheduler_tests.cpp(112): last checkpoint
test_bitcoin: key.cpp:292: void ECC_Start(): Assertion `secp256k1_context_sign == nullptr' failed.
unknown location(0): fatal error in "is": signal: SIGABRT (application abort requested)
test/scheduler_tests.cpp(112): last checkpoint
ttest/scheduler_tests.cpp(112): last checkpoint
test_bitcoin: key.cpp:292: void ECC_Start(): Assertion `secp256k1_context_sign == nullptr' failed.
unknown location(0): fatal error in "switchover": signal: SIGABRT (application abort requested)
test/scheduler_tests.cpp(112): last checkpoint
test_bitcoin: key.cpp:292: void ECC_Start(): Assertion `secp256k1_context_sign == nullptr' failed.
unknown location(0): fatal error in "AreInputsStandard": signal: SIGABRT (application abort requested)
test/scheduler_tests.cpp(112): last checkpoint
test_bitcoin: key.cpp:292: void ECC_Start(): Assertion `secp256k1_context_sign == nullptr' failed.
unknown location(0): fatal error in "script_build": signal: SIGABRT (application abort requested)
test/scheduler_tests.cpp(112): last checkpoint
test_bitcoin: key.cpp:292: void ECC_Start(): Assertion `secp256k1_context_sign == nullptr' failed.
unknown location(0): fatal error in "script_json_test": signal: SIGABRT (application abort requested)
test/scheduler_tests.cpp(112): last checkpoint
test_bitcoin: key.cpp:292: void ECC_Start(): Assertion `secp256k1_context_sign == nullptr' failed.
unknown location(0): fatal error in "script_PushData": signal: SIGABRT (application abort requested)
test/scheduler_tests.cpp(112): last checkpoint
test_bitcoin: key.cpp:292: void ECC_Start(): Assertion `secp256k1_context_sign == nullptr' failed.
unknown location(0): fatal error in "script_CHECKMULTISIG12": signal: SIGABRT (application abort requested)
test/scheduler_tests.cpp(112): last checkpoint
test_bitcoin: key.cpp:292: void ECC_Start(): Assertion `secp256k1_context_sign == nullptr' failed.
unknown location(0): fatal error in "script_CHECKMULTISIG23": signal: SIGABRT (application abort requested)
test/scheduler_tests.cpp(112): last checkpoint
test_bitcoin: key.cpp:292: void ECC_Start(): Assertion `secp256k1_context_sign == nullptr' failed.
uunknown location(0): fatal error in "script_combineSigs": signal: SIGABRT (application abort requested)
test/scheduler_tests.cpp(112): last checkpoint
test_bitcoin: key.cpp:292: void ECC_Start(): Assertion `secp256k1_context_sign == nullptr' failed.
unknown location(0): fatal error in "script_standard_push": signal: SIGABRT (application abort requested)
test/scheduler_tests.cpp(112): last checkpoint
test_bitcoin: key.cpp:292: void ECC_Start(): Assertion `secp256k1_context_sign == nullptr' failed.
unknown location(0): fatal error in "script_IsPushOnly_on_invalid_scripts": signal: SIGABRT (application abort requested)
test/scheduler_tests.cpp(112): last checkpoint
test_bitcoin: key.cpp:292: void ECC_Start(): Assertion `secp256k1_context_sign == nullptr' failed.
unknown location(0): fatal error in "script_GetScriptAsm": signal: SIGABRT (application abort requested)
test/scheduler_tests.cpp(112): last checkpoint
test_bitcoin: key.cpp:292: void ECC_Start(): Assertion `secp256k1_context_sign == nullptr' failed.
unknown location(0): fatal error in "script_FindAndDelete": signal: SIGABRT (application abort requested)
test/scheduler_tests.cpp(112): last checkpoint
test_bitcoin: key.cpp:292: void ECC_Start(): Assertion `secp256k1_context_sign == nullptr' failed.
unknown location(0): fatal error in "script_HasValidOps": signal: SIGABRT (application abort requested)
test/scheduler_tests.cpp(112): last checkpoint
test_bitcoin: key.cpp:292: void ECC_Start(): Assertion `secp256k1_context_sign == nullptr' failed.
unknown location(0): fatal error in "creation": signal: SIGABRT (application abort requested)
test/scheduler_tests.cpp(112): last checkpoint
test_bitcoin: key.cpp:292: void ECC_Start(): Assertion `secp256k1_context_sign == nullptr' failed.
unknown location(0): fatal error in "operators": signal: SIGABRT (application abort requested)
test/scheduler_tests.cpp(112): last checkpoint
test_bitcoin: key.cpp:292: void ECC_Start(): Assertion `secp256k1_context_sign == nullptr' failed.
unknown location(0): fatal error in "sizes": signal: SIGABRT (application abort requested)
test/scheduler_tests.cpp(112): last checkpoint
test_bitcoin: key.cpp:292: void ECC_Start(): Assertion `secp256k1_context_sign == nullptr' failed.
unknown location(0): fatal error in "floats_conversion": signal: SIGABRT (application abort requested)
test/scheduler_tests.cpp(112): last checkpoint
test_bitcoin: key.cpp:292: void ECC_Start(): Assertion `secp256k1_context_sign == nullptr' failed.
unknown location(0): fatal error in "doubles_conversion": signal: SIGABRT (application abort requested)
test/scheduler_tests.cpp(112): last checkpoint
test_bitcoin: key.cpp:292: void ECC_Start(): Assertion `secp256k1_context_sign == nullptr' failed.
unknown location(0): fatal error in "floats": signal: SIGABRT (application abort requested)
test/scheduler_tests.cpp(112): last checkpoint
test_bitcoin: key.cpp:292: void ECC_Start(): Assertion `secp256k1_context_sign == nullptr' failed.
unknown location(0): fatal error in "doubles": signal: SIGABRT (application abort requested)
test/scheduler_tests.cpp(112): last checkpoint
test_bitcoin: key.cpp:292: void ECC_Start(): Assertion `secp256k1_context_sign == nullptr' failed.
unknown location(0): fatal error in "varints": signal: SIGABRT (application abort requested)
test/scheduler_tests.cpp(112): last checkpoint
test_bitcoin: key.cpp:292: void ECC_Start(): Assertion `secp256k1_context_sign == nullptr' failed.
unknown location(0): fatal error in "varints_bitpatterns": signal: SIGABRT (application abort requested)
ttest/scheduler_tests.cpp(112): last checkpoint
test_bitcoin: key.cpp:292: void ECC_Start(): Assertion `secp256k1_context_sign == nullptr' failed.
unknown location(0): fatal error in "compactsize": signal: SIGABRT (application abort requested)
test/scheduler_tests.cpp(112): last checkpoint
test_bitcoin: key.cpp:292: void ECC_Start(): Assertion `secp256k1_context_sign == nullptr' failed.
unknown location(0): fatal error in "noncanonical": signal: SIGABRT (application abort requested)
test/scheduler_tests.cpp(112): last checkpoint
test_bitcoin: key.cpp:292: void ECC_Start(): Assertion `secp256k1_context_sign == nullptr' failed.
unknown location(0): fatal error in "insert_delete": signal: SIGABRT (application abort requested)
test/scheduler_tests.cpp(112): last checkpoint
test_bitcoin: key.cpp:292: void ECC_Start(): Assertion `secp256k1_context_sign == nullptr' failed.
unknown location(0): fatal error in "class_methods": signal: SIGABRT (application abort requested)
test/scheduler_tests.cpp(112): last checkpoint
test_bitcoin: key.cpp:292: void ECC_Start(): Assertion `secp256k1_context_sign == nullptr' failed.
unknown location(0): fatal error in "sighash_test": signal: SIGABRT (application abort requested)
test/scheduler_tests.cpp(112): last checkpoint
test_bitcoin: key.cpp:292: void ECC_Start(): Assertion `secp256k1_context_sign == nullptr' failed.
unknown location(0): fatal error in "sighash_from_data": signal: SIGABRT (application abort requested)
test/scheduler_tests.cpp(112): last checkpoint
test_bitcoin: key.cpp:292: void ECC_Start(): Assertion `secp256k1_context_sign == nullptr' failed.
utest/scheduler_tests.cpp(112): last checkpoint
test_bitcoin: key.cpp:292: void ECC_Start(): Assertion `secp256k1_context_sign == nullptr' failed.
unknown location(0): fatal error in "GetSigOpCount": signal: SIGABRT (application abort requested)
test/scheduler_tests.cpp(112): last checkpoint
test_bitcoin: key.cpp:292: void ECC_Start(): Assertion `secp256k1_context_sign == nullptr' failed.
unknown location(0): fatal error in "GetTxSigOpCost": signal: SIGABRT (application abort requested)
test/scheduler_tests.cpp(112): last checkpoint
test_bitcoin: key.cpp:292: void ECC_Start(): Assertion `secp256k1_context_sign == nullptr' failed.
unknown location(0): fatal error in "skiplist_test": signal: SIGABRT (application abort requested)
test/scheduler_tests.cpp(112): last checkpoint
test_bitcoin: key.cpp:292: void ECC_Start(): Assertion `secp256k1_context_sign == nullptr' failed.
unknown location(0): fatal error in "getlocator_test": signal: SIGABRT (application abort requested)
test/scheduler_tests.cpp(112): last checkpoint
test_bitcoin: key.cpp:292: void ECC_Start(): Assertion `secp256k1_context_sign == nullptr' failed.
unknown location(0): fatal error in "findearliestatleast_test": signal: SIGABRT (application abort requested)
test/scheduler_tests.cpp(112): last checkpoint
test_bitcoin: key.cpp:292: void ECC_Start(): Assertion `secp256k1_context_sign == nullptr' failed.
unknown location(0): fatal error in "findearliestatleast_edge_test": signal: SIGABRT (application abort requested)
test/scheduler_tests.cpp(112): last checkpoint
test_bitcoin: key.cpp:292: void ECC_Start(): Assertion `secp256k1_context_sign == nullptr' failed.
unknown location(0): fatal error in "streams_vector_writer": signal: SIGABRT (application abort requested)
test/scheduler_tests.cpp(112): last checkpoint
...
...
...
*** 103 failures detected in test suite "Bitcoin Test Suite"
FAIL test/test_bitcoin (exit status: 201)

-------------------------------------------------------------------

**Comment by h4x3rotab** [comment]
Solution here: #46. This is caused by wrong libsodium version.
