### ISSUE TITLE
TestNet will not generate 'G' addr - Pool.Gold will ONLY "Faux Payout" to "G" addr

### ISSUE THREAD

**Issue by bilbobits** [BTCGPU/BTCGPU#144]
Strange behaviors the only working pool is pool.gold, they will accept any thing for a -u address, you can enter "BTGIsAScam" and it will enter that as a valid user, thus absolutely no verification is done.

Most interesting is that it only records a 'payout' to valid G addresses, but note that testnet doesn't not generate them and a week ago DEV disabled normal operation of bgoldd now if U don't run -testnet it aborts ( easy to turn this off internally in CPP )

The other interesting thing is even though pool.gold reports a payout, nothing show up in the block explorer, so a testnet payout is really not being made.

It's like all the software is a poorly designed stage or theatre to make it appear that this is legitimate BITCOIN.

**Comment by bilbobits** [comment]
Pool.Gold is highly relevant here they are the only working ( poorly ) pool for BTG, and they're the same people as china-asic, its all the same team, obviously the bgoldd that is not the same as we get on github, and not the same that btg-explorer is using.
Toward of bitcoin-babel is the btg arch

Currently 99% of testnet blocks are mined on pool.gold, it appears that most solo miners have given up, as no blocks are ever found.

The 'payouts' on pool.gold are not real as they never show up on local bgoldd "getbalance", or on the block explorer, again it appears that everyone is on a different blockchain and/or different 'rev' of bgoldd

gettemplate and block numbers show up rather consistent,,so that glue is working, but not much more

This is important as if TESTNET isn't working, how in the hell will main-net ever work???

Why have no other pools even bothered to offer the testnet mining pool? Most likely because no working version of NOMP is working for BTG.

Solo mining is possible, but its a lot of work, with no payback. Thus at this time it cannot be confirmed it works, as if you can't get paid in testnet coin, how in the hell can you get paid in btg mainnet?

**Comment by h4x3rotab** [comment]
Duplicated with: https://github.com/BTCGPU/BTCGPU/issues/135

**Comment by shakilmia** [comment]
#135
