### ISSUE TITLE
Mining on the testnet (offtopic - some)

### ISSUE THREAD

**Issue by jagottsicher** [BTCGPU/BTCGPU#145]
This issue tracker is only for technical issues related to bitcoin-core.

General bitcoin questions and/or support requests and are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).

For reporting security issues, please see the official [Bitcoin Gold website](https://btcgpu.org/).

### Describe the issue
Mining on testnet not possible and by far not documentated well

#### If so, please list the steps to reproduce below:
1. make zminer run
2. point to eu.pool.gold
3. see how all shares are rejected

### Expected behaviour
Tell us what should happen
all shares accepted

### Actual behaviour
Tell us what happens instead
all shares rejected

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of bitcoin-core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.

### Machine specs:
- OS: Windows
- CPU:
- RAM:
- Disk size:
- Disk Type (HD/SDD):

There are severeal issues with the mining and the "official" minning pool eu.pool.gold
- The description how to start mining on the website minepool.gold could only be worse reading: 
1. download miner, 
2. fill in whatever credentials you like, 
3. make it run somehow
- slack invitation outdated
- pool domain not visible, people maby think minepool.gold is a valid address, port unknown

Maybe my general approach is wrong.
I sucessfully compiled the client. then I connected to the testnet. 
I generated an address.
on several windows PC I used zecminer 12.6 and filled in the credentials ,  btw: ssl not possible?
my config looks like this:

> -zpool eu.pool.gold:3044
> -zwal mvuxscWCXXXXXXXXXXXXXXXXXXXXXXbAy9EDg.jagottsicher
> -zpsw z
> -ftime 1
> -i 6
> -tt 75
> --nofee
> -allpools 1
 
Result connection done, all shares rejected. Also the miner shows 0.00 Hashrate. Hard to complain to the miner, because ZEC it is minig properly.

In the pool's stats I see lots of G-adresses. G-Adresses needed or not?
How to come to some testbgold? any faucet availalble?
The address I used does not eppear in the stats even not with the rejected shares, but on the miner new jobs are received.
also the difficulty shown in the miner differs seems tpo differ fro the one shown in the client

Please put a more detailed mining desription on the bgold website.  In 2 days the mainnet will start!

**Comment by bilbobits** [comment]
https://github.com/BTCGPU/BTCGPU/issues?q=is%3Aissue+is%3Aclosed

Read the 'closed' all the answers are in there, why the DEV's choose to hide the answers is not clear, it appears they have entered a denial mode, where they fear any bad information about BTG.

U must use a "G" address on pool.gold, otherwise you will never get a payout.

To generate a 'G' you must run the bgoldd in 'mainnet' mode, which means you must hack the software, as now it aborts if you don't have -testnet, in testnet mode it will NOT generate a 'g' address

Not to worry, cuz even on pool.gold with a 'G' address they're not paying out as the site is largely just for show, I have mined many coin and the explorer shows my  balance as zero,

The code is a serious mess, and these people can't get testnet to work, thus the mainnet will never go live

**Comment by StarbuckBG** [comment]
@bilbobits 
Please stop spamming. We cannot handle your pointless tickets. You can ask all you questions on Slack, not here.
I receive on average 30 emails from you per day.

The pool is working, zminer is maybe not supporting the network. Please check pool.gold repos on github, there are modified and working miners. 
https://github.com/poolgold <https://github.com/poolgold>

**Comment by h4x3rotab** [comment]
I've deleted @bilbobits's redundant replies and will continue if he keep spamming.

**Comment by jagottsicher** [comment]
sorry for the offtopic stuff, didn't realise there is a repo from pool.gold. I will try with some miner from there. Thanks for "cleaning up the issue". I'll close it later.

**Comment by bilbobits** [comment]
https://github.com/BTCGPU/BTCGPU/issues/132

How to mine BTCGPU has been already discussed in detail

**Comment by sammy007** [comment]
Stop mining on testnet retards.

**Comment by oliverw** [comment]
By the way. Does anyone else trouble to mine a single block on testnet?
