### ISSUE TITLE
https://btcgpu.org/ Shows 8 pools, but ONLY "Pool.Gold" is working, but it doesn't really Payout!

### ISSUE THREAD

**Issue by bilbobits** [BTCGPU/BTCGPU#146]
https://btcgpu.org/

I have tested all the pools mentioned at the ORG site, only Pool.Gold is working, tell us what other pools are working?

Pool.Gold is NOT paying out, they only payout to "G" address, but they don't really payout as nothing ever shows up on 'bgold-cli getbalance' or the explorer site.

**Comment by StarbuckBG** [comment]
Man.
G addresses are for MAIN NETWORK.
We are currently in testnet period. Use “n” or “m” address to receive payment.

**Comment by h4x3rotab** [comment]
@StarbuckBG 

BTW, why don't you reach out to Martin directly? He is in the slack channel. You can also reach to the support of pool.gold. You have created so many redundant issue. Please stop abusing GitHub.
