### ISSUE TITLE
What is going on with pool.gold?

### ISSUE THREAD

**Issue by Ayms** [BTCGPU/BTCGPU#147]
Posting here since this is the official btg mining pool

Why is pool.gold accepting G addresses and other strange ones (t, btc, etc) instead of testnet m addresses?

Why is pool.gold not showing the payment txs? OK because there are none (checked on btgexp.com) but we don't see on the site where to get this info, why is pool.gold not paying anybody although the site is indicating the contrary?

**Comment by StarbuckBG** [comment]
First of all you can use https://github.com/poolgold to write the issues there.
Then:
Currently the addresses that are used by most of the people are not valid for the BTG network. This is normal as the testnet addresses are starting with m or n but some of the people test with t, 1, 3, z, G addresses etc. In order not to block the test process I have disabled the connection check that is made to verify address as that way people will get rejected upon connection and they will look for the reason in their machine or will just deny pool.gold as a pool.
Upon a transaction currently I'm checking if address is correct and if it is valid for the BTG Testnet I'm sending the transaction to the address. Else I'm keeping the transaction in the pool. If you want to receive any Testcoin Gold I can send to you if you provide valid testnet BTG address. 
In the explorers you can check for address : mr3mGSeQafdft7jgZMM2N5DcewmHyK2f3r I'm sending the payments to valid addresses from there.

**Comment by StarbuckBG** [comment]
Sorry, wrong address. Check this : http://btgblocks.com/testnet/address/mjm6rYeeAJyr9ZiXQqUMdzYrj3xyWYtdZy
Over 373 BTG send in the BTG testnetwork to valid addresses.

**Comment by Ayms** [comment]
Posted here since I thought poolgold repo was more for conf issues

Then OK, I checked one of the worker with a correct address msvzhM7J5Qp9vQpusQVmugrsGSVQoJt6pZ and we see the payments (on btgexp but how can we see them on pool.gold?) 

I don't really get why quasi all people are using wrong addresses (they can get G addresses but not m ones ???)

I just modified this if it can be useful for some people: https://github.com/Ayms/bitcoin-wallets#use---convert-bitcoin-addresses

Probably you are right not to block them, now the site could indicate that the addresses are wrong (and/or provide the correct corresponding converted addresses)

Then too bad that I changed my testnet valid address for a G one, will revert to the correct one

**Comment by StarbuckBG** [comment]
1. I'm currently using sendMessage stratum method to send message to mining software that the address is invalid upon registration to the pool. I hope people see it.
I will add also a box in the site that currently it is a testnet mining.
2. I don't know why people are using G addresses. Maybe they got them from exchanges. 
btw I use http://btgblocks.com/testnet to check the transactions. 
3. I will consider adding a payment section in the site showing payments to a give address.

**Comment by Ayms** [comment]
I know that you are busy so I will not insist here but testnet/mining pool is therefore not really tested, you can close this or maybe it's better to leave it open until mainnet is active, comments:

1- I don't think that people see it because I did not, what is strange is that they apparently don't see either that they are not paid

2- thanks for the link (the official btg explorer?), so people are trying to use mainnet addresses on the testnet, hope they know they should not (I suppose that the only replay protection between both is not to use the same addresses)

3- that's a minimal requirement I think

**Comment by krtschmr** [comment]
@StarbuckBG an announcing would make sense and then simply deny non-valid addresses. Miner need to become aware of what they are doing. I even know people who thought they are literally mining (and they went nutz after i told them they have 0 income).

When can we expect mainnet?

**Comment by Ayms** [comment]
I don't want to bother but I am not very convinced in fact by the answers received so far, because it seems to elude some trivial things that must be there and some others that must protect people, whether they know what they are doing or not (looking at the site people think that they are paid for example, while they are not), giving somewhere a feeling of lack of credibility to the project for a pre-launch/testnet phase

**Comment by h4x3rotab** [comment]
@Ayms Just FYI, unique address format does nothing with replay protection. It’s just a way to avoid accidental cross-chain payment.

**Comment by sammy007** [comment]
@h4x3rotab is it possible to generate valid mainnet address and pubScriptKey for it already? I need it for dev fees.

**Comment by Ayms** [comment]
> Just FYI, unique address format does nothing with replay protection. It’s just a way to avoid accidental cross-chain payment.

??? what do you mean? And what do you mean by "unique address format"? There is no "unique address format", whatever version you use the addresses will always derive to the same hash (p2pkh) of the pub key as it is designed today, then if there are no other protection (like sighash_forkid) a btg testnet tx can be replayed on btg mainnet, except if people know that they should not reuse the same addresses

Probably it's unlikely but the concern here is more that testnet + gold mining pool just look like a mess, people don't know what they are doing and you don't tell them

> I will consider adding a payment section in the site showing payments to a give address

This one in fact made me a bit angry, sorry, that's a basic requirement, considering it as optional looks like just kidding with people

> is it possible to generate valid mainnet address and pubScriptKey for it already? I need it for dev fees.

What do you mean? Of course it is, and quite easy, what's the problem?

**Comment by bilbobits** [comment]
I have brought thus up for weeks, the pool.gold like exchange started this scam two weeks ago, the DEVS just delete,

BTG is a scam, and the devs are part of the scam,

The dev's even removed the ability of testnet to generate 'G' address

If you see the blocks paid, then go to explorer you can see they're not paid, nothing is paid, nothing actually works, 100% of all the BTG software is a fraud

miner --u "BTGisaSCAM" --p x --Server pool.gold --port 3044

The above is also a valid address on pool.gold because pool.gold doesn't validate any address they just let people hash equihash, then pool.gold redirects the hashes, its all part of the scam

**Comment by StarbuckBG** [comment]
@Ayms 
1. Addresses in testnet and main net are different. There is no way to replay transaction from testnet to mainnet. All of the keys are different, the addresses

**Comment by Ayms** [comment]
Please let the discussion go through, btg is certainly not a scam, see above, read again and test the correct addresses

**Comment by StarbuckBG** [comment]
@Ayms please check above comment and if you want delete yours about the scam thing. I will delete mine after that.

**Comment by Ayms** [comment]
@bilbobits and others, please stop the trolling, I don't know about the future of BTG but btg folks are doing a great job

@StarbuckBG 

We can continue the discussion by email if you prefer, but as I wrote before, testnet, mainnet, whatever net, whatever coin addresses are just the same, the keys are the same. The replay protection just protects from one network to another, and then not from a testnet to a mainnet of the same network except if you have the same replay protection between both, or if people know that they should not use the same addresses, again this is somewhere unlikely because it would mean that btg dev rewards + mining pools are using the same addresses for testnet and mainnet, since they are first receiving/originating the transactions, and probably this is not the case, I think that it is well known for bitcoin or others and the simple solution is just not to reuse the same addresses

same address above = same hash of the public key and this does not depend on the network versions, so it is the same for every networks

Then, coming back to the initial point it would be good to see that people are mining correctly on pool.gold just not waiting like crazy not understanding what they are doing to mine mainnet

Not sure what you mean by "However pool.gold will switch immediately from testnet to main net from moment 0. I hope that will please the people, as there is clear information, even on the pool.gold site that it is written TESTNET!!!"

**Comment by sammy007** [comment]
Could you just mine different coin really? It's impossible to use testnet due to idiotic waste mining.

**Comment by sammy007** [comment]
If you really want to help, please spam testnet with both segwit and normal transactions, at least 5-10 per block. If you still want to mine testnet, please don't 90% of blocks so diff will go down and will be usable for testing again.

**Comment by StarbuckBG** [comment]
@sammy007 please behave and stop insulting people. I will start deleting your posts. 
When you want to test, use regtest. Testnet is for testing the main net on real conditions - here are real conditions. You can also build the code, rise 2 nodes and connect them to each other with connect = xxx.xxx.xx.xx .

**Comment by sammy007** [comment]
@StarbuckBG I know how to launch private network, you don't have to teach me. But first you prolly should create a branch with a different testnet with HF in a first block after genesis, otherwise it's all mess to deal with.

**Comment by jagottsicher** [comment]
I reference #145 here, seems to be similar problem.
Sorry, but the [Poolgold rep for mining stuff](https://github.com/poolgold/ClaymoreBTGMiner) is the original nanopool one with an edited readme. 

I used that settings already, but minig doesn't work. all shares are rejected. I use an address created with self compiled client on the testnet. Anyway the Address in the config/command line should not matter.

Are the addresses checked by the pool at all or can I mine "anonymously"? I just want to rule out some wrong settings. I tried on various computers. mining at any Zcash-pool works fine. 

@sammy007 @bilbobits Please don't fill this with comments how bad bgold, the dev team or the pool are. I feel already silly enough because of my awkward noob questions, but other people maybe have similar problems and noob questions. I think bGold is a good idea and gives the control back to the user, taking it from the miner, and trolling doesnt help, while @StarbuckBG does a good job and has for sure a full schedule and better things to do than cleaning up after your visit.

**Comment by StarbuckBG** [comment]
I think that all of the current pools are using my modification of z-nomp. Can you give me a bit more information about the software that you are using for mining ? I can also connect one my my machines to your pool. There is no address validation or something similar, the software is running out of the box and it is possible that the mining software needs some modifications.

You can contact me in Slack, there is a group for the pool operators so the communication is faster.

**Comment by jagottsicher** [comment]
Not about the pool Software, I will go later for that. It is about the client.

I use an unmodified Claymore's ZCash AMD GPU Miner, Latest version v12.6 - BTG.
but with a config like this:

> -zpool eu.pool.gold:3044
> -zwal mvuxscWCJGD8Fzs441ap3Cj5abcbAy9EDg.jagottsicher
> -zpsw z
> -ftime 1
> -i 6
> -tt 75
> --nofee
> -allpools 1

That should make it. The status lines say I receive work, but all shares I deliver are rejected.

**Comment by StarbuckBG** [comment]
Could you remove the other lines from the file epools.txt ?

**Comment by jagottsicher** [comment]
made all lines in epools.txt a comment by #

**Comment by jagottsicher** [comment]
made all lines in epools.txt a comment by "#"
same result/outcome.
on one computer (but one with an old GPU) I can see 

`timestamp 1eca4 GPU #0 returned incorrect data! 2014f2`

in the command line and in the log. the hex at the end of the line differs.

another one (where the screenshot is from) does not show that.

both show zero hashrate. feeling silly and clueless.

**Comment by StarbuckBG** [comment]
Do you use : eu.pool.gold:3044 ? I cannot understand the problem :/
Which version of Claymores ZEC miner do you use?

**Comment by jagottsicher** [comment]
I use the miner 12.6 - downloaded from your rep, which you forked from nanopool
As you can see I can connect to the pool eu.pool.gold:3044, I receive workloads, but all my shares are rejected by the pool. also there is zero hashrate shown.

The problem is simply that the pool rejects all my shares.

I thought it is a pool problem, but seems other miner can connect.

**Comment by StarbuckBG** [comment]
We never had such problem :/

**Comment by jagottsicher** [comment]
I see. Thanks. I'll go on trying.

**Comment by jagottsicher** [comment]
I see. Thanks. I'll go on trying. feel free to close the origin topic, if solved, seems I have a specific local problem, cause my zecminer behaves the same now. Thanks!

**Comment by sammy007** [comment]
My solo mining solution is available for Linux users https://github.com/sammy007/zcash-proxy/releases/tag/v2.0.0 works with testnet and hopefully with mainnet. Contains 2% dev fee via coinbase transaction.

**Comment by StarbuckBG** [comment]
You can also setup locally z-nomp pool. It happens for about 1 hours - https://github.com/poolgold/z-nomp-bitcoin-gold <https://github.com/poolgold/z-nomp-bitcoin-gold>

**Comment by jagottsicher** [comment]
different driver problems on different machines. works now.

**Comment by Ayms** [comment]
Initial topic diverted to uninteresting one, closing

**Comment by eaglekoko** [comment]
So, starting with G address is not valid?
If it is not valid, what should I do? 
I did't get any message from you about this issue

**Comment by h4x3rotab** [comment]
G addresses are valid BTG mainnet addresses. The issue was about the
testnet where the correct prefix is n or m.
