### ISSUE TITLE
I bilbobits will stop writing inappropriate topics to BTCGPU github issue tracker because I disturb the developers while they are working.

### ISSUE THREAD

**Issue by bilbobits** [BTCGPU/BTCGPU#149]
**I bilbobits want to disturb all of the developers and to create useless topics to this issue tracking system, becase developers started deleting my other topics as they have consisted of questions that are answered in the FAQ section of the site.**

**Please excuse the following words, as they are not applicable to this topic, and only show how much I don't understand what is code, development and product and that I have limited capabilities to understand how this crypto currency works.**

I have brought thus up for weeks, the pool.gold like exchange started this scam two weeks ago, the DEVS just delete,

BTG is a scam, and the devs are part of the scam,

The dev's even removed the ability of testnet to generate 'G' address

If you see the blocks paid, then go to explorer you can see they're not paid, nothing is paid, nothing actually works, 100% of all the BTG software is a fraud

miner --u "I <3 BTG" --p x --Server pool.gold --port 3044

The above is also a valid address on pool.gold because pool.gold doesn't validate any address they just let people hash equihash, then pool.gold redirects the hashes, its all part of the scam

***

China pays these guys in bulgaria to run this scam called github.com/btcgpu,, these guys don't even know C++, they just make empty promises and delete any mention that this project is a 100% vaporware

In the meantime the Exchanges Make real money by stealing real BTC, even the blockchain explorer for BTG is a scam as it never reports real 'getbalance' as the code is non-existant.

The Dev's don't care, and now their current plan to deploy main-net is 2018, and people are burning 1000K sols/sec, 400 miners are pissing their rigs into the wind, and U can be certain that pool.gold is redirecting that HASH to real Zcoin's

**Comment by vattay** [comment]
Dude stop clogging this up with your weird complaints. People are trying to get work done. Just because you don't understand how something works doesn't mean it's a scam. A testnet is not for making money, it's for testing the network. Bitcoin also has a testnet. Does that make it a massive scam too?

**Comment by evgenyundefined** [comment]
here working ban system? this dude i thing loose him mind....

**Comment by D3m0nKingx** [comment]
You can report the user, also @h4x3rotab can delete his posts, etc

**Comment by h4x3rotab** [comment]
> I have brought thus up for weeks, the pool.gold like exchange started this scam two weeks ago, the DEVS just delete,

Yes, I will delete all the redundant issues as what all the GitHub maintainers usually do.

> The dev's even removed the ability of testnet to generate 'G' address
Dude, testnet use the same address format as Bitcoin. We only changed the address format of mainnet to avoid to send coins to the wallet of another blockchain accidentally. You should generate "m" or "n" address by testnet daemon.

> If you see the blocks paid, then go to explorer you can see they're not paid, nothing is paid, nothing actually works, 100% of all the BTG software is a fraud
I believe @StarbuckBG has already answered this question. You can see the pool has about 50% coins paid in any blockchain explorer.

> The above is also a valid address on pool.gold because pool.gold doesn't validate any address they just let people hash equihash, then pool.gold redirects the hashes, its all part of the scam
The pool is sending warning messages by stratum protocol when found invalid addresses, though I think it can be further improved.

Any question? Why don't you ask us in slack directly?

**Comment by evgenyundefined** [comment]
You can check G-adresses in block-explorer https://btgexp.com... I try and not find transactions with G-adresses..
