### ISSUE TITLE
I Professor Starbuck admit I'm Over My Head - I Can't Code C++ - I want to go to Greece

### ISSUE THREAD

**Issue by bilbobits** [BTCGPU/BTCGPU#152]
I pity Professor Starbuck, he's got the  devil in China on his back, and that little devil 'hx2bot' on his neck.

Most of us here came to this github to support  BTG, but then we quickly find out that Professor Starbuck can't handle the truth, nor can he over-come the NIH factor in his genetics ( Not Invented Here )

The Nutty Professor could have just bought a BTC clone for 0.5 BTC months ago and would have working code prior to the Oct 25 'fork-launch', now of course TEAM-BULGARIA & TEAM-ASIC China prefer to edit other peoples posts.

Been out of here for days, came back to add 'color' to the build.

Still waiting for scammy-sammy-007 to deliver his working solo-miner :)

U know what we Greeks say about "Bulgarians"?? We say we Greeks ain't got nothing, but we know what we have.

Kali-Spira, out of here.

**Comment by StarbuckBG** [comment]
I have reported you. We have hundreds of pointless tickets from you. I'm tired of that.
