### ISSUE TITLE
Testnet v2 - i think wrong sol per second.

### ISSUE THREAD

**Issue by evgenyundefined** [BTCGPU/BTCGPU#153]
Re make daemon, connect to testnetv2 and on rpc command getmininginfo see "networkhashps": 528197767930.8387.
I don't think is correct. And same see on Blockexplorer https://btgexp.com/network

**Comment by StarbuckBG** [comment]
This is based on leftovers from bitcoin network as some of the nodes were having this data in their local DB. It will fix after some blocks.

**Comment by evgenyundefined** [comment]
Now 1210401 block its ~80 blocks but hashrate 226780599851.2383 need wait more blocks?

**Comment by shakilmia** [comment]
any halpe me

**Comment by sammy007** [comment]
Prolly related to stupid powLimit they specified for premine period.
