### ISSUE TITLE
Testnet faucet

### ISSUE THREAD

**Issue by rakeshiitd** [BTCGPU/BTCGPU#154]
Is there any faucet available for BTG testnet if not suggest a good way to get some testnet coins.

**Comment by h4x3rotab** [comment]
There's no faucet so far. Any one who would like to make one? I believe pool.gold can provide enough testnet coins for the faucet.

**Comment by StarbuckBG** [comment]
Please post your testnet address and I will supply coins.

**Comment by wizzfile** [comment]
t1VdeaW6gc745miFbGqegEmUdanwCgg5GTb

**Comment by StarbuckBG** [comment]
This is transparent zcash address… 
I need m or n BTG testnet address.

**Comment by evgenyundefined** [comment]
mteELnKxLELsz7Z5LHwqs1DZ2keTri5Mrb

**Comment by jagottsicher** [comment]
t1emzuNbemjqnEhEue74NL3BxsR4cA1ajfP
mvuxscWCJGD8Fzs441ap3Cj5abcbAy9EDg

could you please provide some testnet bgold to the m address?

**Comment by rakeshiitd** [comment]
Thanks @StarbuckBG. This is my address-: myYY2CJjvmeYsKEmfNq3axsK9Rkrfci88b

**Comment by wizzfile** [comment]
miYqVUG2f4sNTMsKVdJj43sumZQcVbHU5Z

**Comment by wjcloud** [comment]
n4YJQE8pmYhoJudpycCrYqrGznoLbZ1psa Thanks!

**Comment by cyprox** [comment]
XRKx7yRdunor9F94ercH546kibz3eHVcui 
Thanks a lot for testing have fun

**Comment by tsaomichael** [comment]
msgdwr5mvLX7XHNrGNiRfhCqKfdYYsqvuh 

Thank you.

**Comment by adbatista** [comment]
mp65iKEfXTfycZPKM2N68vbWbDtqLx4p98

Thank you :)

**Comment by 2tvenom** [comment]
moLmYkWNP5LwePyPRNEQdzueYr3yFuuSHP

**Comment by h4x3rotab** [comment]
We are glad to inform you that we finally had a testnet reset and launched our official testnet faucet:
https://github.com/BTCGPU/BTCGPU/wiki/Testnet-v3

**Comment by oliver-zhao** [comment]
mubSzQNtZfDj1YdNP6pNDuZy6zs6GDn61L

Thanks.

**Comment by guchenglin111** [comment]
mgAfBUzMoHFs5zGjaE8sY6WfkuAwTowHdF
mrAD6MAxZddSXhFPBqwptZDn52nE4qKPaG
n1XQeqSmphQxXVCABC8EKvgCPa9WneHNeA
n1JQS9Nr794yGLLqezKn2UWjPVpXEfYuJs
n242mL96NaprqzPyrefdAnmLuF8DqNoryG
Thanks.

**Comment by xkf4806** [comment]
Hello, the testnet faucet is unavailable recently, could anyone help me send some coins to the test address?
n2jBgtqyzfA4TUmX7pe897NaDB1J6cQN9Y

Thanks.

**Comment by bitcoingold-readonly** [comment]
Will do shortly.

**Comment by h4x3rotab** [comment]
@xkf4806 250783be33c4fcb57d957f208049343b763868027f2d69cd0e97dd6588dc4e99

**Comment by xkf4806** [comment]
> @xkf4806 250783be33c4fcb57d957f208049343b763868027f2d69cd0e97dd6588dc4e99
---
 Hi, the transaction is still in unconfirmed state after 17 hours, I'm stuck on it. 
https://github.com/BTCGPU/BTCGPU/issues/154#issuecomment-449848557
