### ISSUE TITLE
What is going on with testnet?

### ISSUE THREAD

**Issue by Ayms** [BTCGPU/BTCGPU#155]
Between today and yesterday the network sol/s apparently raised from 1.7 M to 150 G (x88000), which is now more than 600 time the total zcash hashrate (then completely unlikely), blocks are mostly mined by the same entities 

What are you guys doing?

**Comment by evgenyundefined** [comment]
https://github.com/BTCGPU/BTCGPU/issues/153 look here

**Comment by Ayms** [comment]
I already saw this, this does not explain anything

**Comment by Ayms** [comment]
Then now it has all of a sudden decreased to 75 G (just 75 G ops/s less, nothing... and nothing in less than a hour)

**Comment by Ayms** [comment]
And now it's showing 44.71 KSol/s for all the network, incredible, no? Less than the mining pools...

BTG team, please explain all of this

**Comment by StarbuckBG** [comment]
Please check now…
You can check how the code is working and the to ask us to explain again.
As it has been said this data are leftovers from bitcoin test network.

**Comment by Ayms** [comment]
>You can check how the code is working and the to ask us to explain again.
>As it has been said this data are leftovers from bitcoin test network.

I don't understand the first sentence but seem to detect some strange tone

Going to 150 G ops/s is just impossible without intentional/outside modifications, as shown above it just dropped to a normal level just after I posted here (coincidence?)

Please explain what happened with more than one sentence and what you call "leftovers"

PS: btw pool.gold does not seem to work at all

**Comment by Ayms** [comment]
Closing as I suspected what you did is obvious
