### ISSUE TITLE
Change default port number

### ISSUE THREAD

**Issue by prusnak** [BTCGPU/BTCGPU#16]
to something else than 8333 so it will not collide with Bitcoin.

**Comment by prusnak** [comment]
Bitcoin Cash did not listen to my advice and this caused big troubles later on. See https://github.com/Bitcoin-ABC/bitcoin-abc/issues/25

**Comment by h4x3rotab** [comment]
Agree. We should probably change both the rpc and p2p port number.

**Comment by arshadshaheen** [comment]
Great attitude towards suggestions

**Comment by daira** [comment]
I suggest also changing the network magic strings if that hasn't already been done.

**Comment by leto** [comment]
@daira I agree about having unique ClientID, added an issue for that: https://github.com/BTCGPU/BTCGPU/issues/34

We have chosen different port numbers for mainnet and testnet (8338 and 18338) which is tracked by https://github.com/BTCGPU/BTCGPU/pull/25

**Comment by StarbuckBG** [comment]
I have changed the Magic and left the port numbers as they are in bitcoin. The user will be able to download BTC blockchain from both BTC nodes and BTG nodes, which will increase the speed. Having different magic will differentiate the networks after the fork.

**Comment by StarbuckBG** [comment]
@leto @daira please advice if that solution may lead to problems.

**Comment by leto** [comment]
@StarbuckBG not using unique port numbers will cause horrific problems in the future, and make Cross Chain Atomic Swaps (XCATs) harder, and generally will annoy the entire community of people that have been working on coins for years

**Comment by StarbuckBG** [comment]
@leto 
We will change the ports then. This will make a bit harder the initial sync of the chain, but I would rise 10 - 15 full nodes to supply the network.

**Comment by h4x3rotab** [comment]
Let's change the port number and add a flag to enable the bootstrap mode on demond.

**Comment by h4x3rotab** [comment]
Closing this issue as the port number has been changed to 8338. (PRC port number has been changed to 18338).

**Comment by StarbuckBG** [comment]
@prusnak can we speak with you about the eventual integration of BTG in Trezor. We are currently making some changes on the Replay protection and we need you for opinion how to improve it so there will be less work for the wallet providers in future? 
I'm in Slack as Martin Kuvandzhiev in BTG channel. 
Thanks for all of the early support, it means a lot to all of us! You suggestions and requests provider major positive impact on the way BTG works!
