### ISSUE TITLE
Light wallet before mainnet launch

### ISSUE THREAD

**Issue by evadogstar** [BTCGPU/BTCGPU#164]
We need light wallet before mainnet launch. Electron Gold or html&js

**Comment by jcyktor** [comment]
[btgwallet.online](https://btgwallet.online/)
[mybtgwallet](https://mybtgwallet.com/)

Both are available to be run locally offline.

**Comment by vilhelmgray** [comment]
@jcyktor Do any of these light wallets allow users to import private keys from Bitcoin core clients?

**Comment by jcyktor** [comment]
@vilhelmgray it looks like mybtgwallet supports converting a BTC mneumonic seed to create the BTG wallet. I'm not sure about private key directly.

**Comment by francois007** [comment]
The question is as follows:
they are developers or chickens thieves!

Without the core wallet I don't provide my private key to external services!
I confirm my opinion... 1 satoshi for this coin!

Good luck to all.

**Comment by evadogstar** [comment]
It's the chance to return and make bitcoin decentralized. ASICs must go away.

**Comment by francois007** [comment]
I agree with you but you have to agree with me if I say that without a wallet core it is impossible to run a node or create a mining pool or make the wallet out of the various exchanges.
Without the core wallet this project will fail.

**Comment by evadogstar** [comment]
@fanquake It have working code. What is the problem? Only need to sync full blockchain.

**Comment by evadogstar** [comment]
URGENT! SCAM WALLTES ON THE SECOND POST AND BTG IS SCAM COIN!

**Comment by h4x3rotab** [comment]
I edited the reply of @jcyktor to exclude mybtgwallet.com

**Comment by h4x3rotab** [comment]
I don't see the need of this thread. Closing.

Please don't abuse GitHub issue for non-development related issue.

**Comment by evadogstar** [comment]
@h4x3rotab Non-developed issue? When developers ignore threads where I request good wallet to get G address to mine on mainnet start and now my mined coin was stolen? It's non-developer issue??? Really?
