### ISSUE TITLE
Electrum Gold Wallet

### ISSUE THREAD

**Issue by JoelBradley** [BTCGPU/BTCGPU#165]
Electrum Gold Wallet https://electrum-gold.org

**Comment by anthony19114** [comment]
Where is the source? Only binaries https://github.com/JoelBradley/BitcoinGold/releases
Are you kidding me? It even says explore source on the website, but the link is invalid.

**Comment by JoelBradley** [comment]
I did not post this. Someone from Latvia logged into my account yesterday it would seem.

**Comment by anthony19114** [comment]
Well delete it

**Comment by anthony19114** [comment]
Delete the TEXT by clicking the PENCIL icon
