### ISSUE TITLE
8 hours till launch no release? Whats up?

### ISSUE THREAD

**Issue by cryptosi** [BTCGPU/BTCGPU#167]
This issue tracker is only for technical issues related to bitcoin-core.

General bitcoin questions and/or support requests and are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).

For reporting security issues, please see the official [Bitcoin Gold website](https://btcgpu.org/).

#### If so, please list the steps to reproduce below:
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of bitcoin-core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.

### Machine specs:
- OS:
- CPU:
- RAM:
- Disk size:
- Disk Type (HD/SDD):

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by saunder1500** [comment]
Electrum Gold released https://www.electrum-gold.org

**Comment by cryptosi** [comment]
![image](https://user-images.githubusercontent.com/9975784/32698279-11774790-c7a3-11e7-9630-996c151e7765.png)

**Comment by cryptosi** [comment]
![image](https://user-images.githubusercontent.com/9975784/32698311-bfb13582-c7a3-11e7-842c-a0d29cc9872d.png)
https://www.virustotal.com/#/file/888933536e6ec63a660d4def4d2c1b46f0da9dc3a0827596e6c6bdd2eacb1704/detection

**Comment by saunder1500** [comment]
This is not my commented! I have never put any file on GitHub.



    On Sunday, November 12, 2017, 6:19:50 AM EST, Crypto.si <notifications@github.com> wrote:  
 
 

https://www.virustotal.com/#/file/888933536e6ec63a660d4def4d2c1b46f0da9dc3a0827596e6c6bdd2eacb1704/detection

**Comment by cryptosi** [comment]
@saunder1500  Isnt this your repository ? 
![image](https://user-images.githubusercontent.com/9975784/32700915-90a8a918-c7cc-11e7-8334-01fd7d74673a.png)

**Comment by saunder1500** [comment]
Yes it`s mine! Look like account hacked, because I do not have any other idea, 

    On Sunday, November 12, 2017, 11:12:01 AM EST, Crypto.si <notifications@github.com> wrote:  
 
 
@saunder1500 Isnt this your repository ?

**Comment by saunder1500** [comment]
No sory  this not my Repositories, but this is my account
 

    On Sunday, November 12, 2017, 11:12:01 AM EST, Crypto.si <notifications@github.com> wrote:  
 
 
@saunder1500 Isnt this your repository ?
