### ISSUE TITLE
Change address version

### ISSUE THREAD

**Issue by prusnak** [BTCGPU/BTCGPU#17]
I suggest to change the address version to something different, so it is obvious the address is a Bitcoin Gold address. (It can start with G for example). Don't forget to change also address version for P2SH!

**Comment by prusnak** [comment]
Bitcoin Cash did not listen to my advice and this caused big troubles later on. See https://github.com/Bitcoin-ABC/bitcoin-abc/issues/35

**Comment by leto** [comment]
This seems like a good move to improve usability for end-users, :+1:

**Comment by prusnak** [comment]
Remember it takes days/weeks to release a new firmware for hardware wallets with support for new coin, so don't keep major technical changes for later, if you want support.

**Comment by h4x3rotab** [comment]
Thanks for the reminder. New address format is planned for the next release. The first launch won't introduce new address format.

**Comment by prusnak** [comment]
It does not make sense. It's VERY hard to introduce new address format after the coin starts to be actually used. Please include new address format in the first release. Don't repeat the same mistakes that Bitcoin Cash did.

**Comment by leto** [comment]
Changing the address format in the 2nd release seems like a usability nightmare, for exchanges most importantly, which take days to weeks to install new versions of full nodes in other cryptocoins. Then from the perspective of an end-user, this is very confusing UI/UX

**Comment by jayarjo** [comment]
But why in second release, what's the point?

**Comment by saleemrashid** [comment]
@h4x3rotab Services and wallets will have to make lots of changes to use Bitcoin Gold anyway. Furthermore, you promise strong replay protection in #18 which will require more changes. Therefore, there is absolutely no reason why you cannot change the address version unless you are attempting to create confusion and will not in fact use replay protection.

**Comment by h4x3rotab** [comment]
Make sense. Finally I decide to change the address format before launch.

**Comment by leto** [comment]
@h4x3rotab have we decided to make Bitcoin Gold addresses start with a `G` and a P2SH BTG addresses start with a `g` ? If that is the spec, than I think we can move forward with various things. This effects Electrum support, so I am interested to know.

**Comment by Ayms** [comment]
Then? Nothing since 4 days while the launch is supposed to happen soon, what is the btg address format?

Still wondering how you could possibly put everything together for the launch, no testnet, no mainnet, no address format, no support for all wallets, replay protection to be tested, no serious mining pools, no serious exchanges, etc

**Comment by h4x3rotab** [comment]
Changed the address version to 38 for P2PKH and 23 for P2SH: https://github.com/BTCGPU/BTCGPU/pull/80

This results in base58 prefix "G" and "A" for two kins of addresses.

**Comment by h4x3rotab** [comment]
Closing this issue due to #80 has been merged.

**Comment by abrkn** [comment]
https://github.com/abrkn/shilly/issues/40
