### ISSUE TITLE
Launching a Pool: ./bgoldd does nothing.

### ISSUE THREAD

**Issue by ICOBOXER** [BTCGPU/BTCGPU#170]
This issue tracker is only for technical issues related to bitcoin-core.

General bitcoin questions and/or support requests and are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).

For reporting security issues, please see the official [Bitcoin Gold website](https://btcgpu.org/).

### Describe the issue
I am launching a pool. coin launch does nothing.  

./bgoldd does nothing.

### Can you reliably reproduce the issue?

Yes

#### If so, please list the steps to reproduce below:
1. Downloaded git
2. compile
3. execute ./bgoldd

No action, no errror, nothing just stays there.

### Expected behaviour
Wallet start.

### Actual behaviour
Nothing happens. no Error, no nothing.

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.
![image](https://user-images.githubusercontent.com/33381147/32703034-1c470a1e-c7be-11e7-8b8c-fc9ae15e672f.png)

**Comment by Robin-73** [comment]
check the debug.log for more information inside the .bitcoingold folder

**Comment by hubdr** [comment]
While bgoldd is running you can use bgold-cli to send commands to bgoldd
`bgold-cli help` for a list of commands

**Comment by thematosek** [comment]
You need to make config file
.bitcoingold/bitcoin.conf (not bitcoingold.conf)
It helped me, so it sure should help you too

**Comment by thematosek** [comment]
Btw. as pool operator you should know basic troubleshooting

**Comment by ICOBOXER** [comment]
Thanks! that worked.
