### ISSUE TITLE
My Pool Wallet is not downloading Blockchain.

### ISSUE THREAD

**Issue by ICOBOXER** [BTCGPU/BTCGPU#174]
No errors, but not downloading...

 "deprecation-warning": "WARNING: getinfo is deprecated and will be fully removed in 0.16. Projects should transition to using getblockchaininfo, getnetworkinfo, and getwalletinfo before upgrading to 0.16",
  "version": 150001,
  "protocolversion": 70016,
  "walletversion": 139900,
  "balance": 0.00000000,
  "blocks": 0,
  "timeoffset": 0,
  "connections": 2,
  "proxy": "",
  "difficulty": 1,
  "testnet": false,
  "keypoololdest": 1510516427,
  "keypoolsize": 2000,
  "paytxfee": 0.00000000,
  "relayfee": 0.00001000,
  "errors": "This is a pre-release test build - use at your own risk - do not use for mining or merchant applications"

**Comment by evadogstar** [comment]
https://github.com/BTCGPU/BTCGPU/issues/172

**Comment by Crypto-Lord** [comment]
Have you added in the nodes from issue #172

**Comment by suprnurd** [comment]
Same here, even with all the addnodes from the other post.

{
  "version": 150001,
  "subversion": "/Bitcoin Gold:0.15.0.1/",
  "protocolversion": 70016,
  "localservices": "000000000000000d",
  "localrelay": true,
  "timeoffset": 0,
  "networkactive": true,
  "connections": 5,
  "networks": [
    {
      "name": "ipv4",
      "limited": false,
      "reachable": true,
      "proxy": "",
      "proxy_randomize_credentials": false
    }, 
    {
      "name": "ipv6",
      "limited": false,
      "reachable": true,
      "proxy": "",
      "proxy_randomize_credentials": false
    }, 
    {
      "name": "onion",
      "limited": true,
      "reachable": false,
      "proxy": "",
      "proxy_randomize_credentials": false
    }
  ],
  "relayfee": 0.00001000,
  "incrementalfee": 0.00001000,
  "localaddresses": [
  ],
  "warnings": "This is a pre-release test build - use at your own risk - do not use for mining or merchant applications"
}

**Comment by ICOBOXER** [comment]
yes, added the nodes.

**Comment by setar** [comment]
check open firewall connections to TCP destination  8333 and 8338 ports

**Comment by ICOBOXER** [comment]
They are opened.

**Comment by ICOBOXER** [comment]
Now it is working! Thanks man!
