### ISSUE TITLE
Adjustment of config file

### ISSUE THREAD

**Issue by oliverdorn** [BTCGPU/BTCGPU#175]
ATM bitcoingold uses _.bitcoingold/bitcoin.conf_ as config file. I would suggest to use _.bitcoingold/bitcoingold.conf_ as default config.

Also the daemon states "Bitcoin server starting" on start. Should be "**BitcoinGold** server starting".

Just minor adjustments for better fitting the project.

Regards Oliver

**Comment by evadogstar** [comment]
Money job to change it from Bitcoin Gold to Bitcoin in the future :)

**Comment by D3m0nKingx** [comment]
@oliverdorn I have a PR #163 for this pending

**Comment by h4x3rotab** [comment]
Thank you @D3m0nKingx. But to keep the compatibility I'd suggest to check `bitcoingold.conf` first but fall back to `bitcoin.conf` when not found.

**Comment by D3m0nKingx** [comment]
@h4x3rotab compatibility? There's no "conflicts" by this change :/, no does it need backwards compatibility. it's just the config file for sake of naming consistency. like bitcoin-qt should be bitcoingold-qt for sake if differentiating the coins.

**Comment by h4x3rotab** [comment]
... just in case some people are using the first release and forget to rename it after upgrade

**Comment by D3m0nKingx** [comment]
That's why there's the warning when starting the server informing the user of the naming of the config file ;)

```bash
ader@HP-15-Notebook-PC:~/coins/BTCGPU/src$ ./bgold-cli getinfo
error: Could not locate RPC credentials. No authentication cookie could be found, and no rpcpassword is set in the configuration file (/home/ader/.bitcoingold/bitcoin.conf)
```
*which is adjusted in the PR to the correct name*

defined in:
```bash
bitcoin-cli.cpp:                _("Could not locate RPC credentials. No authentication cookie could be found, and no rpcpassword is set in the configuration file (%s)"),```

**Comment by h4x3rotab** [comment]
It has been changed to `bitcoingold.conf` in #163
