### ISSUE TITLE
Connection, but no blockchain download, minepool offline! What's going on (or what not?)

### ISSUE THREAD

**Issue by jagottsicher** [BTCGPU/BTCGPU#176]
This issue tracker is only for technical issues related to bitcoin-core.

General bitcoin questions and/or support requests and are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).

For reporting security issues, please see the official [Bitcoin Gold website](https://btcgpu.org/).

### Describe the issue
no download of blockchain

#### If so, please list the steps to reproduce below:
1. start bggold client
2. get connection
3. look bored at screen

### Expected behaviour
Tell us what should happen
a fucking awesome fast download of the complete blockchain

### Actual behaviour
Tell us what happens instead
nothing

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of bitcoin-core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.
0.15.0.1

### Machine specs:
- OS:
- CPU:
- RAM:
- Disk size:
- Disk Type (HD/SDD):

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

I compiled the client several times now, got no problem with the testnet.
already added nodes from #172 

Now I have 1 (!) connection, but still no download of any parts of the blockchain.
Needed port are open!
Offical pool [https://mine.pool.gold/](https://mine.pool.gold/) is offline.

Can it be that it is a probelm to runa bitcoin  and a bitcoin gold full node on the same machine, because of a conflict of the ports?

**Comment by lonelywoolf** [comment]
Assumes, this is DDoS-attack on BTG resources. Try add new node: 87.103.203.200:8338

**Comment by Airead** [comment]
Same to me. I have 8 connections but no blockchain downloaded.
```
$ src/BTCGPU/src/bgold-cli getinfo
{
  "deprecation-warning": "WARNING: getinfo is deprecated and will be fully removed in 0.16. Projects should transition to using getblockchaininfo, getnetworkinfo, and getwalletinfo before upgrading to 0.16",
  "version": 150001,
  "protocolversion": 70016,
  "walletversion": 139900,
  "balance": 0.00000000,
  "blocks": 0,
  "timeoffset": 0,
  "connections": 8,
  "proxy": "",
  "difficulty": 1,
  "testnet": false,
  "keypoololdest": 1510537444,
  "keypoolsize": 2000,
  "paytxfee": 0.00000000,
  "relayfee": 0.00001000,
  "errors": ""
}
```

**Comment by jagottsicher** [comment]
thanks. completly need compiled version now. show no errors or hwarnings by -getinfo, but still only one connection.
log says, that upstart works fine, port 8338 open, but after receiving DNS seeds it tries to connect but only gets "Connection refused" with error 111 and 113.

network overload?

**Comment by jagottsicher** [comment]
added lots of nodes, got 2 to 5 connections, but very unstable.
still no download at all.
ideas?

**Comment by tankitty** [comment]
try to add node 43.229.76.42:8338

**Comment by jagottsicher** [comment]
` Loaded 906 addresses from peers.dat  3ms`
and
` 142 addresses found from DNS seeds`
manually added approx 100 addresses.

still the samo problem.

**Comment by h4x3rotab** [comment]
Tip to download blockchain history before the fork height: run the node with `-bootstrap` and `-addnode=<some Bitcoin Core ip>`. It will begin to download the chain and stop at 491406. And then you can stop the client and restart without these two flags.

**Comment by jagottsicher** [comment]
but i want to prune anyway to 1GB or so. will that work?

**Comment by tankitty** [comment]
@h4x3rotab  that work ! Now syncing ...

**Comment by jagottsicher** [comment]
not for me :-/
First of all it can only connect on port 8338, so all Bitcoin nodes will refuse the connectiion anyway, or?
`
2017-11-13 03:52:46 connected to self at 127.0.0.1:43040, disconnecting
2017-11-13 03:52:47 connect() to 81.7.16.17:8338 failed after select(): Connection refused (111)
2017-11-13 03:52:47 connected to self at 37.XX.XX.23:33578, disconnecting
`
so I tried to stick to port 8333 on an external machine, which I also own.
`2017-11-13 03:57:14 receive version message: /Satoshi:0.15.0(needs-coffee)/: version 70015, blocks=494139, us=37.17.230.23:45368, peer=2
`
looks in the log like at least doing something, but now has 1 connection, but still zero downloads!!! 

Is there a conflict with running a bitcoin and a bitcoin gold node on the same machine?

**Comment by tankitty** [comment]
nodeip:8333

**Comment by tankitty** [comment]
because bitcoin core used 8333

**Comment by jagottsicher** [comment]
connection done (see above), but still not syncing!

**Comment by jagottsicher** [comment]
hell, now it is syncing. with 2 connections only, but blocks raising.

Question: will pruning work?

**Comment by tankitty** [comment]
I removed /root/.bitcoingold/* first and then start with

bgoldd -bootstrap -addnode=XXX:8333 -shrinkdebugfile -conf=/root/.bitcoingold/bitcoin.conf  -daemon

Replace XXX with bitcoincore full node ip

**Comment by jagottsicher** [comment]
I emptied .bitcoingold, and kept wallet and bitcoin.conf only.
in bitcoin.conf the nodes are added and pruning is turned on, but started without -boostrap.
that is not needed, because i do the pruning.

now stopped at block 126832, and diff 244112

**Comment by tankitty** [comment]
At first time must start with -bootstrap and stop at 491406

**Comment by jagottsicher** [comment]
okay. will try. can I put bootstrap in the bitcoin.conf?

**Comment by tankitty** [comment]
I put -bootstrap at run command parameter

**Comment by ghostshirt** [comment]
I have two bitcoin servers running in my LAN, one BCash and one BU (core chain). Interestingly, when I -addnode to BU IP, it does not download the chain but when I switch to BCash server IP it starts downloading.

**Comment by jagottsicher** [comment]
I tried several times now. the best resuts I get when going with the -bootstrap option like recommended from @tankitty. I add up to 15 node (or BTC node), but eventually the download always stopps!

Really really sucks! Anybody an idea?

**Comment by tankitty** [comment]
@jagottsicher i added only 1 bitcoin node ( from LAN ) 

run with this command .. now finished

 /root/bgold/bgoldd -bootstrap -addnode=xxxx:8333 -shrinkdebugfile -conf=/root/.bitcoingold/bitcoin.conf -daemon

**Comment by jagottsicher** [comment]
even after a restart, it does not continue to download the blockchain.

**Comment by jagottsicher** [comment]
I have no 2nd node in the LAN, only one on the same machine, but bgoldd does noch accept a bitcoin node with the same ip - assuming it shall connect with itself. :-1:

**Comment by Powie** [comment]
port 8338 or 8333 ...?

**Comment by tankitty** [comment]
@Powie 8338 for bitcoin gold , 8333 for bitcoin core 

Bootstrap sync block from bitcoin core node (8333)

**Comment by Thecreator1** [comment]
This pool.gold is a fraud.
I had build up some balance by mining and then it simply disappeared and went back to zero.
Mind you this was after the start of the mainnet in case you wondered if it was not lost testnet coins.

**Comment by jagottsicher** [comment]
This connection issue really really sucks.
I added all node from #172 and #178, but the client is not able to establish connections to download the first part of the blockchain from gold nodes. adding only btc nodes lead to a sync (finally), but evetually always fails at approx 50% of the blockchain. - bootstrap was o good idea, but only works in an intranet.

Does anyone outside of CHhina (!) have a valid and complete bgold blockchain?

**Comment by jagottsicher** [comment]
IT is definetly not possible for me to download more than 50% of the blockchain. also only from btc sources, bgold sources all refuse to send any bit - if they connect at all. the testnet worked okay, but the mainnet seems a desaster.

**Comment by srmo** [comment]
Interesting, added --bootstrap to the Windows link to bitcoin-gold-qt and it automagically connects to bitcoin core nodes and the download of the chain now shows expected downstream rates. (Sidenote: added the nodes to bitcoin.conf as posted in other issues)

**Comment by jagottsicher** [comment]
up to 50% the download works fine, then suddenly stops and does not continue. there  are always bitcoin core node connected, but you have to add them manually. with gold nodes I did not even download a byte, but sometimes it connects to 1 or 2, but only for a few seconds, then skips...

**Comment by 5dao** [comment]
why not provide a p2p seed to download history data about bitcoincore

**Comment by wizzfile** [comment]
how

**Comment by jagottsicher** [comment]
@srmo the code atomatically switches to core nodes after 50 failed tries to reach a gold node. 
I already added hundreds of both nodes to bitcoin.conf.

Anyway the doenload stopps again and again. 

I already asked in other posts: does anyone have a complete blockchain?

**Comment by virtualrobotix** [comment]
Hi ..
i don't yet finish to download ,but if you use the -bootstrap function can
connect the bitcoin full node so you are more fast to download old part of
blockchain.
I don't yet near october so when will be near i'll re switch and check the
sped with btg node.

**Comment by srg777** [comment]
I just started with -bootstrap options, seems much faster

**Comment by jagottsicher** [comment]
no idea, how often to repeat this: of course I already use -bootstrap, It just quits after 50%

`
2017-11-14 23:38:20 ERROR: invalid header received
2017-11-14 23:38:20 ProcessMessages(headers, 162003 bytes) FAILED peer=83
2017-11-14 23:38:21 ERROR: AcceptBlockHeader: Consensus::ContextualCheckBlockHeader: 000000000000000000e5438564434edaf41e63829a637521a96235adf4653e1b, bad-height, incorrect block height (code 16)
2017-11-14 23:38:21 ERROR: invalid header received
2017-11-14 23:38:21 ProcessMessages(headers, 162003 bytes) FAILED peer=8
2017-11-14 23:38:21 ERROR: AcceptBlockHeader: Consensus::ContextualCheckBlockHeader: 000000000000000000e5438564434edaf41e63829a637521a96235adf4653e1b, bad-height, incorrect block height (code 16)
2017-11-14 23:38:21 ERROR: invalid header received
2017-11-14 23:38:21 ProcessMessages(headers, 162003 bytes) FAILED peer=19
2017-11-14 23:38:22 ERROR: AcceptBlockHeader: Consensus::ContextualCheckBlockHeader: 000000000000000000e5438564434edaf41e63829a637521a96235adf4653e1b, bad-height, incorrect block height (code 16)
2017-11-14 23:38:22 ERROR: invalid header received
2017-11-14 23:38:22 ProcessMessages(headers, 162003 bytes) FAILED peer=15
2017-11-14 23:38:25 ERROR: AcceptBlockHeader: Consensus::ContextualCheckBlockHeader: 000000000000000000e5438564434edaf41e63829a637521a96235adf4653e1b, bad-height, incorrect block height (code 16)
2017-11-14 23:38:25 ERROR: invalid header received
2017-11-14 23:38:25 ProcessMessages(headers, 162003 bytes) FAILED peer=10
2017-11-14 23:38:48 connect() to 46.101.195.208:8338 failed after select(): Connection refused (111)
2017-11-14 23:39:49 connect() to 46.101.195.208:8338 failed after select(): Connection refused (111)
2017-11-14 23:40:31 receive version message: /Satoshi:0.12.1/: version 70012, blocks=494387, us=37.17.230.23:34530, peer=110
2017-11-14 23:40:50 connect() to 46.101.195.208:8338 failed after select(): Connection refused (111)
2017-11-14 23:40:52 ERROR: AcceptBlockHeader: Consensus::ContextualCheckBlockHeader: 000000000000000000e5438564434edaf41e63829a637521a96235adf4653e1b, bad-height, incorrect block height (code 16)
2017-11-14 23:40:52 ERROR: invalid header received
2017-11-14 23:40:52 ProcessMessages(headers, 162003 bytes) FAILED peer=6
2017-11-14 23:41:51 connect() to 46.101.195.208:8338 failed after select(): Connection refused (111)
`

and my logs are full of that connection refused and incorrect block height error!

**Comment by srg777** [comment]
I have been syncing more than 24 hours for now, and only 18.8% done 
progress is minor unfortunately

**Comment by jagottsicher** [comment]
Could be some Luck thing. I recompiled anyway and finally downloaded the whole Chian within 24 Hours.
first part I did with the -bootstrap otion to one of my btcoin full nodes and rest worded after a restart with -bootstrap.
good luck to everyone. For people with slow download it could be a good idea to add some fully snyced bitcon full nodes via -conf or cli.
Search [here](https://bitnodes.earn.com/nodes/leaderboard/) for a country near you and add some node with :8333. That should work.

**Comment by srmo** [comment]
@srg777 Fear not, took me 2+ days but it's finally up and running.

**Comment by StarbuckBG** [comment]
It is not only downloading. Your PC acts like full node and validates all the data.
Few important factors are determining the speed :
1. Network speed
2. CPU
3. Luck (to connect to enough nodes)

**Comment by Ayms** [comment]
And RAM, if you are trying to sync the full chain from the network on a standard pc you are probably wasting your time, most likely it will fail at a certain point of time or will take you 10 days, most of the work is to validate the data as stated above

So the best way is to torrent the full chainstate #192 (and not 191 @jagottsicher you should edit your post), not the pruning version, the full one, then to resync your wallet

**Comment by h4x3rotab** [comment]
`bootstrap.dat` file can be fund at the official download page.
