### ISSUE TITLE
Working Node Addresses

### ISSUE THREAD

**Issue by oliverw** [BTCGPU/BTCGPU#178]
Since I'm probably not the only one struggling with having its nodes sync I'd like to encourage everyone to post working BTG P2P nodes until the whole discovery works a bit more reliable.

**Comment by JokerCatz** [comment]
+1 & I need testnet too ... connection is 0 , I need peer list & explorer

**Comment by tankitty** [comment]
https://github.com/BTCGPU/BTCGPU/issues/176

**Comment by jagottsicher** [comment]
while trying to sync I mined some time at mine pool.gold - the so called offical pool, but whenever checking the addresses of my worker, the system cant find them, smells like scam spirit.

syncing stops over and over again.

**Comment by Gannicus1987** [comment]
pool.gold was apparantly syncing the wrong chain or something, i'm mining @ btgpool.pro now, they are on the correct blockchain and height!

**Comment by DarthJahus** [comment]
Someone published a list on the [Telegram group](https://t.me/BTCGoldChat), Changed it to `bitcoin.conf` format:

> [BTG-Nodes.txt](https://github.com/BTCGPU/BTCGPU/files/1466673/BTG-Nodes.txt)

It may help, at least until they hardcode some good nodes in the client.

(From [here](https://github.com/BTCGPU/BTCGPU/issues/172#issuecomment-343895001))

**Comment by BTCtrinkets** [comment]
Adding the BTG-Nodes.txt data to bitcoin.conf does nothing, still 0 peers.

**Comment by oliverw** [comment]
Yeah same here.

**Comment by ilia2s** [comment]
same issue

**Comment by w4tch3r7** [comment]
Same issue, I can't mine if I can't get the wallet to work.... modified the bitcoin.conf to add the hosts but still get nothing. (Sent 3kb/Recieved 0kb) 0 peers listed in the peers tab, for a brief moment 1 will pop up in the window then disappear.

**Comment by Gannicus1987** [comment]
Ive added the nodes and downloaded 10% of the blockchain in the last 4 hours or so

**Comment by h4x3rotab** [comment]
You can try this ATM: https://8n1.org/12322/67e0

Working on real fixes including the dnsseed and bringing up more full nodes

**Comment by DarthJahus** [comment]
People can use `btg.suprnova.cc` as the only node. Works really well. They know how to build a real pool, and they have a real infrastructure.

**Comment by fabioganga** [comment]
I am trying EVERY SINGLE node that has been published here... and I've been trying to sync for the past THREE DAYS. It's pretty much impossible to use this wallet and sync it successfully. I have tried the -bootstrap and -addnode=IP:8338 flags, I have added the nodes in bitcoin.conf, I have read all the issue topics! Nothing, it is just either awfully slow or it syncs for a little while and then it gets stuck to the point that I have to exit and launch it again. Come one guys... surely you can do better this! Get your acts together and release a WORKING WALLET, as this one surely cannot be called a working solution at all.

**Comment by evgenyundefined** [comment]
In yours trello i see make up full nodes in all continents... But what we see now? for fast sync need make too much actions... When precompiled daemon works out of box?

**Comment by virtualrobotix** [comment]
I try with -connect=x.x.x.x:8338 with -bootstrap and it work if you have
firewall off and bitcoin classic wallet open

Il 14 nov 2017 8:23 PM, "fabioganga" <notifications@github.com> ha scritto:

**Comment by evgenyundefined** [comment]
responsible owners must be care of clients and make accesable full nodes (include bitcoin blockchain if ours make btc fork...)

**Comment by DarthJahus** [comment]
Can someone who **can't sync** on Windows (x64) try this?

* Download [this build](https://mega.nz/#F!9MlUXRbS!s8XV9JUH07qAW8eKp0fxHg)
* Remove all from `%AppData%\BitcoinGold` except `wallet.dat` (unless you want to remove your wallet)
* Move `bitcoin.conf` file to `%AppData%\BitcoinGold`
* Run the wallet and go to Help > Debug window and see if the connections are working

**Comment by dexX7** [comment]
I recommend **not** to download any binaries ever. They are likely infected!

**Comment by h4x3rotab** [comment]
Living full node address list: status.bitcoingold.org

**Comment by kenorb** [comment]
Attaching config file with actual nodes:
[bitcoingold.conf.gz](https://github.com/user-attachments/files/29005074/bitcoingold.conf.gz)
I was able to sync node as of today.

**Comment by DarthJahus** [comment]
@kenorb, 9 years later?
