### ISSUE TITLE
This is a epic failure?

### ISSUE THREAD

**Issue by francois007** [BTCGPU/BTCGPU#183]
I have many pcs in my home. One of these was shut down the day before the fork.
Today I've been compiled and run your source! After running, I checked the default blockchain folder, I selected the folder that I used for Bitcoin Core.
Surprise! The blockchain is corrupted! Patience, synchronize everything and keep the old Bitcoin Core wallet (empty wallet before running this new chain).
All the addresses I used are changed ...
I had to add a bitcoin.conf with a list of nodes found on bitcointalk!

WE ARE SURE THAT IS A REAL FORK?
WHY THE CHAIN ISN'T CORRECT? IS THE SAME THAT WORKS ON 4 DEBIAN STABLE PCs!

IS A CHAINSPLIT OR IS A FORK!

![btg1](https://user-images.githubusercontent.com/11857471/32760979-24478138-c8f1-11e7-815b-6b9395038ce3.png)

![btg2](https://user-images.githubusercontent.com/11857471/32760990-30e91df2-c8f1-11e7-98cb-6765c75eae64.png)

**WHERE IS MY ADDRESS?**
![btg3](https://user-images.githubusercontent.com/11857471/32761001-3bf818ce-c8f1-11e7-9de9-82da4ef2d7e6.png)

**Comment by jagottsicher** [comment]
so with the new bitcoin gold client you can not access the addresses?
and your "snapshot" of the blockchain is not accepted by the gold client?
would be nice to get some explaination from the dev team

**Comment by h4x3rotab** [comment]
Block header format has been changed. So loading the datadir form Bitcoin doesn't really work. You should download the blockchain from BTG nodes.

**Comment by benma** [comment]
Block header only changed from the point it forked. Syncing using the existing data set should have been considered.

**Comment by h4x3rotab** [comment]
@benma I don't see the value of doing that. It's not easy to have blockchain data in two format stored in the disk. But if we write a tool to convert from one to another, BTG client still need to reindex, which takes most of the time. I'd rather connect the BTG client to Bitcoin Core client and sync via local network.

**Comment by benma** [comment]
The blocks before the fork are the same, so there is nothing to rebuild or reindex. The same data could have been used, saving tons of bandwidth and time for everyone.

**Comment by h4x3rotab** [comment]
Theoretically it's true. It should accept the block file copied from Bitcoin Core. There will be two kinds of block files and the client distinguishes them. I'm not sure if the indexing will still work if we do so.
