### ISSUE TITLE
recommand for init sync ...

### ISSUE THREAD

**Issue by JokerCatz** [BTCGPU/BTCGPU#184]
first sorry my poor english...

I think new full node is sync from block 0 , but it need 80GB+ network & hdd space , will be very slowly & it may not DDoS , just too many full node wait to sync & they can't sync old blocks from bitcoin core ( bitcoin cash is no problem like this , it can be sync from bitcoin core )

so why not then me download block datas like from MEGA ( or another service ) & use config 

    prune=551

? (doc in https://en.bitcoin.it/wiki/Running_Bitcoin)

so I can download it and sync will be fast to latest block , if I don't need trace full chain & I can sign transaction from my core node? (copy paste the pkey / payload to BTG full node to sign[rawtransaction] & send it)

**Comment by h4x3rotab** [comment]
Great suggestion. We are also preparing for bootstrap torrent files to alleviate the network issue.

**Comment by jagottsicher** [comment]
I hope soon, because I already used the but the only way of reseaonable shorten the download and validatin time is a bootstrap with the actual blockchain
Please including som PGP-HASHes to validate the origin!

**Comment by Esonics** [comment]
Now I'm doing an archive of 150GB that would reduce

**Comment by Esonics** [comment]
Hello!
Created a torrent Full Blockchain Bitcoin Gold - 500078 (Block)

https://bitcointalk.org/index.php?topic=2171754.msg24610604#msg24610604

**Comment by h4x3rotab** [comment]
Better to use the official version :)

Download page: https://bitcoingold.org/downloads/
Magnet link:
```
magnet:?xt=urn:btih:ef763678e152bb91461fe9ae45e6f1faea422c79&dn=bootstrap&tr=udp%3A%2F%2F151.80.120.113%3A2710%2Fannounce&tr=http%3A%2F%2F163.172.81.35%3A1337%2Fannounce&tr=http%3A%2F%2F51.15.4.13%3A1337%2Fannounce&tr=udp%3A%2F%2F51.15.4.13%3A1337%2Fannounce
```
