### ISSUE TITLE
Minimum requirments for Bitcoin Gold Server FULL NODE  ?

### ISSUE THREAD

**Issue by miranos** [BTCGPU/BTCGPU#185]
Hi,

I want to buy a VPS in order to install Bitcoing Gold FULL NODE, what requirments i need please ?

Thank's.

**Comment by ilia2s** [comment]
1) 1Gbit+ Internet channel without traffic limits,
2) External IP with open 8338 port,
3) 250GB or more GB Disk storage
4) 4 or more GB RAM
5) i3 or higer (not shared recommended) CPU

**Comment by h4x3rotab** [comment]
@ilia2s Good answer :)
@miranos If your question is solved, please close the issue.

**Comment by miranos** [comment]
How much time it will take to download the blockchain and synchronize please ?

**Comment by ilia2s** [comment]
It depends on your hardware, network speed and load. From several hours to some days (in practice).

**Comment by miranos** [comment]
Thank you all for your help, appreciated.
