### ISSUE TITLE
(Easy question) Is this how Bitcoin Gold's SigHash FORKID works?

### ISSUE THREAD

**Issue by DesWurstes** [BTCGPU/BTCGPU#186]
https://github.com/DesWurstes/bchutil/commit/4ac2b0ab88113fce0c52ba2bc187ad24da1096b8

Is there another difference between Bgold's and Bitcoin Cash's replay protection?

(20,024 = 79 << 8)

**Comment by h4x3rotab** [comment]
Yes, exactly. Also be aware that Bcash doesn't have SegWit tx but BTG has.

**Comment by DesWurstes** [comment]
Okay, thanks.
