### ISSUE TITLE
Instructions to start a node

### ISSUE THREAD

**Issue by miranos** [BTCGPU/BTCGPU#188]
Hi,

Any fast instructions on how to launch a node ?!

I downloaded the files for linux, extracted them and then ?

Looking to configure it and synchronize it.

bitcoin.conf example please.

Thank you.

**Comment by virtualrobotix** [comment]
If you have a Bitcoin full node on your pc
you can use on your BTG node :
 bitcoin-qt -bootstrap -connect=x.x.x.x:8333
so you can align blockchain directly from your btc full node.

**Comment by miranos** [comment]
I dont sorry.

I want use BGOLDD only since i will do it on an online VPS throue SSH.

Thank's.

**Comment by h4x3rotab** [comment]
There's a contributed wiki page for running a full node. It's write for Windows but Linux should be similar.
