### ISSUE TITLE
btcgpu bootstrap

### ISSUE THREAD

**Issue by jmtibbetts** [BTCGPU/BTCGPU#191]
I have created a Full bitcoingold Bootstrap up until 5:07pm EST.

If anyone knows where I should post or upload to please let me know, I am in the process of uploading it to my onedrive and am willing to host it there, but I think making a torrent would be better.  The bootstrap was made from -bootstrap from bitcoin core up until the fork, then synced the rest of the bitcoingold mainnet.

It took me 2 days to -bootstrap from a LAN Bitcoin node, so I think this would help.

Maybe the Dev can use this to include in the downloads ?

Onedrive Download for the torrent file.
https://1drv.ms/u/s!AtI7KNIy08cgguFUQ30vjPWZ5iZH8Q

Torrent is my only option atm, So until another solution or something better occurs, i'll seed it. 

thanks, Please re-seed after downloading and share this link with whoever you need, the onedrive link above is read only so the bootstrap cannot be replaced.

**Comment by shakilmia** [comment]
bootstrap

**Comment by jagottsicher** [comment]
I would be extremly thankful to be able to download it, but not as a torrent or at least only in worst case!
Please let me know, when it is ready!

**Comment by jmtibbetts** [comment]
I cannot upload the 153GB of the bootstrap to onedrive due to upload limit sizes. I am creating a torrent file that i'm not sharing on a site like thepiratebay I will post the torrent and utilize my entire 1gb/s connection to host the file.  I'm searching for a alternative place to upload it.

**Comment by jmtibbetts** [comment]
torrent link provided in First comment, i'll seed at the highest possible bandwidth for as long as I can

**Comment by arubinofaux** [comment]
thank you @jmtibbetts ill seed for a few days

**Comment by srg777** [comment]
thank you @jmtibbetts, I start downloading
will seed for few days

btw, what I should do with this .dat  file? :)

**Comment by JokerCatz** [comment]
just copy to like `~/.bitcoin` path & it will be import it

but 15X GB is toooo large , like my VM only 40GB , so I need download and add `-prune=551` , I think it will be less 2GB .... but it will not be full chain , will delete old blocks & try fit to 551 MB

**Comment by jmtibbetts** [comment]
yes any of the 30 - 40 people who have downloaded please comment i'm using like 20-50mb/s of upload bandwidth and it would be nice to know if the bootstrap is helping anyone.

**Comment by Ayms** [comment]
Take care, this one is complete shit, don't download it, go to #192

**Comment by srg777** [comment]
@jmtibbetts I've started early in the morning, maybe 9-10 hours ago. 20% done
still online and downloading the file

**Comment by Ayms** [comment]
Go away from this one, the magnet link is magnet:?xt=urn:btih:B7E4EBFE79773FCEEBB4BB83E74C09FA05F57310, if you see it elsewhere, don't use it

**Comment by h4x3rotab** [comment]
Duplicated: #192 #184
