### ISSUE TITLE
Created a torrent Full Blockchain Bitcoin Gold - 500078 (Block) and prune 600 - 500145 (Block)

### ISSUE THREAD

**Issue by Esonics** [BTCGPU/BTCGPU#192]
Hello!
Update Post
Created a torrent Full Blockchain Bitcoin Gold - 500078 (Block)
Created a torrent Blockchain Bitcoin Gold (prune=600) - 500145 (Block)
https://bitcointalk.org/index.php?topic=2171754.msg24610604#msg24610604

Blockchain Bitcoin Gold (prune=600) - 500145 (Block)
magnet:?xt=urn:btih:04D10B030C13E54372161C1AD5F674F0FCAF2365

Full Blockchain Bitcoin Gold - 500078 (Block)
magnet:?xt=urn:btih:47BFB9826B588354917CB6BDC0CAF00D47A1D4D4

If this helped you can send not much BTG - to buy a new HDD :)
Gf16JfFSJnPcLYNqJzCUq6RkSqUDFHGSfs

**Comment by miranos** [comment]
What is the size on Gegabyte ?

I am actually at 28 G is it good ?

**Comment by Esonics** [comment]
Full ~150Gb - Zip ~118Gb
prune 600 ~3.5Gb - ZIp ~2.9Gb

Of course it's legal ...
This facilitates synchronization

**Comment by miranos** [comment]
How to install it please ?

I will download thebitcoin gold blockchain, replace the existing one with new one, and then what command should i launch ?

Thank you for your helpful contribution.

**Comment by Esonics** [comment]
It's already Bitcoin Gold
unzip folder "blocks" and "chainstate" in folder BitcoiGold (Windows) or .bitcoingold (Linux)

**Comment by miranos** [comment]
Tried to downlaod but stay 0% since no one shared it yet.

**Comment by Esonics** [comment]
I'm giving away. Must wait.

**Comment by miranos** [comment]
Ok thank you sir :)

Now it's working.

**Comment by TechniumUnlimited** [comment]
remember the danger in this

**Comment by miranos** [comment]
@TechniumUnlimited What is it please ?

**Comment by Esonics** [comment]
Attention
Who downloads the cut-down version (prune=600) in the label write prune more 600 - 700 or 800 otherwise there will be an error
Example:
"C:\Program Files\BitcoinGold\bitcoin-qt.exe" -prune=800

**Comment by Ayms** [comment]
@Esonics Why don't you just provide the magnet link also? Same for @jmtibbetts #191

**Comment by Esonics** [comment]
OK!
Blockchain Bitcoin Gold (prune=600) - 500145 (Block)
magnet:?xt=urn:btih:04D10B030C13E54372161C1AD5F674F0FCAF2365

Full Blockchain Bitcoin Gold - 500078 (Block)
magnet:?xt=urn:btih:47BFB9826B588354917CB6BDC0CAF00D47A1D4D4

**Comment by Ayms** [comment]
Great, more simple than downloading the torrent file, working well apparently, hope people will seed (and we can trust your file...)

**Comment by Esonics** [comment]
I hope someone downloads the first one will leave feedback

**Comment by Ayms** [comment]
Was joking, #184 , but we never know, some people are seeding already so if it was not correct we would probably know it, would be good anyway that this is stamped by the dev team (and not sure that the pruning version is a good idea for now), good work, some people look to be afraid of torrents, for maybe some copyright issues that have nothing to do here, this is of course the fastest/most efficient way to sync

**Comment by DLee-AU** [comment]
I am half way there on the torrent download the bootstrap option is just boggin down

**Comment by mardarfar** [comment]
Was unable to import my private keys with the prune blockchain

17:41:59 Rescan is disabled in pruned mode (code -4)
That was a waste of time...

**Comment by Esonics** [comment]
What for Rescan ?

Who downloads the cut-down version (prune=600) in the label write "prune" more 600 - 700 or 800 otherwise there will be an error
Example:
"C:\Program Files\BitcoinGold\bitcoin-qt.exe" -prune=800

**Comment by Mikadily** [comment]
You can't import keys on pruned blockchain, it's useless

**Comment by JokerCatz** [comment]
pruned can't be txindex / reindex or something ... old block is pruned , so nodata to scan

the (prune=600) version look like okay , now 500299 blocks & 14 connections

**Comment by mardarfar** [comment]
Rescan with the full blockchain takes hours after importing private key

**Comment by Ayms** [comment]
Hours, not days, that's better, no?

**Comment by JokerCatz** [comment]
you can use explorer => get hex(at wallet & unused vout) => createrawtransaction , sign & send , without rescan full chain , but the explorer is not stable now , they no old block datas (before chain split) ...

**Comment by h4x3rotab** [comment]
Duplicated: #184 #191 

Better to use the official bootstrap.dat. The current version has the block from genesis to 500060.

Download page: https://bitcoingold.org/downloads/
Magnet link:
```
magnet:?xt=urn:btih:ef763678e152bb91461fe9ae45e6f1faea422c79&dn=bootstrap&tr=udp%3A%2F%2F151.80.120.113%3A2710%2Fannounce&tr=http%3A%2F%2F163.172.81.35%3A1337%2Fannounce&tr=http%3A%2F%2F51.15.4.13%3A1337%2Fannounce&tr=udp%3A%2F%2F51.15.4.13%3A1337%2Fannounce
```

**Comment by marousi** [comment]
I downloaded  https://bitcoingold.org/downloads/, question is what do I do with it? Where to put it?

**Comment by marousi** [comment]
where to put the bootstrap.torrent file?

**Comment by Ayms** [comment]
Use your bittorrent client (like utorrent), then "File/open torrent by url" or something like this and copy the magnet link

**Comment by marousi** [comment]
ok, thx. But once I have done that how do I get bitcoin-qt to read the file?

**Comment by h4x3rotab** [comment]
The torrent itself contains a readme file with instructions.

**Comment by marousi** [comment]
the readme file is 0 bytes

**Comment by marousi** [comment]
ah, perhaps because the torrent reader has not finished.

**Comment by marousi** [comment]
ok, the torrent reader has finished and followed instructions in the readme, yet it does not load bootstrap.dat. What todo?

**Comment by marousi** [comment]
ok, the torrent reader has finished and followed instructions in the readme, yet it does not load bootstrap.dat. What todo?

    On Wednesday, November 22, 2017, 12:09:54 PM GMT+2, h4x3rotab <notifications@github.com> wrote:  
 
 
The torrent itself contains a readme file with instructions.

**Comment by marousi** [comment]
does not matter, downloading the entire blockchain, 7 hours remaining.
