### ISSUE TITLE
How to validate bitcoin gold mainnet address by code

### ISSUE THREAD

**Issue by Airead** [BTCGPU/BTCGPU#193]
I want to validate bitcoin gold mainnet address with code, how to do this?

It's ok to use `bgold-cli validateaddress xxxx`, but how to use code to do this?

**Comment by evadogstar** [comment]
Forged about bitcoin gold. It's SCAM and shitcoin made to HYIP real bitcoins from users.

**Comment by h4x3rotab** [comment]
It depends on how you write the tool. Basically you can reuse any Bitcoin library to validate the address. The only difference is the address version has been changed.

You can check this nice article: https://en.bitcoin.it/wiki/Technical_background_of_version_1_Bitcoin_addresses

**Comment by Airead** [comment]
Thanks!
