### ISSUE TITLE
Lost all BTC in BTG blockchain - pls check this !

### ISSUE THREAD

**Issue by bol-van** [BTCGPU/BTCGPU#194]
I have privkey from bitcoin core and imported it to BTG core. It was expected to have ~1.34 BTG there.  I see that all coins were moved out on 22-sep  and balance is zero.

http://ipic.su/img/img7/fs/btgshit.1510748018.jpg

Gf49enUukW48KQBqLSBJDVDsxx1Smvnxt6  -  its the address derived from BTC privkey
22-sep I payed 0.022 BTC from 1NDEEf9xmeSqEvtYQVXBnisz3nDbm7abmv which translates to Gf49enUukW48KQBqLSBJDVDsxx1Smvnxt6 in BTG chain

https://btgexp.com/tx/bf8f0955ebd3facea300a89bfce1038201188e6d4eb15acb000c22a35f910013
https://blockchain.info/tx/bf8f0955ebd3facea300a89bfce1038201188e6d4eb15acb000c22a35f910013

After that spend In BTC chain I still owned 1.35 BTC , then sent 0.009 BTC 23-sep and last transaction was on 14-nov to clear that address before importing privkey to BTG.

So, for now, I have ZERO on BTG chain, and thats not what was expected

**Comment by StarbuckBG** [comment]
The transaction happened long before the split of the chain. The explorer shows the transactions translated to BTG addresses. 
If the transaction was made after block 491407 you would have your coins.

**Comment by bol-van** [comment]
You dont get it.
I had 1.34 BTC at the moment of the split.
I didnt sent 1.35 BTC to anywhere.   Its how change return translated in BTG chain

**Comment by StarbuckBG** [comment]
According to both the explorers this money were sent to another address on September 22.

**Comment by bol-van** [comment]
Honestly I dont fully undestand in's and out's in blockchain output. I just know that 0.02 BTC was sent to 1FgenQ7UZxqGDbCRGoS7EkS6AFhi6X8VAh. Its what I did - sent 0.02 BTC there in bitcoin core. After that I had 1.35 BTC, and its exactly amount of second output. From simple logic I suppose its change and my BTC wallet correctly displayed balance as 1.35 BTC. I never sent it out

**Comment by bol-van** [comment]
Here are all transactions I made since 22-sep.

https://blockexplorer.com/tx/bf8f0955ebd3facea300a89bfce1038201188e6d4eb15acb000c22a35f910013
https://blockexplorer.com/tx/04fa1527591bbd2ee4770377beceb9d42c84e096780f0955e25e4076383f0790
https://blockexplorer.com/tx/b32b6249037bc2bc059369209f1c4a7422f9775b996bb22f18af033a6995231e

1) 22-SEP : change 1.35 BTC transferred to 1G5RmzcwurewFLFjWtreZ3UD13KDsgKtGe
2) 23-SEP address from 1 was used as source and change 1.34 BTC transferred to  1GsXEvtKe113b5YqwK1t3gzwi3ibbGVguu
3) 14-NOV address from 2 was used as source and everything was transferred to new address 1MCh6s9kYNWeKtLDYciWrqUBcnNaPF4GTm

Can you explain how core wallet works and how to get privkey from 1GsXEvtKe113b5YqwK1t3gzwi3ibbGVguu ?

**Comment by TheComputerGenie** [comment]
Not that the bgold explorer works correctly (in terms of a chain fork) or even shows those coins, but

At block 486,593, they were in the possession of 1GsXEvtKe113b5YqwK1t3gzwi3ibbGVguu 
the snapshot happened at block 491,407
At block 494,344, they were in the possession of 1MCh6s9kYNWeKtLDYciWrqUBcnNaPF4GTm 

The bgold should reside with the private key for 1GsXEvtKe113b5YqwK1t3gzwi3ibbGVguu

**Comment by bol-van** [comment]
Yes I also think so . But i dont know about that feature of bitcoin core. It uses temporary addresses I've never created for each transfer, and they are not displayed in "receiving addresses". But still it can transfer from them, and it means it silently stores privkey somewhere in the wallet or use some derivation algorithm

**Comment by bol-van** [comment]
I was able to dump privkey from 1GsXEvtKe113b5YqwK1t3gzwi3ibbGVguu in BTC core wallet.
It works. But what is that feature, how its called and is it possible to disable it ?
I only had backups of pkeys from addresses I thought I have money on but reality suggest I had only one actual copy of wallet.dat and if it was destroyed all my backups are nothing
Holy shit

**Comment by aprx4** [comment]
Many wallet softwares including Bitcoin Core send remaining of fund (change) to another address belong to your wallet, to improve your privacy and security.

Bitcoin Core use HD wallet, meaning you only need to backup wallet.dat once. So the private keys of all the address, including change address, is automatically backed up to wallet.dat.

**Comment by bol-van** [comment]
Yeah, it has all previously used key pairs. But what about new ones ?
Does it pre-create tons of keypairs and uses them when needed or creates new one after each send ?
If so then its not enough to backup once

**Comment by aprx4** [comment]
For illustration, you can think about HD wallet as some sort of 'master private key', from which we can generate unlimited number of address/privkey. This  mean you only need to back up wallet.dat once without worrying about newly generated addresses. Those new address/privkey can be derived from 'master private key'.

**Comment by bol-van** [comment]
Thanks. If you have BTC->BTG transfer guide somewhere this information should essentially be there

**Comment by bol-van** [comment]
I look to my bitcoin core interface. In status bard there's crossed out HD icon saying "HD key generation" is disabled. Could it mean there's no deterministic key generation and wallet uses limited amount of pregenerated keys and generate new ones at demand ?

**Comment by JokerCatz** [comment]
the BTC => BTG need regenerate public key from private key , and rescan full chain , get the txid & create rawtransaction will be okay ... (guess)

**Comment by jagottsicher** [comment]
is this related to #183?

**Comment by 008** [comment]
+1
lost all BTGs
tx was long after the split of the chain

**Comment by bol-van** [comment]
Not related.  Its about "feature" I didnt know about. And suppose many other ppl dont know. So its good to have a guide for them

**Comment by StarbuckBG** [comment]
We need more information about the TXID and also which sites have you used. You may have been scammed.

**Comment by bol-van** [comment]
Everything is resolved, if you read the thread you will find the reason

**Comment by h4x3rotab** [comment]
Yeah. We need a complete tutorial.
