### ISSUE TITLE
electrum -> btg core 

### ISSUE THREAD

**Issue by scgbckbone** [BTCGPU/BTCGPU#195]
Can I import electrum private key or sed to bcg core wallet ?

**Comment by francois007** [comment]
Hello,
From electrum you can import ONLY private key into BTG Core Wallet!

**Comment by scgbckbone** [comment]
Can you, please, describe how to do it. I only tried to delete my BCG wallet.dat and moved my default_wallet(renamed to wallet.dat) from electrum to bitcoingold directory. However that does not work. 

error: wallet.dat corrupt. salvage failed

**Comment by francois007** [comment]
You can't use electrum wallet, isn't a .dat file, it is a .txt
Extract private key from Electrum and put this in BTG wallet (using console)

**Comment by scgbckbone** [comment]
I do not see any option to import my extracted private key:
not in bgold-cli, not in bgoldd, not in bitcoin-qt, neither in console when I run 'bitcoin-qt --disablewallet'

where should I find it.?

I ran Ubuntu 16.04

**Comment by scgbckbone** [comment]
I don't have any help option there. Only 4 tabs in top form (Overview, Send, Receive, Transactions). No help at all. Not even console. I can only get to console if I use --disablewallet option. Bitcoin Gold Version v0.15.0.1-db7b378

**Comment by francois007** [comment]
@scgbckbone 
Compile and run full version of BTG wallet.
Otherwise fuck you and your private key.

**Comment by h4x3rotab** [comment]
It's inside the "help" menu, not a tab.

**Comment by scgbckbone** [comment]
just a pointer to where I get and also where I'm stuck:

https://bitcoin.stackexchange.com/questions/62951/which-private-key-to-export-from-electrum

**Comment by DChiuch** [comment]
As far as I can tell, there's no way to import a 2FA wallet from Electrum (which is essentially a 2of3 multisig wallet) into the BTG wallet.

**Comment by kxjhlele** [comment]
@DChiuch  me too, 2fa, not to btg wallet

**Comment by h4x3rotab** [comment]
Duplicated #238
