### ISSUE TITLE
Bitcoin Gold Web Wallet (gWallet)

### ISSUE THREAD

**Issue by gold-wallet** [BTCGPU/BTCGPU#196]
Hi,

We just launched Bitcoin Gold Web Wallet.

We are on beta test, if you have any suggestion or feedback, you are welcome.

Link from here: https://gwallet.info

We offer too an API Service, you can check it from here:
https://gwallet.info/api

Thank you.

**Comment by StarbuckBG** [comment]
As it is online wallet we need the source code.

**Comment by LeaTex** [comment]
total scam.

**Comment by miranos** [comment]
Will give it a try ...

**Comment by gold-wallet** [comment]
@StarbuckBG  Why is it required to give you the source code ? we can show you everything from Team Viewer if you want.

@LeaTex Please give us why is it a scam ?

We just opened the registrations, you can start testing now.

**Comment by LeaTex** [comment]
there is no info abou you in the web. where are you? who are you? why you doesn't exists before today and participate in the project from the beginning?
what's the real name of the company behind this? who's the owner? where's the contact information? etc. etc. etc.

**Comment by gold-wallet** [comment]
We are on Beta test for now, we just finished the project.

As soon as everything is up, we will create presentation pages, contact infos etc.

**Comment by LeaTex** [comment]
so, you want us to be your beta testers, for free.
you say "if you have any suggestion or feedback". where can a leave the feedback? you have no mail or cantact form.
my first suggestion is this: put your information on the web, if you wanna look serious.

**Comment by gold-wallet** [comment]
@LeaTex Appreciated feedback, will take a note.

**Comment by LeaTex** [comment]
one shot, one kill...

first step: registration. result? incorrect activation link.

:man_facepalming: 

![btgwallet](https://user-images.githubusercontent.com/6115573/32873512-3a7e63b0-ca6b-11e7-9ded-f4258d67e42f.png)

**Comment by gold-wallet** [comment]
@LeaTex Problem solved, many thank's.

--
**Note:** We offer too an API Service, you can check it from here:
https://gwallet.info/api

**Comment by LeaTex** [comment]
Delete account option is not working.
After confirm deletion, it redirect to https://gwallet.info/privatekeys and shows error 500

Then I login again, and nothing is working.

![btgwallet2](https://user-images.githubusercontent.com/6115573/32873750-896c3ea6-ca6c-11e7-9ea6-9205db2b6a49.png)

**Comment by gold-wallet** [comment]
The account is deleted successfully, you have to delete browser cache and problem will disappear.

Anyway will check this again asap.

Thank you another time, your help is appreciated.

**Comment by miranos** [comment]
I tested it and works great ... can you add a way to import bitcoin addresses private keys in order to to get our BTG please ? Thank you and good luck for this awesome work.

**Comment by Bourne-ID** [comment]
Heads up that the WHOIS lookup has guard protection enabled so it's impossible to determine who owns the site and therefore the reputation. That's a huge no-no for me.

**Comment by gold-wallet** [comment]
@miranos We planed to do it during this week.

@LeaTex When you delete account cache will be deleted automaticallt and you got redirected to home page.

Many updates done ! Thank you all for your suggestions and feedback.

**Comment by benkloester** [comment]
This is a scam

**Comment by evadogstar** [comment]
BTG GOLD total and full scam. It's only part of scam
