### ISSUE TITLE
Node list

### ISSUE THREAD

**Issue by francois007** [BTCGPU/BTCGPU#197]
Hello devs,
Can you provide a complete full node list?
Can you post it on your official twitter/fb/website channel?
Sync process is very slow.

Thank you so much,
François.

**Comment by Mikadily** [comment]
https://github.com/BTCGPU/BTCGPU/issues/172 worked for me

**Comment by h4x3rotab** [comment]
DNSSeed should working. But you can also have a full node list from here:
https://status.bitcoingold.org

**Comment by wilsonmeier** [comment]
@francois007 i think your question has been answered. Please close this issue. Thank you.
