### ISSUE TITLE
I need confirm current main chain ...

### ISSUE THREAD

**Issue by JokerCatz** [BTCGPU/BTCGPU#198]
it look like some pools is spilt main chain (if sync wrong chain , sync will be stop |||) , so I need confirm my main chain block hash is current (without explorer...)

the main chain last block is

    height : 500277
    hash : 00000000220d884d9b62877b812b39ea54a58c32bed3c25f090634b1e8c3d517

and the testnet chain last block is

    height : 1210319
    hash : 00000000f6cea403537818b5297844139ed25da46dfbce220a96e0ba1a3b0ab7

it is current ? and this will help somebody can be confirm it too ?

**Comment by TechniumUnlimited** [comment]
no?

**Comment by h4x3rotab** [comment]
Check explorers:
http://btgexp.com
http://btgblocks.com

**Comment by JokerCatz** [comment]
okay , great , I need explorer and my main chain is okay , many thanx
