### ISSUE TITLE
Which PoW algorithm does the project utilize?

### ISSUE THREAD

**Issue by oliverw** [BTCGPU/BTCGPU#20]
I'm considering to add support for BTG to our pool but - correct me if I'm wrong here - that the PoW algorithm to be used is not set in stone yet. I've seen this [PR](https://github.com/BTCGPU/BTCGPU/pull/15) point to Equihash. What's the current situation here?

**Comment by h4x3rotab** [comment]
The PoW is changed to Equihash, same as Zcash. And I will try my best to be compatible with Zcash miner.

**Comment by oliverw** [comment]
@h4x3rotab Thanks for the update. I've sent you an email by the way. Please check your spam folder 😄
