### ISSUE TITLE
My BTG Wallet - Warning!!

### ISSUE THREAD

**Issue by LeaTex** [BTCGPU/BTCGPU#200]
From https://bitcointalk.org/index.php?topic=2393967.20

> Another stupid victim here, my whole Jaxx wallet was emptied (it was a lot..not only BTC) about 1 day after I used http://mybtgwallet.com.
> I can give all the details if it's of any use.
>Because it was referenced on the official http://bitcoingold.org/ site, I assumed it was safe and checked by the devs.
> They now removed the link from their site and also at the bottom of their page it now says they are not responsible for third parties, bla, bla.
> At http://mybtgwallet.com it now states 'Access to the site direct from your browser, dont search in google or access from any other website. It’s reported that some hackers are disguising the real wallet. We are investigating the problem.'
> Also the github is updated.
> What to do now?? 

@John-Dass maybe you can explain something.

**Comment by casaroto** [comment]
They don't even care to put an alert on the main btg site. And just post a "take care" with scams without point out about http://mybtgwallet.com, which were previously officially on their website.

**Comment by Technophant** [comment]
I used it too. Seemed safe, but now there's no gold in the address I had it in: 16Cc2Hm4LWPwPU8ZYN1G4sTB4rJkmsvCB3    I would love to think I'm importing it wrong into Coinami.  It's only $5 worth, so that's why I went ahead and tried it.  Disappointing.

**Comment by JokerCatz** [comment]
don't use private key or seed to public area ... you can wait the BTG all internet env is stable ...

**Comment by Technophant** [comment]
That was the public BTC address that had BTG according to the official website. All of the transactions are mine and I lost no btc. It converts to GP3XSR61KN1ETwRrUJfNVdo4z26bpBZXG which isn't on the block explorer so maybe it's still there?

**Comment by Technophant** [comment]
It's disturbing, truly. It's alledged that JohnDass's wallet was included on the official site, and it was promoted using twitter.  The two transactions that moved away my btc along with many other inputs resulted in an outputs that are multiples of 5 (5 btg and 20 btg). How or why was this done? Do common round numbers disguise the transfers further?

**Comment by LeaTex** [comment]
@JokerCatz I don't understand you.
My BTC address is 16FKbQwKVwCYCDNEG9ZMeye5e7dJRz3evT with 2,649 BTC
https://blockchain.info/address/16FKbQwKVwCYCDNEG9ZMeye5e7dJRz3evT

I convert it to BTG address and got GP6F1YGGUnoqGgfXC6DU5jyyZHR9TSfoWm but explorer shows me:
"Error! : Search found no results. GP6F1YGGUnoqGgfXC6DU5jyyZHR9TSfoWm"

The same with other 3 addresses.

**Comment by JokerCatz** [comment]
@LeaTex 
I think full chain mean is 0 to last blocks right?

http://btgexp.com/blocks
last page now at 318 , it start from block height : 491408 , so it only 491408 to last blocks ...

http://btgblocks.com/
the same ... not 0 to last blocks , and bitcoin need to trace all unspent (unused vout) and sum = your balance , not like ETH has a global balance pool can be search , so~

but you can use bitcoin explorer , pick your unspents (txid / index / hash) and createrawtransaction / sign from bgold , and broadcast it , I think it will be okay (if your unspent from block height <= 491407)

**Comment by LeaTex** [comment]
Ah, ok.

Everything is complicated with this coin. Nothing for common people.

**Comment by evadogstar** [comment]
@LeaTex This shitcoin is scam. Forget about it. They stole my mined BTG from the first day :) They will stole all what they can.

**Comment by Ayms** [comment]
Complicated, indeed, for common people indeed too, then please check:

https://github.com/BTCGPU/BTCGPU/issues/226#issuecomment-346672481

and https://github.com/Ayms/bitcoin-transactions

If it's not clear, please let me know

**Comment by evadogstar** [comment]
@Ayms you came too late, everything is already stolen.

**Comment by Ayms** [comment]
@evadogstar you edited your post to add "your scam", this is a free (and stupid) comment

Read again, this module is not for bitcoin gold only, how long do you think people will run x bitcoin y sw even if they are pruning to have their wallets synced? 

And if everything is already stolen people are still trying to sync
