### ISSUE TITLE
Still 0 connections and not syncing 

### ISSUE THREAD

**Issue by khelle** [BTCGPU/BTCGPU#201]
So, since the mainnet has "started" I was running the BTG node. Up till today I have still 0 connections and no blockchain at all. What's more I don't see any new reeleases addressing this issue or work being done on that part. Is the connection problem going to be fixed? Why the fork was done so much time ago, while it seems the BTG team was not prepared at all for release back then and still isn't?

Regarding the download links to torrents being posted on this github as the "solution". I don't find it safe to donwload such kind of data through torrent from no-one knows who. What I want is the full-node to be able to sync from block 0 to the newest without any additional help. It might be slow, but I has to work.

What is the official stance on this?

**Comment by TheComputerGenie** [comment]
>What I want is the full-node to be able to sync from block 0 to the newest without any additional help
Then bgold is not the coin for you.
