### ISSUE TITLE
after import privkey rescan stuck at 1%

### ISSUE THREAD

**Issue by srg777** [BTCGPU/BTCGPU#202]
I 've downloaded  blockchain and have imported private key in debug console.
rescaing window appeared and ticker at 1% 
situation the same for few hours

### What version of bitcoin-core are you using?
latest - downloaded from git hhub

### Machine specs:
- OS: Debian linux
- CPU: Core2DUO
- RAM: 1,5GB
- Disk size: 160Gb + external (where is blockchaine is placed)
- Disk Type (HD/SDD): HDD

**Comment by srg777** [comment]
i've restarted bitcoin-qt, and now importpriv doesnt work at all

**Comment by srg777** [comment]
does anybody have such experience?

**Comment by TheComputerGenie** [comment]
https://github.com/BTCGPU/BTCGPU/issues/204

**Comment by srg777** [comment]
update

after 10 hours rescaning - it is already 48% percents done
so, I think the very first percent is too difficult to pass
