### ISSUE TITLE
Stratum poolserver includes Hidden fee - Warning!!

### ISSUE THREAD

**Issue by LeaTex** [BTCGPU/BTCGPU#203]
What about this @StarbuckBG ?
> All pools based on this open source software are mining hidden fee. 

https://github.com/StarbuckBG/node-stratum-pool/pull/1

**Comment by StarbuckBG** [comment]
Already merged the PR. 
Thanks.

**Comment by LeaTex** [comment]
Why this exists at first time?

**Comment by TheComputerGenie** [comment]
Already done to death:
https://github.com/BTCGPU/BTCGPU/issues/180

**Comment by StarbuckBG** [comment]
Fees are returned to the pools you can check the TXiDs for the hardcoded address.
