### ISSUE TITLE
Another Bitcoin Gold wallet scam

### ISSUE THREAD

**Issue by emre9712** [BTCGPU/BTCGPU#206]
https://medium.com/@EmreEkrem/as-almost-everyone-in-the-crypto-world-knows-after-segwit-there-appeared-too-many-forks-bitcoin-fee1c07e90d

There are many people burned by this because the  mistakes BTG GOLD team have made with linking scam wallets to their official website!  I contacted them and they said that 4 people are working on the situation

**Comment by Merrtiee** [comment]
I lost 30k euro! Read my post! How can I get in touch with them? @emre9712

**Comment by evadogstar** [comment]
Predicated final when schoolchildren climb to make money on HYIP&blockchain and solve on the school party to make there own bitcoin

**Comment by evadogstar** [comment]
Total scam :) My mined BTG gold was also stolen. BTG GOLD and devs SCAM

**Comment by h4x3rotab** [comment]
Duplicated. #213

**Comment by emre9712** [comment]
Go do better things than closing issues

**Comment by emre9712** [comment]
here are the adresses that scammer used when steatling my coins 

GNr19CrZ3EzYQVZ6DLJXfLtTxWu9RvhokG

GfVhxiz7CEgGeTkrxeyPbpXCgsHcPWb4Bh

GRvhh6sTUrgjsqpxTm7KDCU9RvD9MstgJe

GbtGnXxvcAkXVQp8WTkTtu8jhLZWgqkPXW

GbwA3Q6zgRPDuznhQzbKkfT511wMc9bRqT

GT6oPUqB76LcTuttZe4AU5HAbheJJZzvKB

Geq1aXh8vbjEsYqNANTFrbzfwT3gzGXbhe

GftWLQG9Y5GUEyafihbhrY2eXPWFBihFzD
