### ISSUE TITLE
bgoldd crash when try to import private key

### ISSUE THREAD

**Issue by miranos** [BTCGPU/BTCGPU#207]
I have problem importing private keys on my wallet !

Using the command ` importprivkey`, each time i launch it, btgold crash !

Any one have same problem ?

The second problem is that i launched `bgoldd -bootstrap` from 5 days now and still 52 GO downloaded actually only ! (Any fix ?).

**Comment by khelle** [comment]
Did you mean crash or just stopped responding due to rescan? If you have multiple addreses that needs to be imported I would suggest you to import them with rescan=false flag, then do the rescanning on the last one - or simply use "importwallet" as it also seems to work.

**Comment by miranos** [comment]
Yes he stop responding ... but i don't know if is due to rescan or not.

I imported only one address, tried to import with other addresses but same issue, i had to stop bgoldd and launch it again in order for it to work.

When i import them with `rescan=false` balance will not show no ?

`importwallet` let us to import private key aswell ? i need to import one by one only not `wallet.da`t or long list.

Thank's.

**Comment by h4x3rotab** [comment]
Rescan will let your client to scan the entire blockchain. So it's a very time consuming operation. As @miranos said, you can import the wallet with `rescan=false` and manually trigger a rescan later.

BTW, I replied you in another thread. You can try `bootstrap.dat` torrent file to bypass the initial blockchain download without adding stress to the BTG p2p network. (And it could also be faster.) You need a fully synced client to get accurate balance.

**Comment by miranos** [comment]
@h4x3rotab Can you follow me to the thread where i can find `bootstrap.dat` ?

Since my server have only `200 GO` i can't download a zip file of `120 GO` and extract it no ?
Bootstrap.dat where i can put it once download since i am using UBUNTU ? In the folder `~/.bitcoingold` there only a subfolder `BLOCKS` that contains entir the blockchain no ?

Thank you.

**Comment by Ayms** [comment]
Please see https://github.com/BTCGPU/BTCGPU/issues/226#issuecomment-346672481

**Comment by wilsonmeier** [comment]
@miranos is the problem solved? If so, please close this issue. Thank you.

**Comment by shakilmia** [comment]
#226
