### ISSUE TITLE
Microsoft Visual C++ Runtime Library Runtime Error!

### ISSUE THREAD

**Issue by nedievas** [BTCGPU/BTCGPU#208]
After few hours of running Bitcoin Gold version v0.15.0.1-db7b378 (64-bit).
Every time this error and crash:
![capture](https://user-images.githubusercontent.com/6176288/32970423-9a90c752-cbf1-11e7-9b09-5fd84223208b.PNG)
Machine specs:
- OS: Windows 10 Pro
- CPU: Intel Core i7-4770 @ 3,40GHz
- RAM: 16 GB
- Disk size: 931GB total / 80.8GB free 
- Disk Type (HD/SDD): SSD

**Comment by h4x3rotab** [comment]
Could you take a look at debug.log or upload it here? You should be able to find it under [datadir](https://en.bitcoin.it/wiki/Data_directory).

**Comment by nedievas** [comment]
Here is the [debug](https://www.dropbox.com/s/pechludcyw53juj/debug.log?dl=0). I even did not notice how it crashed. It just disappeared from taskbar.

**Comment by h4x3rotab** [comment]
The 425970th line complains out of memory. But 16GB should be sufficient to run a full node. Maybe we can try to monitor the memory usage over time. One of my node has been running for nearly a week in a linux machine with 4GB RAM.

**Comment by devilsmist** [comment]
i am also been getting this issue  their is a problem with the destop app i have put in a bug report as it crashed my computer
