### ISSUE TITLE
Exact fork date?

### ISSUE THREAD

**Issue by DaanDD** [BTCGPU/BTCGPU#21]
If I understand correctly, from this file:

https://github.com/BTCGPU/BTCGPU/blob/master/src/chainparams.cpp#L82

It seems like the fork already happened, at block 487427. The website however says Bitcoin Gold won't launch until October 25. How will this work exactly?

**Comment by h4x3rotab** [comment]
The fork date is postponed to Oct 25. We haven't finalize the block height yet but it will be published with the launch of the website soon.

Also please note that the fork date doesn't mean the launch date. At the fork block height we will "take a snapshot" of the bitcoin blockchain, and begin to mine from that block of Bitcoin Gold a few days later, to ensure that the launch is fully prepared.

**Comment by tiagosd1** [comment]
Could you give us the pool so we'll be together?

**Comment by h4x3rotab** [comment]
After the launch, everyone can connect the the mainnet to mine BTG. We are also working with a few pools and will publish later. Testnet will arrive before the launch.

**Comment by sennevb** [comment]
miningspeed will add the coin on launch! we will test on testnet once it is released

**Comment by sennevb** [comment]
is there any slack or so where you guys are on?

**Comment by h4x3rotab** [comment]
https://join.slack.com/t/bitcoin-gold/shared_invite/enQtMjUxOTQxMzkyMDE3LWM0OTA1NjU1NzI5ZGM5YzY5M2RkNDIyNWQ1ZmRkMzI1NGFmMjJmNjkyMjg3Y2FlMTg4MjAyMmU2OGUzMGU5MzQ

**Comment by Grimm2017** [comment]
Slack link doesn't work

**Comment by krtschmr** [comment]
>>After the launch, everyone can connect the the mainnet to mine BTG. We are also working with a few pools and will publish later. Testnet will arrive before the launch.

nicely written. especially **after the launch**. so, it's still 16.000 blocks pre-mined, right?

diff-adjustment after each block so we can expect you guys keep the 2.5 min blocktime. 

16k * 2.5 = 40000minutes / (24*60) = 27-28 days.

so you'll fork, keep it all private for 27-28 days and then let *us* join the pool-party?
that's an issue somehow. so at the time of your *launch* when you want to get my 1070 mining farm to support you, there is also a huge fork in the books with X2 which might gain way more attention.

**Comment by h4x3rotab** [comment]
I'm going to close this issue because the exact fork height is already in the README.md.

**Comment by krtschmr** [comment]
was it forked? yes or no? will the snapshot be used?
