### ISSUE TITLE
Error syncing to regtest node with more then 3000 block height

### ISSUE THREAD

**Issue by litwi1rm** [BTCGPU/BTCGPU#211]
#### If so, please list the steps to reproduce below:
1. Node 1 - #bgoldd -server -deamon -regtest -whitelist=node2-IP
2. Node 1 - #bgold-cli -regtest generate 3001
3. Node 2 - #bgoldd -server -deamon -regtest -whitelist=node1-IP -connect=node1-IP

### Expected behaviour
Node 2 should sync to block 3001

### Actual behaviour
ERROR: ContextualCheckBlock: only one coinbase output is allowed
ERROR: AcceptBlock: bad-premine-coinbase-output (code 16)

### What version of bitcoin-core are you using?
0.15 

### Machine specs:
- OS: Ubuntu 16.04.3 LTS

**Comment by h4x3rotab** [comment]
Understood. The logic is not fine for testnet & regtest mode.

To solve this, the conditions to skip premine whitelist at `chainparams.cpp: CChainParams::IsPremineAddressScript`
```
    if (!consensus.BTGPremineEnforceWhitelist) {
        return true;
    }
```

should be moved to `validation.cpp: ContextualCheckBlock`:
```
    if (nHeight >= consensusParams.BTGHeight &&
        nHeight < consensusParams.BTGHeight + consensusParams.BTGPremineWindow &&
        !consensus.BTGPremineEnforceWhitelist)
```

I'm going to make this change soon but the above code should be able to unblock your work.

**Comment by litwi1rm** [comment]
@h4x3rotab with your change I'm able to sync now past 3000, but when I try to mine on regtest after block 3000 I am now getting this:

`CheckBlockHeader(): Equihash solution invalid`

**Comment by h4x3rotab** [comment]
The regtest mode has the setting of N = 48, K = 5. I assume you are trying to mine with regular miners, which often doesn't support this setting. However you can feel free to change it for testing purpose.

Code here:
https://github.com/BTCGPU/BTCGPU/blob/5d1e5ce9ab5d4d98cef7b25d30c2391c15558d61/src/chainparams.cpp#L394

**Comment by litwi1rm** [comment]
This works, thanks!

**Comment by oliverw** [comment]
@litwi1rm @h4x3rotab That's strange. Implementing the changes mentioned here crashes the daemon on <code>bgold-cli -regtest generate 3001</code>. Does not happen with 2999.

**Comment by litwi1rm** [comment]
@oliverw I had the same issue, I'm not sure what the const_t is for but when I changed it to the same settings as mainnet it seemed to take a lot more resources when using `bgold-cli -regtest generate`. I ended up only generating 500 blocks at time until I got to 3000 to get it to work.
