### ISSUE TITLE
bgoldd derives address with 0 BTG from segwit p2sh private key from joinmarket.

### ISSUE THREAD

**Issue by frenchgox** [BTCGPU/BTCGPU#215]
At block 491407 I had coins in an address in segwit joinmarket. For example:

https://blockchain.info/address/36iSWFrXZrkDYNJaEc2XgeCXixP9S5z55Z

I generate the private key for this address from joinmarket and import it into bgoldd.

The address bgoldd derives from that key contains 0 BTG.

Please help me figure out how to get the private key from segwit joinmarket that bgoldd needs to access the BTG.

**Comment by h4x3rotab** [comment]
You can check the balance here:
https://btg-bitcore2.trezor.io/address/ALoJEDDiM75zGAp8gA2GQu6h4328JADeWv

(The address are converted by `bgold-cli -convertaddress 36iSWFrXZrkDYNJaEc2XgeCXixP9S5z55Z`)

SegWit address are actually P2SH addresses. It's not derived by the pirvkey directly. Bitcoin Core doesn't have a full segwit wallet support. This discussion is worth reading: https://bitcointalk.org/index.php?topic=2182148.0

**Comment by molxyz** [comment]
@h4x3rotab Hello,  

I had some Bitcoin in a BTC Segwit P2SH address before Bitcoin Gold fork.  With Bitcoin Knots wallet I can get the private key of a Segwit P2SH address, the private key is the same as the key of the Bitcoin legacy address.  I can import this private key to Bitcoin Gold full node, then I use this site to convert both BTC legacy and Segwit p2sh addresses:  https://ledgerhq.github.io/btg-convert/

But when I use "validateaddress", bgold node only can see that the BTC legacy address "ismine: true" but it can not see the BTC Segwit P2SH address.  And my balance on Bgold wallet is 0 when it should show the same balance as in the BTC Segwit address.  (I can see this balance in Bgold Segwit on Bgold explorer but there's no way I can get the Bgold full node to show this on my wallet).  Is there something that I'm missing?  Please help.  Thank you.

**Comment by molxyz** [comment]
@h4x3rotab  I found the solution. Pls ignore my last post. 
@frenchgox  What you need to do:  Get the BTC legacy address of your Segwit address, convert it to Bgold address, then do: "bgold-cli addwitnessaddress <converted-Bgold-address>", this is how you add your BTC Segwit address (which is auto converted to Bgold Segwit address) to the wallet.  Then restart your Bgold wallet with "bgoldd -rescan" and your balance will show up.

**Comment by drunkenclam** [comment]
@molxyz How do I get the BTC legacy address of my Segwit address? Thanks for your help.
