### ISSUE TITLE
Add some of web seeds and trackers to bitcoin gold website bootstrap.torrent

### ISSUE THREAD

**Issue by ghost** [BTCGPU/BTCGPU#219]
I've uploaded the bootstrap torrent files to my multiple S3 storage.
If bitcoingold.org adds my web seed directory and tracker server, it would be helpful for decentralizing BTG. (And it would help people download and establish their nodes much faster).

Just add these settings.

Tracker:

http://tracker.blockchaindownload.kr:2710/announce

udp://tracker.blockchaindownload.kr:2710/announce 

Web seeds:

http://chaindownload1.s3.amazonaws.com/torrent/
http://chaindownload2.s3.amazonaws.com/torrent/
http://chaindownload3.s3.amazonaws.com/torrent/
http://chaindownload4.s3.amazonaws.com/torrent/
http://chaindownload5.s3.amazonaws.com/torrent/
http://chaindownload6.s3.amazonaws.com/torrent/
http://chaindownload7.s3.amazonaws.com/torrent/
http://chaindownload8.s3.amazonaws.com/torrent/
http://shnano1.ipdisk.co.kr:80/publist/VOL1/Downloads/torrents/

If you have any questions please contract me anytime: shnano1128@naver.com

Here is my modified torrent file
https://chaindownload1.s3.amazonaws.com/bootstrap.torrent

**Comment by wjcloud** [comment]
And this job occurred more than 1000 GB traffic from my home....

**Comment by wjcloud** [comment]
![torrent](https://user-images.githubusercontent.com/32424832/33030187-0596cbdc-ce5e-11e7-9613-f8815dc246a3.PNG)

It works!

**Comment by Ayms** [comment]
Stop your bulls you too, trackers are not needed for torrents since 10 years and nobody care about your storage, torrents do not work like this

The magnet link for the official torrent is: magnet:?xt=urn:btih:EF763678E152BB91461FE9AE45E6F1FAEA422C79

Don't use anything else and certainly not the bootsratp.torrent file of this idiot or others posting/mirroring supposedly the official bootstrap.torrent file

**Comment by wjcloud** [comment]
@Ayms  If I change some information in this torrent file, it would not have any compatibility with those one. And most of all, we still need trackers in case of sharing information of peers, DHT or other method still needs tracker.

Plus I did it for some good reason, it doesn't harm anything or sharing some malware.

**Comment by francois007** [comment]
In the next days our company put online a free dedicated node with 1/Gbps real bandwidth.
The big problem of Bitcoin Gold is the slow chain synchronization.
https://bitcointalk.org/index.php?topic=2284289.msg24907859#msg24907859

**Comment by Ayms** [comment]
@wjcloud @francois007 The only way to help is to seed the official torrent in many places, not in some big places, even if this helps too, and certainly not to propose to download elsewhere a bootstrap.torrent file, which is of no use and prone to attacks/malwares, trackers are not required neither welcome with the DHT, bootstrap nodes exist

So the only trusted information is the infohash in the magnet link and this is all what is required to download the torrent, if people have deactivated the DHT then we cannot help them further

**Comment by francois007** [comment]
@Ayms  BTG nodes and seeds are very slow... this is the real big issue!

**Comment by Ayms** [comment]
I know, that's the issue since the begining, if you can sync and run full nodes with servers, then do it, and if you can help seeding the torrent from many places, then do it also

**Comment by francois007** [comment]
@Ayms My team is at work to run a full BTG node, at this moment we can't create a torrent chain source (full node run, but isn't sync and can't be launch).

**Comment by Ayms** [comment]
#226 

https://github.com/BTCGPU/BTCGPU/issues/226#issuecomment-346672481

Then see https://github.com/Ayms/bitcoin-transactions

If you can run a good full node and seed the torrent that's good, now for people who can't consider the above
