### ISSUE TITLE
Cannot connect to any peers

### ISSUE THREAD

**Issue by axelay** [BTCGPU/BTCGPU#22]
Cloned the repo, compiled it on a clean Ubuntu 16.04 server and started the process but I get no connections.

In the logs, I see several occurrences of the following:
2017-10-09 21:44:47 Misbehaving: xxx.xxx.xxx.xxx:8333 peer=12 (0 -> 100) BAN THRESHOLD EXCEEDED
2017-10-09 21:44:47 ERROR: invalid header received
2017-10-09 21:44:47 ProcessMessages(headers, 135597 bytes) FAILED peer=12
...
2017-10-09 21:49:45 ERROR: AcceptBlockHeader: Consensus::ContextualCheckBlockHeader: 000000000000000000bd23f1e0ac2383fe48b53e169c0bee7a1f6411bdb3a8a3, bad-diffbits, incorrect proof of work (code 16)
...

Perhaps I am too early for this but I thought I should be able to synchronize in preparation for the fork.
What am I doing wrong?

**Comment by maloner** [comment]
There was talk about changing the port no - I wonder is this the issue:

https://github.com/BTCGPU/BTCGPU/issues/16

Looks like you are on 8333 - BTC default mainnet - have you tried testnet?

**Comment by axelay** [comment]
When running in testnet it does synchronize but not on mainnet.
I understand the need to change the default port numbers when all the processes are running on the same machine (Bitcoin + Bitcoin GPU + Bitcoin whatever) but when it's running from a single server there's no need. Besides, I don't think this would affect the failed connections - I think it's more a case of my server trying to connect to other versions of Bitcoin and not succeeding.

Any insight from the main devs?

**Comment by h4x3rotab** [comment]
@axelay, it's the intended behavior. Bitcoin Gold can connect to Bitcoin p2p network to download the blockchain before the fork, but after the fork height, no block from Bitcoin network will be accepted.

The software is under development and several changes should be made. I will keep this issue until the testnet can be launched without problem.

**Comment by abakus1** [comment]
I all the time have 
2017-10-23 18:35:49 connect() to 74.208.221.224:8338 failed after select(): Connection refused (111)
With all the address

**Comment by StarbuckBG** [comment]
Reffer to this PR: #49 
Issues: #39 #36
