### ISSUE TITLE
stuck at block 491406

### ISSUE THREAD

**Issue by MCrypto** [BTCGPU/BTCGPU#224]
been stuck at this block for two days now!

running compiled bins version:
Bitcoin Gold RPC client version v0.15.0.1-db7b378

> ./Coins/BTG/bin/bgold-cli getblockchaininfo
{
  "chain": "main",
  "blocks": 491406,
  "headers": 501120,
  "bestblockhash": "000000000000000000b23dfce1c518814ec15cc1416f5e72af1844c17d470244",
  "difficulty": 1196792694098.793,
  "mediantime": 1508804637,
  "verificationprogress": 0.9717438055107958,
  "chainwork": "000000000000000000000000000000000000000000a21782bdf8690807c8e5af",
  "pruned": false,
  "softforks": [
    {
      "id": "bip34",
      "version": 2,
      "reject": {
        "status": true
      }
    },
    {
      "id": "bip66",
      "version": 3,
      "reject": {
        "status": true
      }
    },
    {
      "id": "bip65",
      "version": 4,
      "reject": {
        "status": true
      }
    }
  ],
  "bip9_softforks": {
    "csv": {
      "status": "active",
      "startTime": 1462060800,
      "timeout": 1493596800,
      "since": 419328
    },
    "segwit": {
      "status": "active",
      "startTime": 1479168000,
      "timeout": 1510704000,
      "since": 481824
    }
  }
}

**Comment by h4x3rotab** [comment]
Are you running with `-bootstrap` flag enabled?

**Comment by dexX7** [comment]
I stuck earlier, too. Then I shut down, deleted everything and started with `-bootstrap`. Now I don't seem to find any peer and get disconnected all the time?

**Comment by dexX7** [comment]
How comes all peers either disconnect or are not available?

**Comment by h4x3rotab** [comment]
-bootstrap flag will connect to Bitcoin p2p network and stop at 491406. Then you can stop the node, delete peers.dat file and restart the client without -bootstrap flag again. This will help you connect to BTG network.

**Comment by dexX7** [comment]
I assume `-bootstrap` only works if headers are not yet synchronized?

It looks like it's working now, but I needed to add some peers manually, because the ones from the DNS server all rejected the connection.

**Comment by dexX7** [comment]
Actually, it stopped working. Even when I manually add peers, they seem to stall and then end up being banned for some reason.

**Comment by MCrypto** [comment]
actually yes i was running it with -bootstrap ... apologies for the delayed feedback!

this got me working:

[https://github.com/BTCGPU/BTCGPU/issues/176#issuecomment-343800054](url)
