### ISSUE TITLE
Double pay!! Great I love it,  but you need to look into this:

### ISSUE THREAD

**Issue by gratiot** [BTCGPU/BTCGPU#225]
This issue tracker is only for technical issues related to bitcoin-core.

General bitcoin questions and/or support requests and are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).

For reporting security issues, please see the official [Bitcoin Gold website](https://btcgpu.org/).

### Describe the issue
Just received 2 payments for the same amount at the same time 

### Can you reliably reproduce the issue?
No

### Expected behaviour
Tell us what should happen
Only 1 payment but seemed to receive 2

Got 2 payments Via coinomi for the same amt.

**Comment by gratiot** [comment]
OK, So I now have a negative balance on my workers... So i guess I'll make it up to??

**Comment by evadogstar** [comment]
Show us you wallet on btg scam explorer. 

Looks like your coins was stolen and scammer send you additional amount to hide and wash coins on your wallet

**Comment by gratiot** [comment]
Please, explain what you mean "to hide and wash coins on your wallet"

**Comment by h4x3rotab** [comment]
Can you post more details? Are you using the core wallet? Is the receiving address from your BTC wallet or a brand new one?

**Comment by gratiot** [comment]
No worries, They announced there was a double payment and all balances 
were set to a negative number to be made up in upcoming rounds.

I think all is well now.

**Comment by wilsonmeier** [comment]
@gratiot is the problem solved? If so, please close this issue. Thank you.

**Comment by gratiot** [comment]
Yes this is resolved -- should have closed earlier- Thanks
