### ISSUE TITLE
Unable to Sync Wallet - Peer Connections not holding

### ISSUE THREAD

**Issue by GaaTY** [BTCGPU/BTCGPU#228]
So, BTG launched. I downloaded the Bitcoin Gold Core Windows Wallet. Got my address, started mining.

I have the wallet open for 2 straight days, 0 active connections. It does not sync. I do a bit of searching to see if I'm not the only one, I am not. See suggestions of adding nodes to the bitcoin.conf and restarting the wallet.

Success! My wallet is now syncing. This was about 12 days ago...

-------------------------------------------------------

2 days ago I open my wallet again. 33% synced so far, but it does not want to sync anymore. It holds at most 1 connection. In the Debug Window -> Peers list, peers pop up and disappears. This goes on for hours.

[Bitcoin Network Nodes.txt](https://github.com/BTCGPU/BTCGPU/files/1501678/Bitcoin.Network.Nodes.txt)

These are all the nodes in my bitcoin.conf file. I have even copied and pasted nodes from https://status.bitcoingold.org/dl.php?format=config - NOTHING WORKS.

I've tried manually adding nodes in the console - DOESN'T HELP.

I am wits end. I need some help, I have 120007 blocks left to sync.

**Comment by bovcan** [comment]
download bootstrap from website

**Comment by h4x3rotab** [comment]
VALIDATE YOUR CHECKSUM!
https://bitcoingold.org/critical-warning-nov-26/


You can find a long node list from: status.bitcoingold.org

**Comment by dexX7** [comment]
@h4x3rotab:

It's still not working, whatever I try:

- Fresh start with `-bootstrap`, adding Bitcoin Core nodes
- Fresh start without `-bootstrap`, adding Bitcoin Gold nodes

And a mix of both. Sometimes at the beginning I get a connection, but at some point it simply stalls.

In the logs I get a variety of errors, such as:

- invalid headers
- connection refused
- network not reachable

I even tried to compile BTG with the seed list of Bitcoin Core.

**Comment by GaaTY** [comment]
@h4x3rotab 

I have validated the installer. I initially downloaded when the mainnet launched on the 12th of November.

Bootstrap is downloaded, started shortcut with the bootstrap option , added node list into wallet config - sync still not happening.

**Comment by h4x3rotab** [comment]
“-bootstrap” option should never be used in future and will be removed
completely. If you have used it, please delete peers.dat to ensure it won’t
pollute the network.

You can use the bootstrap file (torrent) and add the node list to quickly
sync to the BTG network.

**Comment by wilsonmeier** [comment]
@GaaTY is the problem solved? If so, please close this issue. Thank you.

**Comment by GaaTY** [comment]
Problem is not solved perse, but I managed to get the wallet synced finally. It took a combination of adding the bootstrap switch, adding the bootstrap file, removing the switch and removing the file (a number of times).
