### ISSUE TITLE
GBT missing coinbasetxn

### ISSUE THREAD

**Issue by sammy007** [BTCGPU/BTCGPU#229]
```
curl -X POST -H "Content-Type: application/json" --data '{"id": 0, "method": "getblocktemplate", "params": [{"capabilities": ["coinbasetxn", "workid", "coinbase/append"]}]}' U:P@IP:PORT
```

Result does not contain `coinbasetxn`. Did you remove it on purpose?

**Comment by h4x3rotab** [comment]
I think our code is the same as Bitcoin Core:
https://github.com/bitcoin/bitcoin/blob/master/src/rpc/mining.cpp

**Comment by sammy007** [comment]
I am asking why there is no coinbasetxn in getblocktemplate call, not if you code is the same as core or not.

**Comment by StarbuckBG** [comment]
Sammy, behave!

The code works the same way as Bitcoin. Where have your seen this information to be returned ?

**Comment by h4x3rotab** [comment]
Look like Core never supports this field: https://github.com/bitcoin/bitcoin/issues/11061
