### ISSUE TITLE
System Tray Icon Menu not Appearing

### ISSUE THREAD

**Issue by D3m0nKingx** [BTCGPU/BTCGPU#23]
### Describe the issue
Bitcoin Gold's System Tray Icon's Menu is not working

#### If so, please list the steps to reproduce below:
1. Open Bitcoin Gold Wallet
2. Right-Click On System Tray Icon

### Expected behaviour
Appmenu should be displayed with various wallet operations that can be performed, (show/hide, receive/send, sign/verify message, options..., debug window, exit) 

### Actual behaviour
Blank narrow box appears

### Screenshots.
![kazam_screenshot_00000](https://user-images.githubusercontent.com/18432686/31530798-c9c97f9e-afb0-11e7-8541-5080ff6981c0.png)

### What version of bitcoin-core are you using?
Version: v0.15.0.1-b195fa2
Compiled locally

### Machine specs:
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	        16.04
Codename:	xenial

### Any extra information that might be useful in the debugging process.
Both appmenu-qt and appmenu-qt5 packages are installed:
```
 appmenu-qt:amd64      0.2.7+14.04.20140305-0u amd64         application menu for Qt
 appmenu-qt5           0.3.0+16.04.20170216-0u amd64         application menu for Qt5
```

**Comment by h4x3rotab** [comment]
Thanks for reporting! Will investigate it further after the consensus change has been made or when have enough devs.

**Comment by mk229797** [comment]
sudo apt-get remove appmenu-qt5 #this will fix it

know issue - https://github.com/bitcoin/bitcoin/issues/1242

**Comment by mk229797** [comment]
Or compile against QT4 not QT5 (thats how Bitcoin Core is compiled in Ubuntu)

**Comment by h4x3rotab** [comment]
@mk229797 Great finding! Thank you.
