### ISSUE TITLE
Reduce size of blockchain through "prune"

### ISSUE THREAD

**Issue by Z1gun** [BTCGPU/BTCGPU#230]
Could you advise "safe" parameter (block number) for `prune` deamon option in BTG blockchain?

**Comment by StarbuckBG** [comment]
Mine is 500.

**Comment by h4x3rotab** [comment]
You have to add the address to your wallet before enabling `prune` mode. Otherwise your wallet will not be able to show the balance correctly. Feel free to use prune mode if you don't use it to check any balance.
