### ISSUE TITLE
Checksum for Setup not matching

### ISSUE THREAD

**Issue by deforation** [BTCGPU/BTCGPU#231]
The Checksum f the downloaded bitcoingold-0.15.0-win64-setup.exe does not match with the data given on the download page.

The calculated sha-256 hash value is "8E9D4CB73116BEB173D6079792D474BA29488C6DE30A05D2D77BFF7850C80B0D" and not "53e01dd7366e87fb920645b29541f8487f6f9eec233cbb43032c60c0398fc9fa " as stated.

What is the reason? 
I have used different applications to calculate the hash value and all give me the same value.

**Comment by h4x3rotab** [comment]
Please don't use the version with bad sha-256 checksum! I downloaded the file from release page again and indeed the sha-256 checksum doesn't match. I'm trying to figure out the reason. During this period, you can compile your own client from source code.

**Comment by h4x3rotab** [comment]
ATM I removed the Windows binary with the bad checksum. I keep the copy of `8E9D4CB73116BEB173D6079792D474BA29488C6DE30A05D2D77BFF7850C80B0D` version and I've reported to GitHub support.

I will upload the correct version later.

**Comment by h4x3rotab** [comment]
The correct file has been uploaded again. Still checking how it was replaced.

**Comment by Cripsii** [comment]
I have a version downloaded on 11/21 @ 20h37 UTC (21h37 UTC +1)
the SHA-256 is
`0ccbae26914fc36973c5b74f0c031ba324bcffc7bbb188e752498573345215d5`

what's about this file? you said the problem occurd between November 24, 2017, 13:11, UTC and November 25, 2017, 22:30, UTC..

**Comment by h4x3rotab** [comment]
Yes. Because we found the compile date of `8E9D4CB73116BEB173D6079792D474BA29488C6DE30A05D2D77BFF7850C80B0D ` is November 24, 2017, 13:11. Can you upload the file you downloaded?

**Comment by Cripsii** [comment]
https://mega.nz/#!Po8gHQbI!OmF39-vF3dbgGl6fBSAehqN5V4AU22OcyqM53QL23TY

Sorry for mega link.. I don't known where host it.

**Comment by h4x3rotab** [comment]
It was compiled on Nov 21 9:39 UTC. Things are getting worse.

You should send all your coins to another wallet created in another clean computer / device and delete the client right now. Then you should take actions to ensure your safety like you found a trojan on your computer.

**Comment by Cripsii** [comment]
I doesn't create wallet with this client. I don't have any wallet client on this computer.

**Comment by h4x3rotab** [comment]
But before we figured out what has been changed, please treat it as a trojan.

**Comment by h4x3rotab** [comment]
Update: found some unknown IP login from GitHub record.

```
22 hours ago user.login – Originated from 178.20.55.16
2 days ago user.login – Originated from 199.249.224.44
2 days ago user.login – Originated from 212.21.66.6
3 days ago user.login – Originated from 199.249.224.49
5 days ago user.login – Originated from 51.15.53.83
5 days ago user.login – Originated from 192.42.116.16
6 days ago user.login – Originated from 179.43.146.230
11 days ago user.login – Originated from 64.137.178.43
On Oct 24 user.login – Originated from 185.117.118.234
```

**Comment by Technophant** [comment]
What has been done to analyze the application to see what it does? Is somebody assigned to this?

**Comment by im0rtel** [comment]
hi there. what type of malicious file has been injected in the windows executable? anyone can post a investigation report?

**Comment by Cripsii** [comment]
It's a very serious problem anyway. I hope that we will have a report extremely quickly.
This is the least of things.

**Comment by StarbuckBG** [comment]
h4x has changed all the files to the right ones. However this is why the checksum is given. No-one is safe in that world. There will be more detailed info tomorrow.

**Comment by certless** [comment]
Thank you for investigating.  I downloaded from bitcoingold .org download's page on November 23 2017 10:17 ET (UTC -05:00).  I just checked SHA256 hash but it does not appear to be one of the altered files.  I also just re-downloaded from the download's page again and the SHA256 hash for both files are the same.  I still agree with recommendations above to do a full overhaul of the computer now.

**Comment by h4x3rotab** [comment]
So the hash is `53e01dd7366e87fb920645b29541f8487f6f9eec233cbb43032c60c0398fc9fa `, right? If so you can use if safely.

**Comment by h4x3rotab** [comment]
> What has been done to analyze the application to see what it does? Is somebody assigned to this?
I reached out to some reverse engineering experts to do this but don't have an ETA yet.

**Comment by leberknecht** [comment]
To restore a bit trust, can you provide information about the build environment that you used for the precompiled binaries? Or a dockerfile for compiling, to re-procude the given checksums...that would be awesome. But i can imagine that you have a zillion things to do atm. Still, would be nice to be somehow be able to verify that the provided binaries are in sync with the source.

**Comment by h4x3rotab** [comment]
`Gitian` is the system should be used to produce trustable build and we are actually working on gitain adaption. It does exactly the same thing you want: to reproduce the same binary as the release version from a source tree. However it's still a work in progress. Submitted PR: #221 #222.

The build environment of the current binary is Ubuntu v14.04 with default build tools. All the dependencies are built from `depends/` directory. But this can't ensure the output binaries will match the one I produced because of lots of factors that affects the outputs.

Btw, I'm also going to sign the checksum by gpg like described at #239.

**Comment by h4x3rotab** [comment]
I believe things are finally solved. I will post a link to the official post about this later.

**Comment by deforation** [comment]
What was the Reason?
What had been changed in the potential malicious file?

**Comment by h4x3rotab** [comment]
The official post is ready: https://bitcoingold.org/vulnerable-wallets/
The technical analysis will be published a bit later.

**Comment by leberknecht** [comment]
I'm very surprised that everyone seems to be fine with it :) so i havent lost any money, but if i would have been affected, i would at least expect that you inform LEA and file a complaint about the breach of your account etc... but ok, apparently most people seem to be fine with getting robbed by official partners and hacked binaries etc (btw, have you checked the other binaries? maybe all binaries were affected and he just forgot to update the checksum for the win binary). 

So i guess thats it, everything back to normal, congratulations :) Can you give more details what "a bit later" for the tech details of the malicious file means?

**Comment by leberknecht** [comment]
Update please

**Comment by h4x3rotab** [comment]
I've prepared a technical analysis post. Now we have returned more than 70% of the vulnerable coins. It's time to publish the details. The post will be live in 1-2 days.

**Comment by h4x3rotab** [comment]
Check it out:
https://github.com/BTCGPU/BTCGPU/wiki/Replaced-Windows-Wallet-Problem-Analysis-(Nov-26th)

**Comment by leberknecht** [comment]
First: Thanks for the update :)
Second: Hm, not sure if it was a smart move to release the constants of the modified privkey... 
Before: if someone triggers transactions, you know it was the hacker or the owner. 
Now: could be anyone reading this... 
You are black-hat'ing your own fuckup somehow.. 

How did the returning of the coins took place? What is with the other 30%? Were legal steps taken aka was LEA informed about the breach of the account? Was the IP traced, did it lead to an proxy/tor-node or something else? What was the volume of coins compromised?

**Comment by h4x3rotab** [comment]
The constants are posted because all the affected addresses have got no money for a few months. Hiding the constants won't help much as the technology is already published :)

Here you can find more info about how the wallet are swept by us before it got hacked and the amount:
https://bitcoingold.org/vulnerable-wallets/

Details about how we verify the owner of the swept coins will be reveal soon on our official blog.

The suspicious IPs are from VPS providers as I posted before. I don't have more clues as the providers don't cooperate to reveal more information and I guess they are behind multiple layers of proxies.

**Comment by leberknecht** [comment]
:+1: thank you :)
