### ISSUE TITLE
Strange Transaction behavior

### ISSUE THREAD

**Issue by dfair98** [BTCGPU/BTCGPU#234]
After the wallet announcement, I started looking into my own wallet (bitcoingold-0.15.0-win64-setup.exe downloaded on launch day) and I noticed what seems to be abnormal behavior and I am not sure if it’s extended behavior or a bug. 

After my first transaction I noticed some strangeness,  I thought it was fluke, but here are the steps I took to verify and reproduce this behavior:

1.	Sent 0.05528121 BTG + 0.00000670 BTG fee to an exchange
2.	Waited for the transaction to be broadcast
3.	Pulled up the transaction in both btcexp.com and btgblocks.com
4.	The amount send was 0.0628609 which is more that 0.05528121+ 0.00000670 fee (**STRANGE**)
5.	There is another recipient for the amount of 0.01000488 (**STRANGE**)
6.	Switched back to my wallet, and I have a pending balance of 0.01000488 no transaction recorded (**STRANGE**)
7.	I waited for my transaction to complete, my 0.05528121 is sitting on an exchange
8.	The pending amount is now available as if it never was sent (**STRANGE**)
9.	Pull up the BTG address in btgexp.com and btcblocks.com  and the balance is 0.01000488 less than my wallet (**STRANGE**)

Now that I have done this twice, I open up the console in my wallet and ran listaddressgroupings :
1.	Shows my main BTG address and balance minus the two additional recipients amounts (**STRANGE**)
2.	Shows the first additional recipient and balance (Deposit is not in transaction list even though it was pending)
3.	Shows the second additional recipient and balance (Deposit is not in transaction list even though it was pending)

Neither one of these additional recipient addresses show up anywhere in my wallet.
Is this expected behavior? I can provide additional information if needed

**Comment by StarbuckBG** [comment]
Hello David!

Can you please do the following

1. Go to Preferences
2. Wallet -> Enable Coin Control 
3. Go to Send menu
4. Click Inputs and check if the 2 addresses are there

The Core client splits the amounts sometimes between your addresses. This happens to improve anonymity and also you have more than 20 generated addresses at the first start. In the exchanges and 3rd party wallets you receive 1 wallet address. However in the core client you have 1 account with many addresses. You can send and receive with all these addresses.

You can also export your wallet information to check if the addresses are there. 

Waiting for your reply.

**Comment by dfair98** [comment]
Yes, they are both there. Both are Received with label  (change). did they think the transaction fee was higher then it was?

**Comment by StarbuckBG** [comment]
Hello!

No, the transaction is internal. So no higher fee.

Wish you all the best. If there are other questions please write them here.

Best regards,
MK.

**Comment by StarbuckBG** [comment]
Hello!

No, the transaction is internal. So no higher fee.

Wish you all the best. If there are other questions please write them here.

Best regards,
MK.
