### ISSUE TITLE
Get Bitcoin Gold from a Electrum 2fa wallet

### ISSUE THREAD

**Issue by fabrizio83** [BTCGPU/BTCGPU#238]
I have a Electrum 2fa wallet and I can't get my Bitcoin Gold... give a method to do that.
You are not proving to be a active community and this take away trust from Bitcoin Gold.
Please, do something.

**Comment by kxjhlele** [comment]
me too

**Comment by MarkusZoppelt** [comment]
Me too. The only wallets that claimed (ha!) to offer that were scam sites. Please provide an official solution for Electrum 2fa wallets.

**Comment by Ayms** [comment]
You can take a look at https://github.com/Ayms/bitcoin-transactions#addresses-and-getting-free-coins and eventually use the tool (but never use P2SH/Segwit/BIP141 addresses)

**Comment by JaydenClayton5** [comment]
I'm offering a service to extract Bitcoin Gold from a 2fa Electrum Wallet, I'll take only 5% of the recovered BTG for this, yes, it's complicated and requires a lot of time but it's doable, I will take care of everything, if you are interested hit me a PM or add me on Skype: jayden82@greenmail.net
I suggest you to do this as fast as possible, before BTG actually fails, as everyone are saying sell ASAP, so contact me and I'll take care of you You won't even need to download the entire blockchain of the BTG Core Wallet, I will send BTG to a Coinomi wallet of yours if you wanna hodl them or to an exchange if you wanna sell them (if you are not pratical I can help with this too, don't worry).

**Comment by wilsonmeier** [comment]
To everyone: Stay away from such obvious scam attempts. The account was created 10 minutes ago.

**Comment by spaunes** [comment]
me too

**Comment by turboblade** [comment]
I used syntax from this thread successfully, though slightly more complicated as had multiple inputs

**Comment by turboblade** [comment]
https://bitcointalk.org/index.php?topic=2424484.new#new

**Comment by Ayms** [comment]
I made the tool mentioned above so you don't have to sync a node and your wallet but it does not handle p2sh/multisig for now, because I thought it was useless

Is really Electrum multisig wallets the common use case?

**Comment by klaaspieter** [comment]
I don't know if it's _the_ common use case, but judging from the amount of questions about getting Bitcoin Cash and Gold from an Electrum 2FA wallet (which is multisig) it is definitely not uncommon. I initially set it up because 2FA seemed the most secure, I wasn't aware of these implications at the time.

**Comment by Ayms** [comment]
Amazing... things are not complicate enough, people are using multisig wallets...

I will modify the tool to handle p2sh and multisig, so people don't have to run the sw/sync and do the outstanding (and dangerous) manipulations that we can see in the above thread

But as explained in my link above it remains mysterious for me why people are rushing to send "from a wallet to another", which means nothing since they already have their coins, it should better be from a wallet to an exchange for example so they can spend the coins without paying twice the network fees

**Comment by shakilmia** [comment]
#213

**Comment by ApproximateSunlight** [comment]
Check this: https://github.com/BTCGPU/BTCGPU/issues/246

**Comment by Ayms** [comment]
See https://bitcointalk.org/index.php?topic=2550529.msg26078268#msg26078268

#246 might be useful while this is already explained in other threads

But my first sentence shows how minimal/very basic security requirements are missing and "Before doing this, empty your wallet from BTC, move all your BTC to a brand new wallet (very important)" is just inept, don't do this

Unknown and newcomer on github (and bitcointalk) @ApproximateSunlight apparently does not know what he is doing too and/or is giving wrong advises maybe to motivate some paid support, it's unclear in his procedure but apparently btgexplorer is supposed to be queried with bitcoin core addresses, which does not work at all, I have explained several time what is the easy way for this (query a bitcoin core explorer to get the tx ref)

For the reasons explained I still think that the tool is useful then I will finish implementing multisig

**Comment by leto** [comment]
@Ayms I believe that advice "empty your BTC into a new address" is old paranoid advice from before 2-way replay protection was a real thing, so people were reasonably paranoid about that. I agree with you that it's not necessary (confirmed by people smarter than me) but just about all the info that can be found online mentions things like this, there is so little good and up-to-date info. Thanks for your tool, it looks super useful.

**Comment by Ayms** [comment]
@leto thanks, please see the ongoing discussion https://bitcointalk.org/index.php?topic=2550529.msg26150335#msg26150335

The two of two, or worse, two of three paranoid "protection" have just created a mess, not sure if it is intended by the wallets creators or not

I am discovering what people are doing, and I am amazed, I must be missing something, what happened to motivate people to use multisig wallets?

Finishing the tool for multisig and maybe the next step after is to have it inside browsers as a standalone <b>OFFLINE</b> more user friendly app, if there is an interest

**Comment by wilsonmeier** [comment]
Word of advice:

Please always use extreme caution by using such tools. 
Move your BTC into a new wallet before exposing your private keys.
Yes this costs you some network fees but it will save your BTC in case of private key leak or scam activities.

**Comment by Ayms** [comment]
You can advise this kind of thing but it is recommended to explain why, so people understand what they are doing, if not you can get the very contrary ending up with people being stuck with multisig wallets for example, like it is the case now

The tutorial is OK now https://bitcointalk.org/index.php?topic=2550529.msg26192086#msg26192086

**Comment by Ayms** [comment]
Here it is https://github.com/Ayms/bitcoin-transactions "add multisig support"

Should work for BCH too but has to be tested

Comments/remarks welcome
