### ISSUE TITLE
Signed Checksums

### ISSUE THREAD

**Issue by grant-olson** [BTCGPU/BTCGPU#239]
You should really sign the SHA256 checksums with a GPG key to provide one more tool for proper verification of the executables, rather than just saying 'the checksum on github is the correct one'.

**Comment by shakilmia** [comment]
h4x3rotab

**Comment by h4x3rotab** [comment]
Added GPG signature. Does it look good now?
https://github.com/BTCGPU/BTCGPU/releases/tag/0.15.0.1

Besides, we are working on gitian adaption to further secure the releases.

**Comment by grant-olson** [comment]
Your key isn't on the keyservers so I can't verify:

```
(facebook_python) master-blaster:facebook grant$ gpg --verify foo.asc 
gpg: Signature made Thu Nov 30 14:59:14 2017 EST using RSA key ID 597B4FC0
gpg: requesting key 597B4FC0 from hkps server hkps.pool.sks-keyservers.net
gpgkeys: key 38EE12EB597B4FC0 not found on keyserver
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
gpg: keyserver communications error: Not found
gpg: keyserver communications error: Bad public key
gpg: Can't check signature: No public key
```

http://pool.sks-keyservers.net:11371/pks/lookup?search=597B4FC0&fingerprint=on&op=index

You probably want to run `gpg --keyserver pool.sks-keyservers.net --send-keys 0x597B4FC0` to get it out where people can download it, and you probably want to publish the key id in verification documents.

**Comment by h4x3rotab** [comment]
http://pool.sks-keyservers.net:11371/pks/lookup?search=0x597B4FC0&fingerprint=on&op=index
gpg --recv-keys 0x597B4FC0

**Comment by verretor** [comment]
His link didn't return results because he was looking up "597B4FC0" instead of "0x597B4FC0".

**Comment by grant-olson** [comment]
Looks good now.
