### ISSUE TITLE
sigs missing

### ISSUE THREAD

**Issue by gitcnd** [BTCGPU/BTCGPU#240]
You are not signing your source code bundles (.zip and .tar.gz) - you are only signing the compiled works.

Please sign them all, so we know that no malicious replacements of source code functionality have taken place!

**Comment by h4x3rotab** [comment]
Thank you for addressing the concerns. However source code bundles are created by GitHub automatically based on the git tag. The release page also have the shortened commit id "287d089". I believe there's no way to upload or replace the source code bundles by malicious ones.

**Comment by grant-olson** [comment]
Now that you have a gpg key for signing the binary sigs, you can gpg sign your tags for major versions. Then someone who wants to authenticate can use github but check the sig on the tag. Short way to do this, add `-s` on your tag command. Longer description at https://git-scm.com/book/id/v2/Git-Tools-Signing-Your-Work

**Comment by h4x3rotab** [comment]
As currently the release process has been fully switched to Gitian build, all the binaries and the source code has been signed. I'm going to close this issue.
