### ISSUE TITLE
32-bit executables for RPi

### ISSUE THREAD

**Issue by sheepy0905** [BTCGPU/BTCGPU#241]
### Describe the issue
I think BTG should release 32-bit compiled executables in parallel to 64-bit to help people interested in setting up Pi3 full nodes.

### Machine specs:
- OS: Raspbian stretch lite
- Hardware: Raspberry Pi 3 Model B

**Comment by nhondong** [comment]
+1
I even would setup my Pi with the BTG Chain.

**Comment by wilsonmeier** [comment]
As soon as gitian build is in place all flavors (32bit, 64bit, arm, and so on) will be build and released. Stay tuned.

**Comment by kitotik** [comment]
FWIW I had built the 15.1 branch for rpi32 and was getting frequent crashes/OOM kills when running on an rpi 2 b+. I suspect an rpi3 would handle it just fine.

**Comment by h4x3rotab** [comment]
Libsodium and Equihash may introduce extra memory usage. However I don’t
have a rpi to test. It’s time to buy one, lol.

**Comment by wigy-opensource-developer** [comment]
Let me do a shameless plug here. http://libertaria.world/project/titania/

Since RPI does not have a decent GPU, do you think it would have a chance to mine blocks? If so, we would package it.

**Comment by h4x3rotab** [comment]
We have synced two full node instances. One is rpi2 another one is rpi3.

@wigy-opensource-developer That's awesome! We always want more people to easily access to Bitcoin Gold. Please don't hesitate to ask for help if needed :)
