### ISSUE TITLE
Extract Bitcoin Gold from a 2fa Electrum Wallet

### ISSUE THREAD

**Issue by JaydenClayton5** [BTCGPU/BTCGPU#243]
I'm offering a service, I'll take only 5% of the recovered BTG for this, it's a bit complicated and requires a lot of time, that's why I ask a fee, but it's doable, I will take care of everything, if you are interested hit me a PM or add me on Skype: jayden82@greenmail.net

I suggest you to do this as fast as possible, before BTG actually fails, as everyone are saying sell ASAP, so contact me and I'll take care of you
You won't even need to download the entire blockchain of the BTG Core Wallet, I will send BTG to a Coinomi wallet of yours if you wanna hodl them or to an exchange if you wanna sell them (if you are not pratical I can help with this too, don't worry).

P.S. **Before you do this, you have to empty your Bitcoin Wallet from Bitcoin sending them to a brand NEW wallet, same with Bitcoin Cash, send them to a new Electron or another BCH wallet, so when you have to extract the BTG the wallet has to be empty from BTC and BCH**

**Comment by wilsonmeier** [comment]
To everyone: Stay away from such obvious scam attempts. The account was created 10 minutes ago.

**Comment by JaydenClayton5** [comment]
What does that mean? I know how to extract BTG from Electrum 2fa wallet, it's a doable thing, so I created an account to offer the service to the ones who can't do it and to not let them lose their BTG and allow them to sell them while they can, so who cares when I created the account? What reasoning is that? I don't see any point

**Comment by h4x3rotab** [comment]
Advertising is prohibited. And again, anyone shouldn’t give out the private key to not fully trusted parties.
