### ISSUE TITLE
Ubuntu Install Problem

### ISSUE THREAD

**Issue by zottirik** [BTCGPU/BTCGPU#245]
### Can you reliably reproduce the issue?

I couldn't install on Ubuntu 16.04. 

#### If so, please list the steps to reproduce below:
./autogen.sh
./configure
make
make install

### Expected behaviour
Tell us what should happen

### Actual behaviour

Making install in src
make[1]: Entering directory '/root/BTCGPU/src'
make[2]: Entering directory '/root/BTCGPU/src'
make[3]: Entering directory '/root/BTCGPU'
make[3]: Leaving directory '/root/BTCGPU'
make[3]: Entering directory '/root/BTCGPU/src'
make[4]: Entering directory '/root/BTCGPU'
make[4]: Leaving directory '/root/BTCGPU'
 /bin/mkdir -p '/usr/local/bin'
  /bin/bash ../libtool   --mode=install /usr/bin/install -c bgoldd bgold-cli bitcoin-tx test/test_bitcoin bench/bench_bitcoin '/usr/local/bin'
libtool: install: /usr/bin/install -c bgoldd /usr/local/bin/bgoldd
libtool: install: /usr/bin/install -c bgold-cli /usr/local/bin/bgold-cli
libtool: install: /usr/bin/install -c bitcoin-tx /usr/local/bin/bitcoin-tx
libtool: install: /usr/bin/install -c test/test_bitcoin /usr/local/bin/test_bitcoin
libtool: install: /usr/bin/install -c bench/bench_bitcoin /usr/local/bin/bench_bitcoin
make[3]: Leaving directory '/root/BTCGPU/src'
make[2]: Leaving directory '/root/BTCGPU/src'
make[1]: Leaving directory '/root/BTCGPU/src'
Making install in doc/man
make[1]: Entering directory '/root/BTCGPU/doc/man'
make[2]: Entering directory '/root/BTCGPU/doc/man'
make[2]: Nothing to be done for 'install-exec-am'.
 /bin/mkdir -p '/usr/local/share/man/man1'
 /usr/bin/install -c -m 644 bitcoind.1 bitcoin-cli.1 bitcoin-tx.1 '/usr/local/share/man/man1'
make[2]: Leaving directory '/root/BTCGPU/doc/man'
make[1]: Leaving directory '/root/BTCGPU/doc/man'
make[1]: Entering directory '/root/BTCGPU'
make[2]: Entering directory '/root/BTCGPU'
make[2]: Nothing to be done for 'install-exec-am'.
make[2]: Leaving directory '/root/BTCGPU'
make[1]: Leaving directory '/root/BTCGPU'

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of bitcoin-core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.

### Machine specs:
- OS: Ubuntu 16.04.3 x64
- CPU: 16 Core
- RAM: 16 GB
- Disk size: 240 GB
- Disk Type (HD/SDD): SSD

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by wilsonmeier** [comment]
I don't see an error message in your pasted output.
If you are not building as root you need to use `sudo make install`
Please attach full build output if using sudo doesn't solve your problem.

**Comment by zottirik** [comment]
I run this:
sudo make install

Response:
Making install in src
make[1]: Entering directory '/root/BTCGPU/src'
make[2]: Entering directory '/root/BTCGPU/src'
make[3]: Entering directory '/root/BTCGPU'
make[3]: Leaving directory '/root/BTCGPU'
make[3]: Entering directory '/root/BTCGPU/src'
make[4]: Entering directory '/root/BTCGPU'
make[4]: Leaving directory '/root/BTCGPU'
 /bin/mkdir -p '/usr/local/bin'
  /bin/bash ../libtool   --mode=install /usr/bin/install -c bgoldd bgold-cli bitcoin-tx test/test_bitcoin bench/bench_bitcoin '/usr/local/bin'
libtool: install: /usr/bin/install -c bgoldd /usr/local/bin/bgoldd
libtool: install: /usr/bin/install -c bgold-cli /usr/local/bin/bgold-cli
libtool: install: /usr/bin/install -c bitcoin-tx /usr/local/bin/bitcoin-tx
libtool: install: /usr/bin/install -c test/test_bitcoin /usr/local/bin/test_bitcoin
libtool: install: /usr/bin/install -c bench/bench_bitcoin /usr/local/bin/bench_bitcoin
make[3]: Leaving directory '/root/BTCGPU/src'
make[2]: Leaving directory '/root/BTCGPU/src'
make[1]: Leaving directory '/root/BTCGPU/src'
Making install in doc/man
make[1]: Entering directory '/root/BTCGPU/doc/man'
make[2]: Entering directory '/root/BTCGPU/doc/man'
make[2]: Nothing to be done for 'install-exec-am'.
 /bin/mkdir -p '/usr/local/share/man/man1'
 /usr/bin/install -c -m 644 bitcoind.1 bitcoin-cli.1 bitcoin-tx.1 '/usr/local/share/man/man1'
make[2]: Leaving directory '/root/BTCGPU/doc/man'
make[1]: Leaving directory '/root/BTCGPU/doc/man'
make[1]: Entering directory '/root/BTCGPU'
make[2]: Entering directory '/root/BTCGPU'
make[2]: Nothing to be done for 'install-exec-am'.
make[2]: Leaving directory '/root/BTCGPU'
make[1]: Leaving directory '/root/BTCGPU'

Then I run:
bgoldd

Response:
bgoldd: crypto/common.h:138: int init_and_check_sodium(): Assertion `crypto_sign_verify_detached(sig, message, sizeof(message), pk) != 0' failed.
Aborted (core dumped)

What can I do?

**Comment by wilsonmeier** [comment]
See https://github.com/BTCGPU/BTCGPU/issues/43

**Comment by h4x3rotab** [comment]
Please close the issue if your problem is solved.

**Comment by shakilmia** [comment]
thanks
