### ISSUE TITLE
[TUTORIAL] How to get Bitcoin Gold from a 2fa Electrum Wallet [Step by Step]

### ISSUE THREAD

**Issue by ApproximateSunlight** [BTCGPU/BTCGPU#246]
Here it is a easy step by step tutorial to claim your Bitcoin Gold from a 2fa Electrum Wallet without giving your private keys or seeds to anyone!

https://bitcointalk.org/index.php?topic=2550529.0

It may seem difficult but it's not but it requires time, enjoy!

**Comment by Ayms** [comment]
Take care, read https://github.com/BTCGPU/BTCGPU/issues/238#issuecomment-350555210

**Comment by wilsonmeier** [comment]
Word of advice:

Please always use extreme caution by using such tools.
Move your BTC into a new wallet before exposing your private keys.
Yes this costs you some network fees but it will save your BTC in case of private key leak or scam activities.

**Comment by Ayms** [comment]
See https://github.com/BTCGPU/BTCGPU/issues/238#issuecomment-352520892

https://github.com/Ayms/bitcoin-transactions ready with multisig support/Electrum wallets

**Comment by gkrizek** [comment]
@ApproximateSunlight Thank you for the tutorial it's very helpful! I'm getting an error that I can't figure out!

I am to the step where I open the Console in the Bitcoin Gold client. I'm able to create a transaction with the given command, but I'm not able to sign the transaction with my first key. I just get:

```
Error: std::bad_alloc
```

Do you know what I'm doing wrong? I've checked my command a thousand times and tried variations of it but it gives that message every time.

Here is an example of my command with sensitive information removed.

```
signrawtransaction '0200000001053728f82873c1405a487c6afa00b42a778e8141e2e35a44332db91c853fc7a900000000000000000001d83bcf08000000001976nabsdf76sdf873897vbcxv7868540ba445b7b6c74098b1be64c88ac00000000' '[{"txid":"a9c73f851cb767869786766873e241818e772ab400fa6a7c485a40c17328f8283705","vout":1,"scriptPubKey":"a914035987687697869876984efbae1f006a9e87","redeemScript":"522102dfaef50c6dfc288760960b10bb7868685764754e7974e1e827a159290a8f1210311d6b4b57f2082e0b247225e8f82bb4a29016d1da40c9730830f38450881588f210358579e4fbb25be1ebca5b3eb962ef7d2396817609889670896098bbca098789786e5ae253ae","amount":"15555550"}]' '["bacbabcdbebdbqYMLURh7HMBCRAVfskaucp467565876vv87687c876wQYYXZC4"]'

```

**Comment by Ayms** [comment]
You can consider trying this tool: https://github.com/Ayms/bitcoin-transactions

Much easier and at least it will tell you what is wrong

**Comment by Ayms** [comment]
After a quick look different things are wrong: tx a973... does not exist and amount should be in BTC not satoshis (so probably 0.15555550)

**Comment by gkrizek** [comment]
@Ayms  Thanks for the suggestion. I'll check out that tool to see if it's any easier.

You are right about the transaction. All that data in my example command is fake. I replaced _all_ data with dummy data, but left the command the same.
