### ISSUE TITLE
Looking for BTG address validator written in PHP

### ISSUE THREAD

**Issue by c0deright** [BTCGPU/BTCGPU#249]
Is there a library alike the existing ones for BTC?

I'm hoping to not have to setup a bgoldd daemon just for `validateaddress` RPC call

**Comment by h4x3rotab** [comment]
I think most of the Bitcoin libraries have the ability to validate address. The only difference is the version byte is different with Bitcoin.

I've modified coin.bin to support BTG address conversion and validation: https://github.com/h4x3rotab/coinbin/commit/c691ec72a1199f0d2b4695fc21b77a988f890cf0

And later a bug has been fixed: https://github.com/h4x3rotab/coinbin/commit/606c6a2bb40f12903b0613c8b7d3196a4a13f825

Validate and decode address:
```js
var d = coinjs.addressDecode('address', coinjs.constBitcoinGold);
```

Conver between BTG and BTC:
```js
var btc_addr = coinjs.addressConvert('btg-address', 'btg', 'btc');
var btg_addr = coinjs.addressConvert('btc-address', 'btc', 'btg');
```

**Comment by c0deright** [comment]
Thank you, I crawled git commits and finally found https://github.com/BTCGPU/BTCGPU/blob/master/src/chainparams.cpp#L175 where the new values for `PUBKEY_ADDRESS` and `SCRIPT_ADDRESS` are used.

So the validator I have for BTC was easily modified for a BTG version.

How about testnet addresses? I guess the testnet addresses format didn't change, right?

**Comment by h4x3rotab** [comment]
No, we didn’t change the version for testnet.

**Comment by h4x3rotab** [comment]
Please close the issue if you don't have more questions :)
