### ISSUE TITLE
nibiru pool closed, switched to eu.pool.gold

### ISSUE THREAD

**Issue by snofte** [BTCGPU/BTCGPU#250]
Lost all work in nibirupool.  Have swithced to eu.pool..gold.  Wallet is btg core.  Miner is Claymore AMD gpu for zcash/btg.  How/where can I se my earnings ?

**Comment by wilsonmeier** [comment]
If the pool did payout anything to you it should be in your synced wallet.

**Comment by StarbuckBG** [comment]
Hello!

The earned on z-nomp based pools are on workers statuses - https://mine.pool.gold/workers <https://mine.pool.gold/workers> .
If the pool is closed they should have paid your earnings already.

**Comment by wilsonmeier** [comment]
@snofte did you receive your earnings? Can this ticket be closed?

**Comment by snofte** [comment]
yes, ok to close ticket
