### ISSUE TITLE
Help! Can't start BitcoinGold Core

### ISSUE THREAD

**Issue by k1184** [BTCGPU/BTCGPU#253]
Can't start BitcoinGold wallet. Who can help me? What is this? See attached file.
![screenshots](https://user-images.githubusercontent.com/25074782/34178977-32b28066-e51a-11e7-8999-00733fbe24ad.PNG)

**Comment by wilsonmeier** [comment]
@k1184 thanks for reporting.
Could you please provide more information:

OS Version
New installation or Re-Install
First or subsequent run
Did you change the config file (if so, please attach it)

Thank you

**Comment by k1184** [comment]
Thanks for reply.
Here the details.
OS Microsoft Windows 10 Pro
Intel Core(TM) i5-3337U CPU @ 1.80GHz 1.80GHz
RAM 6GB

I have tried to copy blocks folder from another PC running Windows 10 Pro. After coping I received such error. I have tried fresh install to another folder. No result yet.

**Comment by wilsonmeier** [comment]
I would suggest to remove the copied folder and try again. Seems the block folder contains corrupted data.

> I have tried fresh install to another folder. No result yet.
By "No result yet" you mean?

**Comment by k1184** [comment]
Thanks. I just deleted the folder and BTG started. Thanks for Reply!

**Comment by wilsonmeier** [comment]
You're welcome. 
Please close the issue.

Thank you.

**Comment by k1184** [comment]
Thanks again. The issue is resolved.

**Comment by wilsonmeier** [comment]
To be honest, i never used the torrent but the procedure should be straight forward.

Download the boostrap.dat and use the "-loadblock=/path/to/bootstrap.dat" option to start the bitcoin gold client.

**Comment by h4x3rotab** [comment]
I think moving the bootstrap.dat to the datadir is sufficient. The client will load block from the disk instead of downloading from the network.

**Comment by k1184** [comment]
I have tried but no result.
