### ISSUE TITLE
Why is bitcoin gold block size only 1M ?

### ISSUE THREAD

**Issue by Marc477** [BTCGPU/BTCGPU#255]
Wouldnt the same problem than bitcoin happen? Getting huge amount of fees and slow transactions just because you decided to keep the block size at 1M?  Why not 8M like BCH or higher ?

How will BTG handle huge transaction volume and keep low fees when it becomes more mainstream ?

Thanks.

**Comment by h4x3rotab** [comment]
We don’t have bigger block size because it’s not needed currently.

BTG follows Bitcoin Core roadmap to scale the blockchain. We will introduce
Lightning and side chains to not only increase the throughputs but also
reduce the latency of the transactions. But anyway, when necessary we will
be happy to increase the block size directly by a fork.

BTW, Bitcoin Gold has the lowest tx fee: BTG 0.005 usd vs BCH 0.025 usd
Chart:
https://bitinfocharts.com/comparison/median_transaction_fee-bch-btg.html

**Comment by Marc477** [comment]
Well actually BCH is worth 10x more than BTG, but the fees are only 5x higher, which means the BTG fees are x2 higher than BCH.  And this is without checking the volume they have 10x more transactions going on. 

I believe in BTG for its decentralized nature, but im just worried that it may become unusable like bitcoin legacy is right now (5-6 hours + 20$ for a transaction).  So I would like to see a clear roadmap on scaling from BTG.

**Comment by h4x3rotab** [comment]
IMHO there's not need to worry. In the first release of our roadmap, we've planned the direct block size increment when the block becomes full.

**Comment by talhaishtiaq** [comment]
Hi,
how to fork from your code?

**Comment by shakilmia** [comment]
@h4x3rotab

**Comment by talhaishtiaq** [comment]
@shakilmia Hi
Where is the max block size int his repo

**Comment by wigy-opensource-developer** [comment]
@talhaishtiaq Do not fork your own crytocurrency if you cannot find it in the source code. This is a huge C++ code base and you will need to maintain all security issues in your fork too. Not doing so is irresponsible towards the users of your fork.

**Comment by talhaishtiaq** [comment]
I already have forked and it is mining now

**Comment by eqjjh** [comment]
The link to the new roadmap (https://bitcoingold.org/wp-content/uploads/2018/01/BTG-Timeline-2018.jpg) should be linked from the https://btcgpu.org/ website, which still links to the old one. According to that, lightning network will be implemented in Q2 of 2018? 
No mention of block size there.

**Comment by h4x3rotab** [comment]
Block size change is never in the roadmap because we can do it whenever it's necessary. It will be described in the upcoming whitepaper. BTW, the link to the roadmap on bitcoingold.org is https://bitcoingold.org/roadmap-2018/. Do you mean another link?

**Comment by eqjjh** [comment]
The link at the bottom of the page, bitcoingold.org, in the "About" section does not link there. Yesterday it linked to the old PDF roadmap. Now it does not go anywhere.
