### ISSUE TITLE
How i can return stolen (evacuated by BTG Team) coins ?

### ISSUE THREAD

**Issue by feofan-altos** [BTCGPU/BTCGPU#256]
Hello !
BTG Team Support does not answer me.
From my wallet coins were lost - they were evacuated.
How do I get coin back ???
my wallet https://btgexp.com/address/GX4wntkpnSKE2WzztLy8zFr4Lffw42PmGW

This situations was described in the blog https://bitcoingold.org/vulnerable-wallets/

P.S. My coins were sent from my address to someone else's address and now I can not return them back. At first I thought they were stolen. Now the developers wrote that they hid the coins from the thief, so that he did not take them away.
Ok, but how do I get them back?

**Comment by MentalNomad** [comment]
There was some initially some confusion. When the team first reached out to feofan-altos to begin addressing the issue, there was some fear about our authenticity.

We are now working directly with feofan-altos to establish his ownership of the coins and to return them.
