### ISSUE TITLE
Bitcoin private keys data file is recognised by Bitcoin gold

### ISSUE THREAD

**Issue by StarbuckBG** [BTCGPU/BTCGPU#26]
### Describe the issue
Upon starting the daemon there is an error message that says "Error loading wallet.dat: Wallet requires newer version of Bitcoin Gold"
#### If so, please list the steps to reproduce below:
1. Build source
2. start bitcoind

### Expected behaviour
Tell us what should happen
Wallet.dat must be different that Bitcoin's wallet.dat

### What version of bitcoin-core are you using?
- 4f33ac1 

### Machine specs:
- OS: MacOS

**Comment by StarbuckBG** [comment]
Fixed in 5c123e7

**Comment by h4x3rotab** [comment]
Should we change the version of wallet file and maybe also all the database?
