### ISSUE TITLE
3rd party clients & libraries integration for the various applications

### ISSUE THREAD

**Issue by ghost** [BTCGPU/BTCGPU#264]
C++: bitcoin-core : BTCGPU
Python: electrum: ???
Java: bitcoinj: ???
Go: btcd: ???

I think we need a multiple clients based on these multiple languages.

**Comment by h4x3rotab** [comment]
Definitely yes! Don't forget BitcoinJS and also utilities like BitCore, coin.bin, etc.

Let's list all the popular Bitcoin implementations, libraries and utilities here.
