### ISSUE TITLE
Fix wrong hashrate estimation in GetNetworkHashPS

### ISSUE THREAD

**Issue by h4x3rotab** [BTCGPU/BTCGPU#265]
The current implementation of `GetNetworkHashPS` doesn't work any more because it assumes the difficulty adjusts per 2016 blocks, which is not the case for Bitcoin Gold:

https://github.com/BTCGPU/BTCGPU/blob/d5522ed66a924a2d505fe45ed2487e741c6c0917/src/rpc/mining.cpp#L59-L61

However this doesn't affect any PRC

**Comment by martin-key** [comment]
@h4x3rotab is this still happening ?

**Comment by h4x3rotab** [comment]
Not a big problem but it's not accurate

**Comment by h4x3rotab** [comment]
Fixed by #385
