### ISSUE TITLE
transaction is pending for over 3 weeks - wallet adress changed

### ISSUE THREAD

**Issue by FrankDaniel** [BTCGPU/BTCGPU#266]
This issue tracker is only for technical issues related to bitcoin-gold.

Hello,

please be so kind to help me with this issue.

the support from ledger nano s cannot help me, i tried a few times

Issue:

Abaut 3 weeks ago i splitted my bitcoin account on ledger nano s to get bitcoin gold 4,69 coins.

After that i made a new account for bitcoin gold and sended all my 4,69 coins to the new bitcoin gold account.
I thought at his time, that it would be better for secure my wallet.

After that - my old account for bitcoin gold doesnt exist anymore and the coins didn t arrived at the new account.

have a look, please:

http://btgexp.com/tx/374e596d0f9cef7c2f794c2f23fb27da6dc646d25658a91a4f116b72b4a3ff26

My wallet adress for bitcoin changed also:

Before: 1DWXAD8g9tE82aMMAuvLzzCzEM1xD2vQEM

new wallet bitcoin: 12mTXC2Ydf8VUnEVDuQcx1Bra8vUxPgAH9

my wallet adress for bitcoin gold:
GWGvKUR16z6MGDM1YVBrjtZw1M8Fqp4gua

Now, i got over 5400 confirmations, but coins didn t arrived, yet.

Please help me, 4,69 bitcoin gold coins are a lot of money for me.

thank you

best regards

Frank Daniel

**Comment by h4x3rotab** [comment]
Looks like the problem is not the stuck transaction - it has been confirmed
by the network for a long time. Are you using Ledger to receive the coins?
It should display the balance in the address you sent to if you have the
control over it. Otherwise it may not get synced for some reason or you
didn’t set up it correctly.

**Comment by wilsonmeier** [comment]
@FrankDaniel Ledger supports claiming BTG. Did you follow the article on Ledger Zendesk (https://ledger.zendesk.com/hc/en-us/articles/115005456969-How-to-install-and-use-Bitcoin-Gold-with-your-Ledger-device)?

**Comment by FrankDaniel** [comment]
Dear h4x3rotab,
thank you, I was setting up correctly. Just after that i created a new bitcoin gold adress on ledger nano s. And then my bitcoin wallet adress and bitcoin gold wallet adress changed. Maybe the new bitcoin gold wallet wasn t fully sync ?

**Comment by FrankDaniel** [comment]
Dear wilsonmeier,

thank you for you help.
I think i followed the article correctly.
