### ISSUE TITLE
Lost coin 

### ISSUE THREAD

**Issue by Hrncek55** [BTCGPU/BTCGPU#267]
Hello,

### Describe the issue

1. I created Guarda Bitcoin Gold wallet as u recommended on your official website.
2. I sent there 1.40757021 BTG from https://changenow.io 
3. The app closed for a while (don't know why) and I can't join back. I could just create a new wallet. On support told me they won't help me because I do not copy their password. It's not their problem app fell down and I can't copy the password and I lost my money.

### Expected behaviour
I want to have access to my BTG.

### Actual behaviour
The Guarda Bitcoin wallet app fell down and I lost access to my BTG not by my misstake.

Could u please help me? Why do you recommend wallets like this on your website?
![changenow transfer](https://user-images.githubusercontent.com/34939497/34437561-a228b37a-ec9f-11e7-933f-181025d8f4b8.jpg)

**Comment by Ayms** [comment]
What is your problem exactly? If you have in your wallet the address GSriVJ19ZFSegj7BiVqtyJZncPUa4WbGNr (ie if you have the private key corresponding to this address), then you can "access" your coins

You might consider using https://github.com/Ayms/bitcoin-transactions instead of dubious wallets

**Comment by tnkmt** [comment]
If I understand correctly the user does not have control of the address GSriVJ19ZFSegj7BiVqtyJZncPUa4WbGNr because the app crashed.

Maybe there is a file with the private key on the phone memory. If the amount is not small I recommend to turn off your phone and give it to a data recovery specialist. I suppose it's safe to remove the SIM card and use it on another phone.

**This is example why we should backup our wallets before to use them.**

**Comment by Hrncek55** [comment]
exactly, I was just zealous becouse want get BTG fast. And after the app
crashed and closed and kicked me from the app. I was just angry becouse you
recommend the unstable wallet on your official website.

The amount was not so big  about 330 eur in this time. But if I lost the
money becouse value of BTG could fall down it is more likly for me as lost
it becouse of unstable wallet.

I think the wallets witch is published on official web site could be
garanted. But  unfortunately they are not.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Bez
virů. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2018-01-29 2:21 GMT+01:00 tnkmt <notifications@github.com>:
