### ISSUE TITLE
cant receive my coins. 

### ISSUE THREAD

**Issue by Stetto** [BTCGPU/BTCGPU#268]
Hi, at the time of fork on 24th october i had some Bitcoins in my wallet.

I sold them BTC on 20th december.

Today i want to receivce my BTG, but the tools say my wallets / privates keys are emptys ..

so far, this is true, my BTC are sold / gone - but the fork is a full snapshot at the time of 24th october and after that had its own transactions - isn't it?

Also there should stay my BTG on this keys, but where are them? How can i claim this coins?

Thank you very much and a happy new year

For examples on this adresses where bitcoins since 7th october before the fork until 20th december .... so i think they should available as bitcoin gold, but i can't claim them. Why?? What i am doing wrong

https://blockexplorer.com/address/12zrr6bG1fBGHRKCTTuHF1J3KngGDb21MQ
https://blockexplorer.com/address/1CGoNxhLZa1o33sK9UTUtM2L4EtsM46RbG
https://blockexplorer.com/address/1BbaS7CqDy7ubqTMSi2a6Hnpx7ksMg7qR6
https://blockexplorer.com/address/18Q2Xtmq28u4wFqxAT69ep8oBE6KcBJPSr

**Comment by wilsonmeier** [comment]
Hi @Stetto,

could you please tell us in what wallet you have held your BTC and how you tried to claim your BTG?

Thx

**Comment by Stetto** [comment]
Hi,

 

it was a bit confusing to me, to find my coins in the BTG Blockchain. After i found a BTC>BTG Adressconverter and importet my private keys to BTG Core Wallet, everything is fine.

 

Thank you for your reply!

 

 

Gesendet: Dienstag, 02. Januar 2018 um 12:01 Uhr
Von: wilsonmeier <notifications@github.com>
An: BTCGPU/BTCGPU <BTCGPU@noreply.github.com>
Cc: Stetto <stephan.handke@gmx.net>, Mention <mention@noreply.github.com>
Betreff: Re: [BTCGPU/BTCGPU] cant receive my coins. (#268)


Hi @Stetto,

could you please tell us in what wallet you have held your BTC and how you tried to claim your BTG?

Thx
