### ISSUE TITLE
Where is the 0.15.0.2 changelog?

### ISSUE THREAD

**Issue by c0deright** [BTCGPU/BTCGPU#276]
https://github.com/BTCGPU/BTCGPU/releases/tag/v0.15.0.2 states

> Please visit https://bitcoingold.org for changelog

But on https://bitcoingold.org/downloads/ there is no such thing as a changelog.

EDIT: a blog is not the right place for a changelog!

> https://bitcoingold.org/bitcoin-gold-wallet-v0-15-0-2-release/

Please use github or the download section on the homepage but *not* a blog as the only source for the changelog...

**Comment by h4x3rotab** [comment]
Moved to wiki page:
https://github.com/BTCGPU/BTCGPU/wiki/Changelogs#v01502

Also changed the description in the release page. Thank you for reporting the issue!

**Comment by shakilmia** [comment]
ps://github.com/blockchain/My-Wallet-V3/blob/master/src/hd-account.js#L311

**Comment by shakilmia** [comment]
not sport
