### ISSUE TITLE
estimate time left 3 week and need more space

### ISSUE THREAD

**Issue by aahmadrezaa** [BTCGPU/BTCGPU#277]
hello dear admin

i need only bitcoin gold wallet but after download your app see complicated process  , and my bitcoin gold not received because say me need complete sync and estimate time is very long !!
how can help me to enjoy your application .
please check my problem

thank you for supporting

**Comment by h4x3rotab** [comment]
Full node is the infrastructure of Bitcoin Gold. It has to receive a full blockchain before you can use it to spend your coins. This is the same for Bitcoin (Bitcoin Core) and all the cryptocurrencies. However if you just need to import the privkey to access your coins, maybe light wallets like Coinomi is better for your use case. Electrum is an awesome SVP wallet that fits your need and we are currently actively working on it.

**Comment by h4x3rotab** [comment]
BTW, if you don’t mind the size of the full blockchain (~140G), you can download our bootstrap.dat file to save the time to download the chain. However you still need a few hours to fully validate he blockchain.

**Comment by aahmadrezaa** [comment]
140gig is very , i need only wallet and now already I sent my bitcoin gold to your wallet , how can see my balance and transfer my bitcoin gold to simple wallet , i dont have a space for 140gig , and i need my bitcoin gold , and can’t find bootstrap.dat this file , please help me and check my problem :(
Thank you for supporting

**Comment by aahmadrezaa** [comment]
https://btgexp.com/address/GYM6EzmbF9YxVU7GASzeZf2cQs5w2YEnET

**Comment by aahmadrezaa** [comment]
I very confused , i echange my bitcoin to bitcoin gold with changelly and in address bitcoin gold type my bitcoingold.org app received address , after exchanging , app say me you can’t see your balance because you should download 140gig all blockchain , an I haven’t space for this download in the laptop , i say everyone how can fix this without download say me you can see your balance and transfer with your app COINOMI in android and i downloaded your app , but I don’t know how can set my bitcoingold.org wallet in your wallet , anyone’s can help me to fix this problem !!!!

**Comment by tnkmt** [comment]
I think you can use pruning.

I suppose it will work if you set `prune=550` in your .conf file and then restart the daemon. This way it will keep only 550MB of the blockchain. You can increase this number for more security (for example, 2000MB), but I think that it's safe even with 550.

Now I am building my software and will use this setting.

I do not recommend to use different wallets, because there are many scams out there. See for example: https://github.com/BTCGPU/BTCGPU/issues/281
