### ISSUE TITLE
[Open Configuration File] button has wrong title and target

### ISSUE THREAD

**Issue by ZhiKosta** [BTCGPU/BTCGPU#278]
![bug-core-wallet](https://user-images.githubusercontent.com/33158037/34923749-59787f6a-f9a7-11e7-8691-c3be6a532bf1.jpg)

windows 10 x64

[Open Configuration File]
1. The title of the button (%1)
2. The target of the button is bitcoingold.conf which is not the one located in 
C:\Users\<username>\AppData\Roaming\BitcoinGold\
Secondary config? where it is located? how it was created?

**Comment by MentalNomad** [comment]
Error does not appear in current version(s).

Closing.

![image](https://user-images.githubusercontent.com/34785888/89239735-09a1de00-d5c8-11ea-8d87-844d5bd7bdca.png)
