### ISSUE TITLE
ElectronGold.org is a phishing website! Their "wallet" will steal your coins!

### ISSUE THREAD

**Issue by tnkmt** [BTCGPU/BTCGPU#281]
Please make announcement on the BitconGold.org website that ElectronGold is a phishing "wallet".

Proof: https://github.com/fyookball/electrum/issues/280

**Comment by h4x3rotab** [comment]
It was added to the scam list one month ago: https://bitcoingold.org/not-official-websites/

**Comment by tnkmt** [comment]
It's not visible enough. When browsing the bitcoingold.org I did not found it. There should be a warning on the front page somewhere.

**Comment by h4x3rotab** [comment]
Our Electrum is called ElectrumG: https://bitcoingold.org/electrumg-spv-bitcoin-gold/
