### ISSUE TITLE
Feature Request: Watch Only Wallet

### ISSUE THREAD

**Issue by ImmortalJ** [BTCGPU/BTCGPU#286]
It would be nice to see a Watch Only Wallet using public key feature added to the official client, it would good for offline cold storage. Some of us are paranoid.

**Comment by h4x3rotab** [comment]
Does this work for you?
https://www.reddit.com/r/Bitcoin/comments/5z35nm/watchonly_wallet_in_bitcoin_core_qt/

**Comment by ImmortalJ** [comment]
It did indeed! I had no idea that option existed.

Thanks!
