### ISSUE TITLE
Importing private keys on pruned node - not working?

### ISSUE THREAD

**Issue by tnkmt** [BTCGPU/BTCGPU#292]
When trying to import private keys on a pruned node it gets error:

    Rescan is disabled in pruned mode

So, it's not working.

Is there a workaround? Can I transfer my coins from the old addresses without downloading the entire blockchain (without relying on third party wallets like exodus.io)?

I know that out there is full of scams and I don't trust other wallets (example: [ElectronGold.org is a phishing website](https://github.com/BTCGPU/BTCGPU/issues/281)).

**Comment by caeepupunha** [comment]
stratum is confiable

**Comment by h4x3rotab** [comment]
ElectrumG is our official light wallet which is usable.

Pruned node can't import keys. So you need to import the key before you prune the node. This is by design.
