### ISSUE TITLE
BTG QT wallet crash when starting with "-txindex"

### ISSUE THREAD

**Issue by user78713** [BTCGPU/BTCGPU#295]
Steps to reproduce:
1. Start wallet with "C:\Program Files\BitcoinGold\bitcoin-qt.exe" -datadir=d:\BitCoinGoldData -Server -txindex
2. Let it sync for a while
3. At some point (38.12% sync, after that it stalls), the wallet just stop syncing, without any error message
4. Close the wallet (press the "X")
5. Error appears "Error: A fatal internal error occurred..."

I 7-Zipped and uploaded the error.log, can be downloaded from [https://ufile.io/68ewh](url)

### Expected behaviour
Wallet should sync, and I should be able to use "getrawtransaction" from debug console

### Actual behaviour
Wallet stalls and then just crash when I close it

### Screenshots.

Wallet stall phase:
![btg_wallet_stalls](https://user-images.githubusercontent.com/35986442/35735376-316ff784-082d-11e8-99e6-f8428bb1138c.jpg)

Wallet crashing once I close it:
![btg_wallet_crash](https://user-images.githubusercontent.com/35986442/35735375-314d3ef6-082d-11e8-8cde-92d5b21fa122.jpg)

### What version of bitcoin-gold are you using?
v0.15.0.2 (64 bit)

### Machine specs:
- OS: Windows 10 x64
- CPU: Intel i5 4210U
- RAM: 8GB
- Disk size: 128GB SSD , but wallet data is stored on portable 1TB HDD

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by user78713** [comment]
Note that I tried to delete all files under "d:\BitCoinGoldData" and let it sync again. The issue was reproduced again. I don't recall if it crashed at the same progress percent like first time, but I guess that you have enough info to investigate it now.

**Comment by h4x3rotab** [comment]
Sorry for the late reply. Looks like some problem related to the database. Did it get stuck at the same percentage? Did you use bootstrap.dat or download from scratch?

**Comment by user78713** [comment]
It got stuck 2 times. I did not collect data from the first time so I don't recall at which percentage did it pause. Also, in both times, I started from scratch.
