### ISSUE TITLE
testnet hung forever , any faucet?

### ISSUE THREAD

**Issue by kiahmed** [BTCGPU/BTCGPU#300]
trying to have a btg test node up for some integration testing , but its hung forever with testnet option as it seems like can't find any other peer. Is there any active testnode out there I can add manually ?

Also, would like to have some test coins ..any active faucet anybody knows of ?

#### If so, please list the steps to reproduce below:
1. just change the config to testnet 

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of bitcoin-gold are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.

### Machine specs:
- OS:
- CPU:
- RAM:
- Disk size:
- Disk Type (HD/SDD):

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by kiahmed** [comment]
none of these worked
addnode=btg.dnsseed.minepool.gold
addnode=46.101.153.138
addnode=eunode.pool.gold
addnode=asianode.pool.gold

**Comment by h4x3rotab** [comment]
Please keep an eye on #296. When it's merged, we will reset testnet asap.

**Comment by kiahmed** [comment]
any faucet yet or tescoin yet?

**Comment by wilsonmeier** [comment]
See https://github.com/BTCGPU/BTCGPU/wiki/Testnet-v3
