### ISSUE TITLE
bitcoin-qt not working

### ISSUE THREAD

**Issue by sapirx3** [BTCGPU/BTCGPU#301]
i sent my 2 btg from exodus to bitcoin wallet core (from offical site) and it take to much time (6 hour)and still didn't finish
it's downloaded block i don't know why and then stuck after 6 hour from transference
so i exit from this wallet and try to enter again
and i get this error:

assertion faild!
program: C:\Program Files\BitcoinGold\bitcoin-qt.exe
file chain.cpp, Line 101
Expression: pindexWalk ->pprev

ohh and i moved C:\Users\sapir\AppData\Roaming\BitcoinGold\blocks  **to**  E:\Block
becuse it was 60-70 gb and i don't have more space in C..

someone know what is the problem?
Or how I get my privet key?

tnx in advance

**Comment by ZhiKosta** [comment]
Hi There, did you move your files after the installation? BTG blockchain is currently around 140-150GB so you have some more syncing to do. Make sure you backup your wallet.dat This is where your private keys are. If you lose this files you lose your money. After you make a backup of this file, uninstall and re-install core wallet. In the installation process chose the new folder where you moved the blockchain data. Wallet will read what you have synced up until that point and continue to the last. You won't be able to see your coins until your wallet is 100% synced.

**Comment by wilsonmeier** [comment]
@sapirx3 is your issue resolved?
