### ISSUE TITLE
Testnet V3 explorer api. Cant broadcast Tx?

### ISSUE THREAD

**Issue by ofumbi** [BTCGPU/BTCGPU#306]
Im trying to send a raw tx. I always get this erro no matter how much fees I set. 
min relay fee not met. Code:-26
Could this be an issue with the testnet insight or am I doing something wrong.
details below.

Exception: Client Error > POST /insight-api/tx/send HTTP/1.1 User-Agent: GuzzleHttp/6.3.2 curl/7.52.1 PHP/7.1.6 Content-Type: application/x-www-form-urlencoded Host: test-explorer.bitcoingold.org rawtx=0100000002803ed286da343e3ac50809befcd6591ada9fde585a78ace2f8cad1716077094900000000fdfd0000483045022100b68302d3c9f860d118ec01417935271873cc87f892696121105369bfe35eb5080220529a900b7679d127caadbe2d0639207e858c8619b89039080a49d334c29fc76b4147304402201b058376707c66338ba535fe3b2e36e1813c8a088e563ceca195a8b54dffb72702206d791e7004f757844409d1fe8e75a07d125f1fed88608ddb7358604761d19614414c6952210255e2d63480d6bcf38edf2fe0ba778aba50cc174a40c0b542df24ad3e78a561cc2103491d10ed81f47208334295ac8e072acfd0a3fed710dbca4b1d87a328804ee84821036e54d8b2bfbc2ac86d4a11bbe3ce747a2af1b39c2e165d69053b16c3401f9cfd53aeffffffff4678d7a63dc32efe7635f061d53a2ea9674ed7a2c5f99b1e22047f298da1bac801000000fc004630430220624c7db622ee15ae72f50380f828237c5c280f16e5633c0f968f205754e7ed5b021f0804dede1aeea45ec651d028f73c9b09dec73b3971d4fec66e47a7ec8b0a3641483045022100d077ca5369ae490c836a5ca6ffa8e978a554dc7dffe47436cea712eb9bd8c923022034f1757ccf4be5a94677e36a5bbb8082c12fb915e25d8589632a32d6bf9f7bcf414c6952210255e2d63480d6bcf38edf2fe0ba778aba50cc174a40c0b542df24ad3e78a561cc2103491d10ed81f47208334295ac8e072acfd0a3fed710dbca4b1d87a328804ee84821036e54d8b2bfbc2ac86d4a11bbe3ce747a2af1b39c2e165d69053b16c3401f9cfd53aeffffffff02001bb7000000000017a9144cbd50379b66418293fe149dbb4999d2c1b7c5f6877d9a8f010000000017a914db621df6e25e9b35627822a50b86731ee89b9f358700000000 HTTP/1.1 400 Bad Request Server: nginx/1.10.3 (Ubuntu) Date: Mon, 02 Apr 2018 15:52:05 GMT Content-Type: text/html; charset=utf-8 Content-Length: 35 Connection: keep-alive X-Powered-By: Express X-RateLimit-Limit: 10800 X-RateLimit-Remaining: 10549 ETag: W/"23-UyaHoCKmaGjl8yX6+vcaZdtM0HI" Vary: Accept-Encoding Strict-Transport-Security: max-age=31536000; includeSubDomains 66: min relay fee not met. Code:-26 in /Applications/MAMP/htdocs/vendor/ofumbi/php-coin/src/ofumbi/Api/Providers/Provider.php on line 95
--

**Comment by h4x3rotab** [comment]
Looks like you are trying to spend two utxo:
```
4909776071d1caf8e2ac785a58de9fda1a59d6fcbe0908c53a3e34da86d23e80:0
c8baa18d297f04221e9bf9c5a2d74e67a92e3ad561f03576fe2ec33da6d77846:1
```

Both of them have 0.1 tBTG. But your outputs are:

```
ANmdnoKkMmN8tUA5JfhLTPofq9bMbfUhVX 0.12000000
AbmsAoRaoJj61HaXzt7jFjYFVSGgMv2tsy 0.26188413
```

which is more than inputs. How did you generate the transaction?
