### ISSUE TITLE
btgmine.pro problems

### ISSUE THREAD

**Issue by juanpc2018** [BTCGPU/BTCGPU#307]
there is No support with btgmine.pro,
https://btgmine.pro/#/about

forgive me, but this is the only logic place...

https://btgmine.pro/#/help

#1. The CPU Miner does Not work, but works with other pools. 
#2. i get many Lost connection with the server Errors using the latest NVIDIA Zec.Miner 0.3.4b.
but other coins/pools do not have that problem "is Not my internet."
#3. Links are outdated and do not link directly to the Miner Developer GitHub, where it should.
#4. using Bminer "another Nvidia Equihash miner", i get file errors from the server.
https://www.bminer.me/releases/

All concludes to: it must be the server.

**Comment by wilsonmeier** [comment]
I'm very sorry, but we can't do anything about it.
It's not under our control.
Try to reach out to them on other channels we definitely can't help you with that.

**Comment by h4x3rotab** [comment]
Please try to join our Discord and ask in #mining or #pool-ops channel. The operator of the btgmine.pro may be there.

https://discord.gg/HmVUU6S
