### ISSUE TITLE
Incorrect Network Id for BTG testnet

### ISSUE THREAD

**Issue by mjwaddell** [BTCGPU/BTCGPU#309]
### Describe the issue
The precompiled version of BTG core has the wrong testnet network Id.
https://bitcoingold.org/downloads/

The zipped source on the download page has the incorrect Id (0x456e48e1)
     https://github.com/BTCGPU/BTCGPU/releases/tag/v0.15.0.2
The Github source has the correct Id (0x456e48e2)
     https://github.com/BTCGPU/BTCGPU/blob/master/src/chainparams.cpp

### Can you reliably reproduce the issue? Yes
1. Install BTG core from download page.
2. Run core (bgoldd)
3. Send handshake request from any BTG client (I'm using NBitcoin)
4. BTG core log will show Invalid MessageStart

### Expected behaviour
Handshake request should complete

### Actual behaviour
In core, "INVALID MESSAGESTART" is logged due to incorrect network Id

### What version of bitcoin-gold are you using?
Zipped version claims to be 0.15.0.2. The Github commit Id is e803c163a680eeb49774f0bd9a24f6f3d7e5718b 

### Machine specs:
- OS: Ubuntu 16.04

**Comment by h4x3rotab** [comment]
You are correct. We have reset the testnet on March while the last release version was done a few months ago. The new testnet has launched with a brand new blockchain and network id. You need to compile your own client to join the testnet.

We will also try to make a new release in the near future. After that you will be able to join the new testnet with the release binary.
