### ISSUE TITLE
Testnet stopped at  height 9418

### ISSUE THREAD

**Issue by mabbas1975** [BTCGPU/BTCGPU#312]
The testnet stopped at height 9418 in 2018-05-01 no more after this block even when i checked the testnet explorer test-explorer.bitcoingold.org, what is the issue, did the test net changed

**Comment by h4x3rotab** [comment]
Hey. Thanks for the report! Just took a look and I found our testnet pool is down somehow. We have restarted it and the block chain is moving now :)

**Comment by mabbas1975** [comment]
Thanks for your help, it works and i keep mining on it but it stuck at block  9924, please help

**Comment by wilsonmeier** [comment]
@mabbas1975 is you issue resolved?
