### ISSUE TITLE
Equihash vulnerability - fix info?

### ISSUE THREAD

**Issue by attritionorg** [BTCGPU/BTCGPU#313]
Regarding this disclosure: https://github.com/edwardz246003/misc/blob/master/Attackers%20Fake%20Computational%20Power%20to%20Steal%20Cryptocurrencies%20from%20Mining%20Pools.md

"_Bitcoin Gold updated to a new equihashjs-verify._"

Can one of the developers link to the fixing commit and/or version that resolves this? Thanks!

**Comment by h4x3rotab** [comment]
Do you mean this repo?
https://github.com/BTCGPU/equihashjs-verify

To clarify, this repo is not intended to solve the z-nomp vulnerability. It's a pure Javascript implementation of Zcash's Equihash verifier for bgoldjs-lib (our bitcoinjs-lib fork). But due to it's not derived from equihashverify, it doesn't have the vulnerability as well.

**Comment by attritionorg** [comment]
Well, I read the original disclosure to mean that Bitcoin Gold was using a vulnerable Equihash implementation, then switched to a new one as a way to resolve the vulnerability. Unfortunately the disclosure isn't clear, so trying to clarify here if Bitcoin Gold is affected, or was.

**Comment by h4x3rotab** [comment]
equihashverify is originally used by z-znomp, which was later modified to the first Bitcoin Gold enabled pool. However it’s not official. We didn’t offer any support

**Comment by attritionorg** [comment]
Right, but still not clear if early versions of Bitcoin Gold used it. Sounds like it based on what you said. If it was a third-party library to Bitcoin Gold and distributed as part of the software, support or not, it would be vulnerable. If that is the case, should be easy to determine which versions were vulnerable, and which were not?

**Comment by wilsonmeier** [comment]
@attritionorg maybe you misunderstood the disclosure. It talks about a vulnerability in a javascript library used by **pools**. This has nothing to do with the core wallet this repo is about. You are right that it's not obvious what they mean by 

> Bitcoin Gold updated to a new equihashjs-verify.

I guess they mean pool.gold and the pools mining BTG.
Your wallet wasn't affected by that vulnerability.
Please close this issue if this answers your question.

**Comment by attritionorg** [comment]
@wilsonmeier Their disclosure implies that BTG is/was using the affected library. They obviously don't specify wallet vs anything else. I am interested in tracking it whether it is the wallet, the coin implementation, or anything else. If this repo covers the wallet only, is there a better repo to ask the question about?

**Comment by wilsonmeier** [comment]
@attritionorg i actually don't have links for you but basically every pool which supported "any" equihash coin and used that vulnerable library was affected.
