### ISSUE TITLE
Stuck at block 508010

### ISSUE THREAD

**Issue by mraksoll4** [BTCGPU/BTCGPU#314]
Hello, i try do some reserch and recompile sources from latest release 0.15.0.2

with new forkblock setting's at 522600 at chainparams.cpp and linearize
return magic bitcoin.

Then i try download blockchain and it always stuck at 508010 block, i try find what make this issue, but not find anyting.

If it possible please say what i forgot or do wrong , where this setting what make stuck at 508010 block.

I reserch all sources by compating with btc ver. from what it bassed, but dont see where setting what do this issue.

2018-05-15 05:18:09 ERROR: ConnectBlock: CheckQueue failed
2018-05-15 05:18:09 Misbehaving: 188.138.1.234:8333 peer=788 (0 -> 100) BAN THRESHOLD EXCEEDED
2018-05-15 05:18:09 InvalidChainFound: invalid block=0000000000000000001b1f59717b2446d89aa4c5d02d8a98f584344cc34d1af6  height=508011  log2_work=88.061177  date=2018-02-06 20:39:00

**Comment by h4x3rotab** [comment]
Sorry, can you explain it with details? What's the `forkblock` setting?

**Comment by mraksoll4** [comment]
i figurate at wat was problem , is was at SIGHASH_FORKID = 0x40,  for some reason it stuck at 508010 and block 508011 is marked as invalid.
But if change them to 0x10 , all work fine and blockchain not stop downloading after 508010.

How forkblock i was use 522600.



/** Signature hash types/flags */
enum
{
    SIGHASH_ALL = 1,
    SIGHASH_NONE = 2,
    SIGHASH_SINGLE = 3,
    SIGHASH_FORKID = 0x40,
    SIGHASH_ANYONECANPAY = 0x80,
};

/** Fork IDs **/
enum
{
    FORKID_BCC = 0,
    FORKID_BTEN = 79, // Atomic number AU
};

**Comment by wilsonmeier** [comment]
@mraksoll4 if i understood your post right, you are modifying the core wallet to experiment with it. We appreciate your engagement but our roadmap is long and sadly we don't have time to support you with that. 
This is not an issue with the core wallet itself.

@h4x3rotab please close.

**Comment by h4x3rotab** [comment]
This is not a problem of core wallet. So I'm going to close the issue. But feel free to reopen if you want a discussion of some experimental ideas.

**Comment by mraksoll4** [comment]
I undestand but possible this issue can affect blockchain of BTG at future. Somting comfict wirh transaction's at 508011 when using sighash id 0x40
