### ISSUE TITLE
test-faucet.bitcoingold.org do not work

### ISSUE THREAD

**Issue by yanpl** [BTCGPU/BTCGPU#317]
http://test-faucet.bitcoingold.org/ do not work now，please repair it or send some testnet3 coin to address：mychjvkKoFyuvJwhTCqs4DaYLBYtR79dpw

**Comment by brucexiu** [comment]
my address: 2NBdbBv7TFTPazrqmcV7LD2zc2fnSTwZgr7
thanks

**Comment by wilsonmeier** [comment]
@yanpl testnet faucet is up again.

**Comment by yanpl** [comment]
@wilsonmeier yes，it's worked， thanks
