### ISSUE TITLE
Feature request: bitcore regtest difficulty

### ISSUE THREAD

**Issue by bijakatlykkex** [BTCGPU/BTCGPU#319]
Hello,

While running the daemon for bitcore in regtest mode and generating some thousands blocks, it seems difficulty goes up and new blocks need much computing power to get generated. It would be desirable that the behavior of node - about block generation - remains in the state when node has just started to generate blocks.

As I have researched the problem may be correlated to https://github.com/BTCGPU/BTCGPU/pull/302 . But since sources differ between master and bitcore branch, it seems applying the changes to bitcore branch may not be trivial.

Comments/helps appreciated.

Thank you

**Comment by h4x3rotab** [comment]
Yes, you are right. It's actually not hard to rebase the bitcore to the latest version. I will do it soon.

**Comment by bijakatlykkex** [comment]
Thank you. Is there any estimated time of arrival for this?

**Comment by h4x3rotab** [comment]
Basically we just keep rebasing to the latest master commit. I've just pushed the latest version to `bitcore` branch. Could you check it out?

**Comment by bijakatlykkex** [comment]
I was able to compile and use the new daemon and difficulty seems to be returning as 1 always for my old reindexed blockchain.

Since the difficulty increase on my side started to happen after some days of block generation, there remains a little probably that difficulty would start to increase sometime from now, which I think will not happen and I would hopefully comment here in such a case.

Thank you very much for your attention and help.
