### ISSUE TITLE
Network upgrade testnet launch

### ISSUE THREAD

**Issue by h4x3rotab** [BTCGPU/BTCGPU#324]

**Comment by bitcartel** [comment]
Do you have access to a z9 mini to test if it can mine the updated parameters (with the current firmware)?

**Comment by h4x3rotab** [comment]
I don't think Z9 mini can mine 144-5. It's a single-chip solver without enough memory.

**Comment by bitcartel** [comment]
It seems 144-5 might be viable: https://forum.z.cash/t/let-s-talk-about-asic-mining/27353/3332

Have you done a teardown of the z9 mini?  Would be great if you could share your findings.

**Comment by h4x3rotab** [comment]
BTG testnet was upgraded by a hardfork at block 14300.
