### ISSUE TITLE
Adjust LWMA params for the mainnet launch

### ISSUE THREAD

**Issue by h4x3rotab** [BTCGPU/BTCGPU#325]
The param of the current LWMA is not perfect. According to https://github.com/zawy12/difficulty-algorithms/issues/3#issuecomment-388386175 we still need to fix a few minor logic for the best performance.

**Comment by Shiro20** [comment]
how to do this on cryptonote?

**Comment by h4x3rotab** [comment]
@Shiro20 https://discord.gg/7UFS4fq Join zawy's Discord server. There are plenty of cryptonote forks who have implemented LWMA.

LWMA is working perfectly on testnet. Closing this issue.
