### ISSUE TITLE
High CPU utilization when querying RPC

### ISSUE THREAD

**Issue by v0l** [BTCGPU/BTCGPU#328]
## Describe the issue
RPC query using a lot of CPU time to fetch recent block and its transactions with txindex enabled (see below)

Version = /Bitcoin Gold:0.15.0.2/

#### Steps to reproduce below:
1. getblockhash 532746
2. getblock {hash goes here} 1
3. Read txn's and all inputs in every tx in this block

### Expected behaviour
Fast rpc response times

### Actual behaviour
requests timeout after 30s (set timeout in php)

### Screenshots.
![image](https://user-images.githubusercontent.com/1172179/41219625-780c469c-6d91-11e8-99a6-70c192223fb7.png)

### What version of bitcoin-gold are you using?
Using the uphold docker image here https://hub.docker.com/r/uphold/bitcoin-gold/
This downloads the release from github 

### Machine specs:
- OS: Ubuntu 17.10
- CPU: 8x core W3520  @ 2.67GHz
- RAM: 16 Gb
- Disk size: 2TB
- Disk Type (HD/SDD): HDD

**Comment by h4x3rotab** [comment]
Sorry, focusing on the PoW. Don't have much time to dig into it. Is this issue stably reproducible?
