### ISSUE TITLE
when release 0.15.1 for hard fork ?

### ISSUE THREAD

**Issue by JokerCatz** [BTCGPU/BTCGPU#336]
https://github.com/BTCGPU/BTCGPU/issues/331

follow the guide , I just need upgrade to 0.15.0.3 right ? but it not yet release , so it will be release at next week? or I need compile master branch by myself at next week ?

**Comment by JokerCatz** [comment]
I need the 0.15.1 release package , and hard fork at "July 1st, 2018" is too close ... I think maybe 80% sync nodes will stay at "classic" branch ...... except some miner node ...

**Comment by wilsonmeier** [comment]
Release is ready https://github.com/BTCGPU/BTCGPU/releases
