### ISSUE TITLE
Gitian release for v0.15.1-rc1

### ISSUE THREAD

**Issue by h4x3rotab** [BTCGPU/BTCGPU#337]
This is the tracking issue for the 0.15.0.1-rc1 release

**Comment by akx20000a** [comment]
Started building new 0.15.0.1-rc1 release 😄

**Comment by Briechenstein12** [comment]
https://github.com/bitcoin/bitcoin/releases/tag/v0.15.0rc1

**Comment by h4x3rotab** [comment]
@akx20000a Any good news? I've uploaded the signatures for signed & unsigned binaries :)

**Comment by akx20000a** [comment]
@h4x3rotab Done! https://github.com/BTCGPU/gitian.sigs/pull/30
