### ISSUE TITLE
Change our ClientID

### ISSUE THREAD

**Issue by leto** [BTCGPU/BTCGPU#34]
Suggested by @daira here https://github.com/BTCGPU/BTCGPU/issues/16#issuecomment-335618886 and a very good idea, to differentiate our client

**Comment by StarbuckBG** [comment]
@leto may we close that issue ? We are referencing to #16 for discussion.

**Comment by leto** [comment]
@StarbuckBG looks like https://github.com/BTCGPU/BTCGPU/blob/master/src/clientversion.cpp#L16 has been changed to a unique value (I am not a fan of the space character, and every other coin comes up with a unique "user agent" string that occasionally changes, so making it `Bitcoin Gold` may cause future issues) but yes, this can be closed
