### ISSUE TITLE
https://test-faucet.bitcoingold.org/

### ISSUE THREAD

**Issue by guchenglin111** [BTCGPU/BTCGPU#343]
use  website: https://test-faucet.bitcoingold.org/   
get test coin

test example  address
           mrAD6MAxZddSXhFPBqwptZDn52nE4qKPaG
          n1XQeqSmphQxXVCABC8EKvgCPa9WneHNeA
          n1JQS9Nr794yGLLqezKn2UWjPVpXEfYuJs
         n242mL96NaprqzPyrefdAnmLuF8DqNoryG
### 
actual result:
           Invalid address

**Comment by guchenglin111** [comment]
How do I get the test coin?
Can you transfer me some test coin to the address of n242mL96NaprqzPyrefdAnmLuF8DqNoryG

**Comment by Vutov** [comment]
This should help you with development - https://test-explorer.bitcoingold.org/insight/tx/0c692cc24ee6c53953e49da217f52af1e4fb2463181df3e59612ff58d980984c

**Comment by guchenglin111** [comment]
Transfer a transaction, the test network is not confirmed！
https://test-explorer.bitcoingold.org/insight/tx/f3af96ef617575ce0dc11cf778e2208b35fedf8e218dc08dec0f3f637eb3205f

**Comment by h4x3rotab** [comment]
The testnet blockchain was stuck because miners all left the pool. Now we have pointed one gpu to the pool and everything looked good now.

**Comment by h4x3rotab** [comment]
Looks like the faucet is working as well

**Comment by guchenglin111** [comment]
thx
