### ISSUE TITLE
openssl_init_crypto error

### ISSUE THREAD

**Issue by potadibyo** [BTCGPU/BTCGPU#347]
*libbitcoin_util.a(libbitcoin_util_a-util.o): In function

CInit::CInit()': /root/mrcash/src/util.cpp:133: undefined reference to

OPENSSL_init_crypto'
collect2: error: ld returned 1 exit status
Makefile:3661: recipe for target 'mrcashd' failed
make[2]: * mrcashd] Error 1
make[2]: Leaving directory '/root/mrcash/src'
Makefile:9359: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/root/mrcash/src'
Makefile:741: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
please help me to sort out this problem..

**Comment by h4x3rotab** [comment]
Are you trying to compile something depending on libbitcoin (not the full node)?

If so, I think at the early stage some dependency of libbitcoin was broken by Equihash. If you can confirm it I can try to add the dependency back.

**Comment by potadibyo** [comment]
i also update .mmo in makefile.am and src/makefile.am and src/makefile.qt.include upgrade  openssl still that gives an error...

**Comment by potadibyo** [comment]
i also added sodium library after giving cannot found lib-sodium.......

**Comment by potadibyo** [comment]
@h4x3rotab thank dear, I do this things today......... yesterday there was no error in compile time..

**Comment by potadibyo** [comment]
@h4x3rotab i install those dependencies

sudo apt-get install build-essential libtool autotools-dev automake
pkg-config libssl-dev libevent-dev bsdmainutils



sudo apt-get install libboost-system-dev libboost-filesystem-dev
libboost-chrono-dev libboost-program-options-dev libboost-test-dev
libboost-thread-dev



sudo apt-get install libboost-all-dev



sudoapt-get  install software-properties-common



sudo add-apt-repository ppa:bitcoin/bitcoin



sudo apt-get update



sudo apt-get install libdb4.8-dev libdb4.8++-dev



sudo apt-get install libminiupnpc-dev



sudo apt-get install libzmq3-dev



sudo apt-get install libqt5gui5 libqt5core5a libqt5dbus5 qttools5-dev
qttools5-dev-tools libprotobuf-dev protobuf-compiler



sudo apt-get install libqt4-dev libprotobuf-dev protobuf-compiler

sudo apt-get install openssl-dev python-dev

**Comment by h4x3rotab** [comment]
Would you like to share me the purpose? I was assuming you are trying to compile just `libbitcoin` for some special use cases. But just want to confirm in case I might be wrong.

**Comment by h4x3rotab** [comment]
If you just want to compile Bitcoin Gold, I think it shouldn't be hard as I replied in another thread: #348
