### ISSUE TITLE
not to build test/test_bitcoin

### ISSUE THREAD

**Issue by potadibyo** [BTCGPU/BTCGPU#348]
in console shown 
../build-aux/test-driver: line 107 :16959 aborted "$@" > $log_file 2>&1
FAIL : test/test_bitcoin
../build-aux/test-driver: line 107 :16968 aborted "$@" > $log_file 2>&1
FAIL : test/test_bitcoin_qt

help needed..........

**Comment by h4x3rotab** [comment]
What's your OS and how did you compile it?

I used to build the project on macOS and Ubuntu (16.0.4). When the dependencies are ready, it's quite straightforward:
```
./autogen.sh
./configure
make
```

**Comment by potadibyo** [comment]
Hello sir @h4x3rotab thank for information.
Right now i am stuck with another error , when i try run bitcoingold-qt on my vps that give error
qt.qpa.QXcbConnection: Could not connect to display
Could not connect to any X dis[play....
please help me sir.....

**Comment by josephnicholas** [comment]
@potadibyo please post your VPS specifications, and if your VPS is just CLI only or the one with Desktop GUI. The Qt wallet is for GUI enabled OSes/VPS, the bitcoingold daemon is for CLI.
