### ISSUE TITLE
after mining genesis  block  its shown

### ISSUE THREAD

**Issue by potadibyo** [BTCGPU/BTCGPU#349]
I  Mined The genesis block through this code  
 consensus.hashGenesisBlock = uint256S("0x");
   std::cout << std::string("Begin calculating Mainnet Genesis Block:\n");
        if (true && (genesis.GetHash(consensus) != consensus.hashGenesisBlock))
{
                printf("Calculating Mainnet Genesis Block:\n");
               LogPrintf("Calculating Mainnet Genesis Block:\n");
                   arith_uint256 hashTarget = arith_uint256().SetCompact(genesis.nBits);
                   uint256 hash;
                   genesis.nNonce = ArithToUint256(0);
              while ((UintToArith256(genesis.GetHash(consensus)) > hashTarget) 
            {
                genesis.nNonce = ArithToUint256(UintToArith256(genesis.nNonce) + 1);
                         if (genesis.nNonce == ArithToUint256(arith_uint256(0)))
                         {
                             LogPrintf("NONCE WRAPPED, incrementing time");
                             std::cout << std::string("NONCE WRAPPED, incrementing time:\n");
                             ++genesis.nTime;
                         }

                         if ((int)genesis.nNonce.GetUint64(0) % 10000 == 0)
                         {
                              std::cout << strNetworkID << " hashTarget: " << hashTarget.ToString() << " nonce: " << genesis.nNonce.ToString() << " time: " << genesis.nTime << " hash: " << genesis.GetHash(consensus).ToString().c_str() << "\r";
                         }

            }
                     std::cout << "Mainnet ---\n";
                     std::cout << "  nonce: " << genesis.nNonce.ToString() <<  "\n";
                     std::cout << "   time: " << genesis.nTime << "\n";
                     std::cout << "   hash: " << genesis.GetHash(consensus).ToString().c_str() << "\n";
                     std::cout << "   merklehash: "  << genesis.hashMerkleRoot.ToString().c_str() << "\n";
        }
        std::cout << std::string("Finished calculating Mainnet Genesis Block:\n");
////nonce : 000000000000000000000000000000000000000000000000000000000000000000000003d04c923
///////////genesishash : 000000001b09e6b2c626694c17c0ce45148897ba738103e5bd65e7c99f6a738b       
///////Merkle Root : 64166c8fd000b931395a6616ac26cceaf6f4a2ea11e292575ab84cee5b90977b	  
it gives nonce like this : 000000000000000000000000000000000000000000000000000000000000000000000003d04c923
but time to genesis function wriiten on like  genesis = CreateGenesisBlock(1534773936, 2083236893, 0x1d00ffff, 1, 50 * COIN);
000000000000000000000000000000000000000000000000000000000000000000000003d04c923 is not like (2083236893) format How can i turned into this formating like nonce  writtrn in CreateGenesisBlock(),
I know just beacause of i didnot give proper nonce format ,
How I can convert this nonce to crategenesisblock nonce type.
chainparams.cpp:219: CMainParams::CMainParams(): Assertion `consensus.hashGenesisBlock == uint256S("0x000000001b09e6b2c626694c17c0ce45148897ba7c99f6a738b")' failed.
please help me need your advice members,
 Thank You,
 Dibyajit

**Comment by h4x3rotab** [comment]
You can convert a uint32 into a uint256 by `ArithToUint256(arith_uint256(u32))`
