### ISSUE TITLE
get chain size through rpc

### ISSUE THREAD

**Issue by roccomuso** [BTCGPU/BTCGPU#358]
Is it possible to get chain size on disk through rpc?
The equivalent of bitcoind `size_on_disk` property from the `getblockchaininfo` rpc method.

**Comment by h4x3rotab** [comment]
This field was merged to the core wallet right after we forked the code. There's a pending PR to upgrade to v0.16, which will introduce this field. Let me prioritize the core wallet upgrade.

**Comment by h4x3rotab** [comment]
It's going to be fixed by 0.17, which is already on the staging branch. So I'm going to close it.
