### ISSUE TITLE
tradesatoshi.com BTG no work

### ISSUE THREAD

**Issue by xxxmig** [BTCGPU/BTCGPU#373]
Hi, BTG wallet no work tradesatoshi.com  02-27-2019 and no deposit
please contact tradesatoshi.com and fix BTG wallet

**Comment by h4x3rotab** [comment]
Hi, thanks for reporting. We are trying to reach out to tradesatoshi now.

**Comment by xxxmig** [comment]
https://tradesatoshi.com
http://prntscr.com/ncu1lf
thank you very much

**Comment by xxxmig** [comment]
Tradesatoshi.com fix BTG ?

**Comment by h4x3rotab** [comment]
We have tried really hard to reach out to them to offer our help but unfortunately we got no response.

**Comment by xxxmig** [comment]
I wrote here https://discordapp.com/channels/342879339202740224/453477450937270272
I do not know what to do...

**Comment by xxxmig** [comment]
support tradesatoshi asked to send them a ticket number

**Comment by xxxmig** [comment]
support tradesatoshi answered "please tell them to send us a ticket"
