### ISSUE TITLE
Must ignore fork ID prior to fork, otherwize we get stuck at block 264083 running with -assumevalid=0

### ISSUE THREAD

**Issue by ehoffman2** [BTCGPU/BTCGPU#379]
Running Bitcoin Gold 0.15.2.0

I start with parameters
  -reindex-chainstate -assumevalid=0

This force re-validating the whole blockchain, and not assume that blocks prior to latest checkpoint are valid.

However, the validation get stuck at block 264083.  The node can not validate block 264084.

The issue come from one of the transaction:
  tx: ba4f9786bb34571bd147448ab3c303ae4228b9c22c89e58cc50e26ff7538bf80

which have bogus hashtype (0x50).

This effectively have bit set which correspond to SIGHASH_FORKID.  However, this flag MUST NOT be checked prior to the fork point, as this is a legacy hashtype.  Note that there are quite a few Tx with bogus hashtype, although I have not checked extensively if some other bogus hashtype have this bit set.

The signature thus does not compute the same sighash, signature validation then fail, and the block is considered as invalid (consensus critical check).

A similar bug appeared in other forks, like Bitcoin Cash (ABC), Bitcoin SV, Bitcoin Unlimited, which all used a 'fork ID' bit, and has since been corrected.  See for example

https://github.com/BitcoinUnlimited/BitcoinUnlimited/commit/31997049677cee45bce04be740bc543b49083454

Basically, the script flags are passed to SignatureHash(), and the check for forkid is done only if flag SCRIPT_ENABLE_SIGHASH_FORKID is set (which is defined after a specific height, encoded in the chain parameters).

In this case, the issue start in SignatureHash() function in src/script/interpreter.cpp, which call

if (UsesForkId(nHashType))
    nForkHashType |= forkid << 8;

instead of something like

if (UsesForkId(nHashType) && (flags & SCRIPT_ENABLE_SIGHASH_FORKID))
    nForkHashType |= forkid << 8;

Note that the 'flags' variable has to be passed from deep above in the function calls, so this is not a simple 1-liner fix.  But it should be similar to what you find for the other coins.

Note that this does not happen if you do not reindex the whole chain and do not set the assumevalid flag to 0 (or a block hash of a block lower than the problematic blocks).

Regards,
Eric H.

**Comment by h4x3rotab** [comment]
Hi Eric,

Thanks for reporting. Indeed it's a problem in the source code. As suggested I will look into it carefully and fix it as soon as possible. It's likely that it will be addressed in the next release (0.17, which is in beta stage).

**Comment by h4x3rotab** [comment]
I'm on it. Still need to fix a few test cases
