### ISSUE TITLE
How to participate during the pre-mine stage?

### ISSUE THREAD

**Issue by krtschmr** [BTCGPU/BTCGPU#38]
i have 155 k/zol that i would like to contribute to make the network bigger. how to do?

when can we start up the first pools?

**Comment by StarbuckBG** [comment]
Hello. The premining will be internal. 
Good luck with the pools. If you have any questions, you can ask.

**Comment by georgk10** [comment]
A few possibility after start of mainnet: 
http://pool.gold/
https://pool.miningspeed.com/
http://versum.io
https://pool.serverpower.net/

**Comment by oliverw** [comment]
https://poolmining.org

**Comment by gcrimi** [comment]
Hi @StarbuckBG, 

if the premine stage will be done at really low difficulty how you can ensure that a miner with high hash power will not rewrite the entire pre-mine period to create a big reorg and get the 100.000 premined BTG for him?

**Comment by leto** [comment]
@gcrimi great question. There is no transparency about the pre-mine, which is causing concern. @StarbuckBG can you please explain it more detail?

**Comment by oliverw** [comment]
@StarbuckBG Well I've asked a question that went unanswered: https://github.com/BTCGPU/BTCGPU/issues/37

**Comment by h4x3rotab** [comment]
Spec and the implementation will come out soon. 

Basically:
* Premine will be done in a very short period (difficulty=1). 
* Coinbase output address must be whitelisted
* Coinbaee output will have special time-lock rules

**Comment by krtschmr** [comment]
so the premine will take part within 5 hours because basically with 5 GPUs and diff1 it's like 1 block per second. maybe the nodes ain't even fast enough for that. 
my concern is that you still *premine* even while testnet is live, simply because we are not ready to jump into after block 16.000.

**Comment by benkloester** [comment]
You're going to gum up consensus code with a whitelisted address for coinbase output specifically for the premine?

I don't see any code reflecting what you're suggesting in chainparams yet, and the fork is supposedly in 5 days now. Can you point me to the LOC that will ensure only you can premine and nobody else?

Furthermore if someone wanted to piss in your wheaties, they could still re-org your premined chain - the code is open source, so they can mine just as fast as you.

**Comment by ekerstein** [comment]
Why is there a premine in the first place, doesn't this undermine the credibility of the entire project? Couldn't it just be interpreted as the devs inserting a hack into the bitcoin protocol where they get free coins?

**Comment by jagottsicher** [comment]
Yes, it is, but generally they see it as some kind of "bonus", they want to make sure they have the longest chain. So if someone wants to "take over" their wonderful Chain they have a longer chain at diff1 in the back pocket which nobody can beat. anyway as I understood they get around 200,000 BTG.

a good reson to start minig as soon as possible after the start of the project, but
how? I didn't see some mining options?

**Comment by Coryvmcs1** [comment]
MinerTopia.org will be ready.

**Comment by krtschmr** [comment]
@Coryvmcs1 the question is simply: when exactly do *we* get rewarded? from block 8.001 on? this will propably be 5 hours after the fork since they wanna run with DIFF=1. if you just have ike 12x 1070 GPUs, it's done quick. if they use our hashing power and simply payout to them, it's even done more fast....

**Comment by TheButterZone** [comment]
https://github.com/realBitcoinGold/BTCGPU/commit/623ec59bb35bd4f20031506a4314e45a1d53fa6f

**Comment by OleksandrBlack** [comment]
http://lucky-mining.com.ua/
Ukraine / Kiev
will be with you

**Comment by Tinkymon** [comment]
Why would the premier only be internal????

**Comment by StarbuckBG** [comment]
I will close this issue. More information can be found on BTG FAQ: https://btcgpu.org/faq/ and the roadmap: https://btcgpu.org/wp-content/uploads/2017/10/BitcoinGold-Roadmap.pdf
For discussion you shall use Slack: https://join.slack.com/t/bitcoin-gold/shared_invite/enQtMjYxMDU5NzQzNjUyLTJlODRhYjg2NGRmMzE4ZjBkZjlmOGM0ZDc0OGUyMDZmMTVlY2RjZDc2OWQ0NWY2NWI0ODcyZjYwZTVhMjQ5OTE
