### ISSUE TITLE
Balls not dropping quickly enough

### ISSUE THREAD

**Issue by ballsonyaface** [BTCGPU/BTCGPU#380]
The balls on this sucker are not dropping fast enough. Bitcoin Core and Bitcoin (Bitcoin Cash) are moving quicker and flawlessly. This is the real Bitcoin and we need to get this suckers testosterone level boosted or we run risk of it becoming a tranny coin. There are more bugs in this thing than when I had crabs the last time. The last thing we need is a confused narcissistic coin that runs around screaming for attention. Time to pick yourself up by your boobstraps and get rock hard into the code! We can do it together.

**Comment by h4x3rotab** [comment]
It's time to code. Let's do it together!
