### ISSUE TITLE
Please Testnet Faucet

### ISSUE THREAD

**Issue by Droppix** [BTCGPU/BTCGPU#391]
Hi there,

I need to do some tests, could someone send me some BTG (testnet) please?
My address is 2NEVg7yQyW5n8Q1hBSUK57H6q43LZVqjFiS

Thanks

**Comment by h4x3rotab** [comment]
Sent 1 tBTG. You can also get some from here:

https://test-faucet.bitcoingold.org/

**Comment by Droppix** [comment]
Oh great! Thankx
