### ISSUE TITLE
fix doc/release-notes.md

### ISSUE THREAD

**Issue by c0deright** [BTCGPU/BTCGPU#394]
@h4x3rotab You might want to fix the [doc/release-nodes.md](https://github.com/BTCGPU/BTCGPU/blob/master/doc/release-notes.md) for the upcoming release since it's from 2018 and straight from bitcoin core.

**Comment by h4x3rotab** [comment]
Thanks for the heads-up. We are going to run a gitian build for v0.17.1 final release so that we can just fix the wrong part.

**Comment by wizzfile** [comment]
https://github.com/BTCGPU/BTCGPU/blob/master/doc/release-notes.md

**Comment by c0deright** [comment]
Is there a reason why the v0.17.1-rc1 is still on the website?
No mention at all of the v0.17.1 (non-rc1) release.
Why is v0.15.2 still the main download offered?

https://bitcoingold.org/downloads/

**Comment by MentalNomad** [comment]
Closing because this has not been the case for several months; v0.17.1 is main download on the website.

Note: website download link is simply a link to the GitHub release.

**Comment by c0deright** [comment]
> Closing because this has not been the case for several months; v0.17.1 is main download on the website.

That's not correct.

v0.17.1 was released [February 28th](https://github.com/BTCGPU/BTCGPU/releases/tag/v0.17.1) but the website on [May 11th](https://web.archive.org/web/20200511114305/https://bitcoingold.org/downloads/) still only offered v0.15.2.

You might want to check your scripts updating the website/purging website cache.

**Comment by MentalNomad** [comment]
You are correct, there was an issue regarding page rollback and sync - however, as of now, July 1, it had been corrected for quite some time, > 1 month. I should not have said "several months." 

The initial issue here still needs to be addressed.

**Comment by MentalNomad** [comment]
It seems there is a discrepancy between these two URLs on the web site:

https://bitcoingold.org/downloads/ <-- this points to the current version download page

https://bitcoingold.org/download/ <-- this points to the old page for v0.15.2

The GitHub repo has always had the correct status. This issue has been referred to our web site admins to be resolved; it is not an issue with the btcgpu codebase, so I'm closing this issue.
