### ISSUE TITLE
VULNERABILITY REPORT EMAIL SPOOFING DUE TO WEAK SPF

### ISSUE THREAD

**Issue by kamranjaved2662** [BTCGPU/BTCGPU#396]
Hello Team ,

i am a security researcher and i founded this vulnerability in your website.

Description :

this report is about misconfigured spf record flag , which can be use to abuse the organization by posing the identity , which allowing to fake mailing on behalf of respected organization .

About the Issue :

as i seen the SPF and TXT record for DPO@bitcoingold.org.   which is :

v=spf1 mx~all  

as u can see the symbol at last which question mark (~all) is the issue , which should be replace by Hyphen (-all) symbol .

so valid record will be look like :

v=spf1 mx -all  

Whats the issue :

as u can see in the article difference between softmail and fail you should be using fail as Softmail allows anyone to send spoofed emails from your domains.

in current SPF record you should replace ~ with - at last before all , - is strict which prevents all spoofed emails except if you are sending .

Whats the issue :

as u can see in the article difference between softmail and fail you should be using fail as Softmail allows anyone to send spoofed emails from your domains.

in current SPF record you should replace ~ with - at last before all , - is strict which prevents all spoofed emails except if you are sending .

Attack Scenario :

an attacker will send phishing mail or anything malicious mail to the victim via mail :DPO@bitcoingold.org.   , even if the victim is aware of phishing attack , he will check the Origin email which will be DPO@bitcoingold.org.   , so he will be sure that its not fake mail and get trapped by attacker !

This can be done using any php mailer tool like this ,

<?php

$to = "VICTIM@example.com";

$subject = "Password Change";

$txt = "Change your password by visiting here - [VIRUS LINK HERE]l";

$headers = "From:  DPO@bitcoingold.org.   ";

mail($to,$subject,$txt,$headers);

?>

u can check your SPF record form here : http://www.kitterman.com/spf/validate.html !

Reference : https://www.digitalocean.com/community/tutorials/how-to-use-an-spf-record-to-prevent-spoofing-improve-e-mail-reliability

have a look on the digitalocean article for the better understanding !

Please let me know if any more info needed !
Waiting for your reply and hopefully a $150 bug bounty for responsibly reporting the issue ...

Regards,
EthicalAm      
hackerone :kamranjaved2662

**Comment by santos177** [comment]
Thanks for that report @kamranjaved2662  but maybe you should read first this : https://github.com/BTCGPU/Developer-Portal/blob/master/responsible-disclosure.md, see the #Please section.

**Comment by kamranjaved2662** [comment]
@santos177 .. I am new here I didn't know how to report a bug here... 
thanks

**Comment by h4x3rotab** [comment]
I'm going to close this because the responsible disclosure requires a disclosure to our admin email directly.
