### ISSUE TITLE
can't compile on any barely-modern OS distribution (too old Berkeley db)

### ISSUE THREAD

**Issue by dchmelik** [BTCGPU/BTCGPU#399]
Describe the issue:

Can't compile on any barely-modern OS distribution (distro, too old Berkeley db.)  I've tried compiling on various OS from Slackware-current 14+ to *ubuntu 20.04 LTS... I realize both are extremely new, though Slackware-stable is itself five years behind on .ISO release, and often falling behind on things like standard compilers & programming languages (necessary for standard usage)... Slackware-current isn't always far ahead (maybe often, so in this case, but if it is, most other distros are)... *ubuntu 20.04 possibly is farther ahead (on some things, not others) but _is_ a long-term-support (LTS) release, and maybe most widely-used.

What behavior did you expect?

Hoped old libdb would be available or newer would be an option so it'd compile: can't compile because these don't have Berekely db 4 anymore, only 5... can't even run prebuilt binary anymore presumably for same reason?

What was the actual behavior (provide screenshots if the issue is GUI-related)?

Make/compile halts because of like 'not finding libdb' file(s) (i.e., can't find the newer, now standard ones.)

How reliably can you reproduce the issue, what are the steps to do so?

Every time on probably any up-to-date distro.

What version of Bitcoin Core are you using, where did you get it (website, self-compiled, etc)?

BTCGPU 0.17.1 got from here.

What type of machine are you observing the error on (OS/CPU and disk type)?

Slackware-current 14+, *ubuntu 20.04 LTS, Intel Core i7 CPUs, medium-to-high-quality solid state drives (SSDs: Micron/Crucial, Intel, Samsung, Corsair, Kingston, etc., maybe PNY on one) with plenty of space (several/many tens extra GB.)

Any extra information that might be useful in the debugging process.

Didn't save one but can redo & paste on gist if you want (GitHub's pastebin, which you probably should mention/recommend.)

**Comment by h4x3rotab** [comment]
Hi. The old Berkeley db is used to make the wallet file compatible with the old node. It can be compiled with newer Berkeley db. To compile the node, it's recommended to compile every dependency from the code. Please check the readme file in depends directory:

https://github.com/BTCGPU/BTCGPU/tree/master/depends

Another good document you might be interested is the build doc:

https://github.com/BTCGPU/BTCGPU/blob/master/doc/build-unix.md

**Comment by dchmelik** [comment]
> Another good document you might be interested is the build doc: https://github.com/BTCGPU/BTCGPU/blob/master/doc/build-unix.md

That's how I was able to compile it for years.

Actually you are probably right; I am compiling it for wallet (so maybe had a different problem, but am working on that) but had some different problem when compiling... as long as you can compile with Berkeley db 5 (mostly it's 5.3) and use the wallet (so if I was wrong) can this thread just be deleted?

**Comment by dchmelik** [comment]
actually... this was the further detail: 'configure: error: Found Berkeley DB other than 4.8, required for portable wallets (--with-incompatible-bdb to ignore or --disable-wallet to disable wallet functionality.)
'  Of course, I compiled it with 5.3 (around many, many years) and BTCGPU compiled & installed fine, but... then I wasn't able to send any BTG (unlike when I previously compiled it with 4.8, could send some)... but not even for portable wallet... for the desktop PC wallet... wondering if they work the same, or there was some other problem maybe I should get in a debug log (not sure how to.)

**Comment by dchmelik** [comment]
I think you were right; had to reread I just have to wait a number of blocks (even if it takes hours) to send; nothing to do with which database was used.
