### ISSUE TITLE
Vote for a new logo design !

### ISSUE THREAD

**Issue by Aklibaitiche** [BTCGPU/BTCGPU#41]
All the exchange platform, coinmarketcap and other news website are going to take the logo from the official website. If you think that the current logo gives a bad image to Bitcoin Gold thank you for voting or propose a new design.

Idea 1 :  Bitcoin is leaning on one side, and Bitcoin cash is leaning on the other side, Bitcoin version Gold will have his letter R I G H T 
![original-version-copie-copie](https://user-images.githubusercontent.com/2818626/31796082-7b4565d6-b528-11e7-8bd3-4a3a4612007e.png)

Vote 👍

**Comment by Aklibaitiche** [comment]
Idea 2 : One of the main improvement that Bitcoin version Gold offers is the decentralisation of miners, this improvement will be put forward in this way
![network-btg-version1](https://user-images.githubusercontent.com/2818626/31796381-8ef6b0a2-b529-11e7-95f6-94057d2e9914.png)

**Comment by Aklibaitiche** [comment]
Or : 
![network-btg-version2](https://user-images.githubusercontent.com/2818626/31796406-a53bacaa-b529-11e7-84ae-5969023f3fd9.png)

**Comment by Aklibaitiche** [comment]
Or we keep the current logo:

![bitcoingold-logo0k](https://user-images.githubusercontent.com/2818626/31796480-010e3fe8-b52a-11e7-9f71-2a15cbeae2ef.png)

**Comment by dxd5001** [comment]
I like the color same as Bitcoin family. It’s good for help people to recognize BTG is the BTC family, and so BTG can adopt speedy, I think. 
The shape a little more simple than those above, I like.

**Comment by krtschmr** [comment]
@dxd5001 it's only good to try to trap people in it... no need for copycat-bitcoin-logo....
