### ISSUE TITLE
Deposit Gate.io

### ISSUE THREAD

**Issue by RAMBASADOR** [BTCGPU/BTCGPU#417]
Hi, I was mining btg coin to wallet GNdNWJpCNhKgdeDroeVM1u7twX7Ek3qtN8, and did not received all coin because wallet was closed, just got 42.98393881, but mining pool shows 113.968775. https://btg.2miners.com/ru/account/GNdNWJpCNhKgdeDroeVM1u7twX7Ek3qtN8. https://btgexplorer.com/address/GNdNWJpCNhKgdeDroeVM1u7twX7Ek3qtN8
how i can get back my coins? Thanks

**Comment by MentalNomad** [comment]
BTG wallets were never "closed;" the balance in wallet GNdNWJpCNhKgdeDroeVM1u7twX7Ek3qtN8 is 113.9687748 BTG, same as on 2Miners.

There are two possibilities;

1. You were looking at the balance before the pool paid out. New blocks need 100 confirmations to mature before the reward can be spent by the pool to pay the miners. As soon as the pool pays out the reward, it will appear in the BTG wallet it was paid to. Be careful not to confuse the pool's "payable" amount (awaiting maturity and payment) and the pool's "total paid" amount (actually sent to your address.)
2. There can be a difference between when a transaction is **received** by an Exchange's wallet address on a blockchain versus when the Exchange will **accept** it. If Gate.io "closed" their wallets what this means is that Gate.io does not recognize deposits or allow those deposited to be tradable. They cannot actually prevent the wallet from receiving transactions;  the transactions are on the blockchain and are uncensorable.

Note that this is why most (all?) pools stress that mining should be done to private wallet addresses, not to Exchange wallets. Many exchanges explicitly state that they **do not allow** their addresses to be used for mining. (They do not want to receive many tiny payments and then have difficulties with transaction sizes and combining the UTXOs into a single payment.)

If Gate.io is still showing only 42.98 BTG, you will need to take up the issue with them. There are 113.97 BTG in that wallet address; beyond that, it is a matter of what Gate.io chooses to recognize.
