### ISSUE TITLE
Duration of premine if DIFF=1 could be a couple of minutes?

### ISSUE THREAD

**Issue by krtschmr** [BTCGPU/BTCGPU#42]
With 5.000 Zol/s (about 12x Nvidia 1070) and a `diff=1` we would be able to reward 659.180 BTCG per day. This will translate to `52734 Blocks` if `reward=12.5`. 

If you want to only premine 16.000 blocks , this will roughly be `0.61`blocks **per second!**. 

First it's curios to see how your network (mainnet doesnt even exist) will keep up the pace but then the question is:  If fork 25th and premine starts 25th, then we can jump in on 25th aswell?

When do you really start the premine (UTC)? how long you expect it to be?

**Comment by krtschmr** [comment]
Since you plan to start mainnet on Nov 1st 2017 i wonder what happens to the difficulty after block 200.000 ? i cant find difficulty adjustment after that block. can you show me the LOC? also, still unknown, how can we contribute hashingpower, towards block 200.001? it seems that you guys stash your coins with diff=1 and then continue till mainnet is on? that sounds scammy and seems to be a bit ridiculous. clearing these issues up might help gaining trust.

**Comment by krtschmr** [comment]
@leto  any statements?

**Comment by leto** [comment]
@krtschmr I am not involved in the premine, I don't know much about the internals. I am working for bounties and currently concentrating on wallets.

**Comment by krtschmr** [comment]
@leto  thought you're *inside the group* . so then, who is actually in charge for this?

**Comment by krtschmr** [comment]
@h4x3rotab @StarbuckBG  any statements?

**Comment by StarbuckBG** [comment]
The idea of the premise is to be a couple of minutes? And the premised coins are 100k. 60% of them are time locked in a period of 3 years. The LOC is being developed and will be publicly available for everyone also the address. The mining will be done with minimum hashing power using only one node and the network will accept blocks only from this one node. 
Any other questions ?

**Comment by krtschmr** [comment]
so, when this will be happening? *minimum hashingpower* is still enough to have it done within 10 hours with a `diff=1`. So then: when can *i/we* participate in mining? after the mainnet starts? 

if you fork and you put +4.000 blocks on the chain within 10 hours, what will happen after this even if mainnet isn't on? you will still go on *mining* alone?

**Comment by StarbuckBG** [comment]
As the blocks will be accepted only by one node upon the start of the main net, anyone can run full node configuration and start mining as soon as the premining is completed.

**Comment by krtschmr** [comment]
and when is this? do you realize that people actually want to contribute but simply nothing is prepared? 
is my timeestimation correct for the premine?

**Comment by StarbuckBG** [comment]
We were forced to implement unplanned features and we’ve got non planned tasks. 
You can stay tuned on our site btcgpu.org <http://btcgpu.org/> and in twitter @bitcoingold we are posting every few hours.
The mining process will occur later in time not on the fork date.

**Comment by Tinkymon** [comment]
What will you guys to premine?

**Comment by oliverw** [comment]
> The idea of the premise is to be a couple of minutes? And the premised coins are 100k. 60% of them are time locked in a period of 3 years. 

Premise? Is that supposed to mean "premine"? Might not hurt your already damaged reputation to at least stick to known crypto terms instead of introducing more confusion by simple to catch spelling errors. 

> The LOC is being developed and will be publicly available for everyone also the address. 

Once again. What is LOC supposed to mean? "Lock"? Basic spell-checking should be doable. Do you agree? Thanks.

**Comment by StarbuckBG** [comment]
@oliverw it is premine, autocorrect. Sorry :/ I have answered this at about 5 AM my time.

**Comment by h4x3rotab** [comment]
it's done. close this issue
