### ISSUE TITLE
Inquiry on how to execute wallet data file in version v0.17.3

### ISSUE THREAD

**Issue by hyeongkoo** [BTCGPU/BTCGPU#420]
Please contact us.
In 2018, I installed the Bit Gold Wallet on my laptop and saved 500 BTG. Block renewal due to insufficient storage space was stopped.
Your Windows computer has encountered a problem. (Block update is stopped due to the use of 98% memory) So, I am trying to copy the data from my Bitcoin Gold wallet and wallet and transfer it to another computer. I do not know how to do it, so I will contact you. Any suggestion of a technical solution would be appreciated. Email:hyeong1248@gmail.com

**Comment by MentalNomad** [comment]
Enable pruning. (Settings, Options, Prune block storage.)
A full block history uses up about 150 GB. Reduce it to 50 GB or less and you should have space for the system to sync up.

Alternately, install v0.17.3 on a new computer, let it sync, and then copy your wallet.dat file from the old computer to the new.

For more help, come to our Discord, Telegram, or Forum to chat.
