### ISSUE TITLE
Pool.Gold

### ISSUE THREAD

**Issue by demkit** [BTCGPU/BTCGPU#423]
hi i dunno where to report this but **pool.gold** is actualy stealing from miners.....i had mined enough for payment like 2 weeks ago and amount dissapeared little by little

**Comment by MentalNomad** [comment]
No, it's not stealing. You're probably misunderstanding something about how the mining/maturation/payment system works - I suggest you go ask questions in the pool.gold support channel on the BTG Discord; pool.gold is active there.

**Comment by ZhiKosta** [comment]
Hello, please popup in to our support channel #pool-gold at BTG discord so we can explain better your misconception of what payment is and why you think you mined something but nothing was paid. Since this is an issue not related to the node itself, we'll be closing it.
