### ISSUE TITLE
Testnet

### ISSUE THREAD

**Issue by oliverw** [BTCGPU/BTCGPU#425]
Is the BTG testnet actually working? Syncing stays at 100% forever (progress 1.0).

**Comment by MentalNomad** [comment]
Testnet is working, but it's not always being mined when there are no transactions.

When there have been no blocks for 2 hours, the node will appear "stuck" at 100%. In reality, it is fully synced, but it does not report that it's fully synced until it receives a recently-mined block.

**Comment by oliverw** [comment]
Thanks. It just finished syncing after a couple hours.
