### ISSUE TITLE
Yobit starting BTG trading prior to launch date

### ISSUE THREAD

**Issue by D3m0nKingx** [BTCGPU/BTCGPU#45]
https://yobit.net/en/bitcoingold/timer/

How is this so?

**Comment by Coryvmcs1** [comment]
It's YobitI would expect nothing else from them but to do scamish things like this.

**Comment by D3m0nKingx** [comment]
To add to this... afaik at the time of the fork there will be 8,000 blocks "premined" = 100,000 BTG (in devs possession), thus the question is... how can exchanges possibly provide users with a 1:1 credit of BTG in their accounts when there's no actual coins existing besides what the devs are holding? because no further coins have been mined yet at that point?  

These coins just magically appear on the exchanges without having been mined into existence?

What would happen if most users tried to do a withdrawal of their BTG? Or is having btc on the exchange wallets trigger some code that in a sense creates the equivalent btg on the new chain (without mining) ?

**Comment by sammy007** [comment]
Yobit is a well known scam so who cares?

**Comment by D3m0nKingx** [comment]
https://www.bitfinex.com/trading/BTGBTC

trading is live

**Comment by John1231983** [comment]
It is the scam. Do not believe it. The code does not work now. Many features did not complete

**Comment by D3m0nKingx** [comment]
No kidding, it's basically just an IOU there... centralized exchanges don't need "wallets" to actually have any trading, it's just database numbers, not like a DEX such as Etherdelta

**Comment by John1231983** [comment]
@D3m0nKingx: You means I was wrong, Right? If it true, why BTC block is over but it does not HF.

**Comment by D3m0nKingx** [comment]
Good question, just like how the code says it was supposed to fork at block # 491314
https://github.com/BTCGPU/BTCGPU/blob/5a9f5b1d337babbbad53f787bc4914520266e1f0/src/chainparams.cpp#L88

**Comment by John1231983** [comment]
Now the block is over 491,407 but nothing happens. Do not believe the yobit which is a very small exchange and comes from CHINNA.

**Comment by sammy007** [comment]
@John1231983 yobit is a russian scam lol.

**Comment by D3m0nKingx** [comment]
Just sold BTGs on Binance :moneybag:

**Comment by StarbuckBG** [comment]
I will close this issue. More information can be found on BTG FAQ: https://btcgpu.org/faq/ and the roadmap: https://btcgpu.org/wp-content/uploads/2017/10/BitcoinGold-Roadmap.pdf
For discussion you shall use Slack: https://join.slack.com/t/bitcoin-gold/shared_invite/enQtMjYxMDU5NzQzNjUyLTJlODRhYjg2NGRmMzE4ZjBkZjlmOGM0ZDc0OGUyMDZmMTVlY2RjZDc2OWQ0NWY2NWI0ODcyZjYwZTVhMjQ5OTE
