### ISSUE TITLE
chain.cpp error when starting app.

### ISSUE THREAD

**Issue by marssystems** [BTCGPU/BTCGPU#453]
![image](https://github.com/BTCGPU/BTCGPU/assets/6579336/11f1d424-1448-4853-a84a-871f543ec845)

When starting Bitcoin Gold, I get this exception error.

Windows 11'

**Comment by MentalNomad** [comment]
Is this a fresh install, or just a restart of a partially synched node? Are you running a full transaction index by setting `txindex=1` in your `bitcoingold.conf` file?

It sounds like a corrupt database, and you may need to start the node with the ` -reindex` option.

Could you enable debug log output (by adding `debug=1` in the `bitcoingold.conf` configuration file), replicate the error, and then provide the contents of the `debug.log` file from before and after the error?

**Comment by marssystems** [comment]
This is a restart of my full node that has been running for a couple of years. Yes I have txindex=1 set.

**Comment by marssystems** [comment]
I have now started a full reindex of the blockchain as there is nothing happening with Bitcoin Gold, so it shouldn't take to long.
Once that is complete - tomorrow probably - I will shut down the node and restart it to see if the error is fixed.

**Comment by MentalNomad** [comment]
Any update?

**Comment by marssystems** [comment]
Yes - sure!  Did a full re-index - now back up and running.

Sorry for not updating earlier.

**Comment by marssystems** [comment]
All good now!
