### ISSUE TITLE
Add libsodium check in configure script

### ISSUE THREAD

**Issue by c0deright** [BTCGPU/BTCGPU#46]
### Describe the issue
configure script lacks a check for libsodium and libsodim-dev

#### If so, please list the steps to reproduce below:
1. download BTCGPU zip file from github
2. unzip file
3. apt-get purge libsodium-dev libsodium18
4. ./autogen.sh && ./configure && make

### Expected behaviour
configure complains about missing libsodium/libsodium-dev

### Actual behaviour
configure runs fine, `make` crashes with:

```
  CXX      crypto/libbitcoinconsensus_la-aes.lo
In file included from crypto/aes.cpp:6:0:
./crypto/common.h:16:20: fatal error: sodium.h: No such file or directory
compilation terminated.
```

### What version of are you using?
bitcon-gpu-master-2f5fe4c15bb88596e7edbbda5ad702d8c075c4b7

### Machine specs:
Ubuntu Xenial (16.04 LTS) on AWS EC2 instance type `t2.small`

**Comment by jagottsicher** [comment]
on Ubuntu 14.04 I had to compile libsodium on my own ([https://download.libsodium.org/doc/installation/](https://download.libsodium.org/doc/installation/) and eventually compile with --no-shared

**Comment by StarbuckBG** [comment]
Could you guys upload steps to build this to the /doc/unix-build file?

**Comment by LunarExplorer** [comment]
resolution is apt-get install -y libsodium-dev please confirm.

**Comment by jagottsicher** [comment]
If compiling doesn't work afterwards, you need to deinstall and compile libsodium from the scratch.

**Comment by vattay** [comment]
I *highly* recommend using the [./depends ](https://github.com/BTCGPU/BTCGPU/tree/master/depends) system to grab your dependencies if you can. The docs and distribution repos are not up to date with this. I wasted hours on dependency hell until I used this. 

I have an example Docker container that build and tests cleanly, use the [Dockerfile](https://github.com/vattay/btcgpu-docker/blob/master/Dockerfile) as a reference point if you want to use this method.

**Comment by jagottsicher** [comment]
I just added it to the /doc/unix and will take care to implement it into ./depends

**Comment by c0deright** [comment]
It's best practice that ./configure should complain if not the right version of libsodium is found on the system. It's a bad decision to let the user compile btcgold with a library installed incompatible with the code resulting in a binary that segfaults/crashes right away.

Please update the configure stuff to only allow compiling with the right version of the lib installed.

It only adds confusion when configure runs smoothly and the built binaries crash nevertheless.

**Comment by 0z4ck** [comment]
I still get the same error even though I did
```cd ./depend&&make```
I'm on Centos6.9. Any solution ?

**Comment by h4x3rotab** [comment]
Have you specified -prefix flag when running configuration? It’s recommended to follow this guide to compile: https://bitcoingold.org/wp-content/uploads/2017/11/Bitcoin-Gold-Testnet-Participation-Manual.pdf
