### ISSUE TITLE
Add Bitcoin Gold to Electrum

### ISSUE THREAD

**Issue by leto** [BTCGPU/BTCGPU#48]
### Describe the issue

Electrum does not support Bitcoin Gold.

#### If so, please list the steps to reproduce below:
1. Observe
2. No
3. Support

### Expected behaviour

Electrum should support Bitcoin Gold.

### Actual behaviour

No support.

### Details

Add Bitcoin Gold to Electrum, which requires changing both the ElectrumX client, which supports multiple cryptocoins (not the horrible BCH fork stuff which doesn't work) and the Electrum server to talk to the correct BTG nodes and make any protocol changes.  This will include a test suite, developer documentation and end user documentation for using BTG via Electrum.

## Bounty

250BTG

Bonus Bounty: 50BTG if this is merged before the launch of mainnet (currently planned for Nov 1st)

**Comment by StarbuckBG** [comment]
Hello!

As the price in the exchanges is between 0.04 and 0.06 BTC per BTG the bounty for solving this issue is 250 BTG (currently about 12.5 BTC). The solution must be well documented, clear to be understood and correctly working. 

In case this task is done before the start of the mainnet there is 50 BTG bonus to the reward (that makes 300 BTG). 

Thanks for all of the support to the project!

**Comment by leto** [comment]
@StarbuckBG I think with the bonus that it sounds reasonable, so I will accept the bounty amounts you listed. I updated the original issue description with the new bounty amounts. :+1:

**Comment by StarbuckBG** [comment]
Thanks for the awesome work and all the help @leto !
Highly appreciated!

**Comment by leto** [comment]
:+1: teamwork 😺

**Comment by cifer-lee** [comment]
great work! so how the solution going now?

**Comment by leto** [comment]
This is in progress, and depends on many other things to test correctly, such as a testnet and finalizing the new address format: https://github.com/BTCGPU/BTCGPU/issues/17 I will be pushing things to my fork of BTG and submitting PR's. Will update this issue when there is something to look at 😃

**Comment by StarbuckBG** [comment]
Nice to hear that!
Keep up the good work!

**Comment by ingamx** [comment]
New girl is in Town. leto how far along are you?

**Comment by btcgoldtrezor1** [comment]
Will Bitcoin Gold Electrum support trezor signing for TXs? 

Trezor claim tool...makes u combine all OUTPUTS...with electrum coin control can send 1 by 1 so please MAKE SURE TREZOR WORKS with Bitcoin Gold Electrum!!!

**Comment by jcserracampos** [comment]
How are this going?

**Comment by jhabdas** [comment]
For all the eager puppies waiting, just keep waiting. But wait patiently. The most you interrupt the development process the longer it's going to take. 😉

**Comment by thomasforde** [comment]
BTG Electrum Gold released https://www.electrum-gold.org

**Comment by h4x3rotab** [comment]
@thomasforde Looks like a scam

**Comment by D3m0nKingx** [comment]
@h4x3rotab @thomasforde no source code? no source = scam

**Comment by D3m0nKingx** [comment]
and the file name is called "electron"-gold... RED FLAG

https://github.com/szybkipc/electrumgold/releases/download/v2.9.3/electron-gold-2.9.3.zip

Source code zip file is bullshit too... just a readme file LOL

**Comment by DocSnyd3r2** [comment]
Virus total already flagged this https://www.virustotal.com/de/file/617a13293dd1824083dbf5de96d11821bf010d0a2b1399ebb0f51d25837b9584/analysis/

**Comment by thomasforde** [comment]
Apologies, someone hijacked my github account and made those posts..

**Comment by onpars** [comment]
electrum-gold dot org is probably a scam, right? Source code links to https://github.com/ which is a joke.

**Comment by jhabdas** [comment]
Please try and keep the noise down for code followers. Follow official Twitter and Telegram chat for updates. Commits should be verified with GPG encryption.

**Comment by DocSnyd3r2** [comment]
Is there a repo available to track progress?

**Comment by jhabdas** [comment]
@DocSnyd3r2 according to an answer to a question on the official Bgold Reddit if your coins were in your Electrum wallet at the time of the snapshot you can move your Bitcoin wherever you please and collect later when this issue tracking the progress is finished.

**Comment by DocSnyd3r2** [comment]
Thanks, I know but I would like to audit the code changes of the new wallet before that.

**Comment by zdzislaw** [comment]
Hello,
I wonder if they still need this feature to be developed?
Thanks.

**Comment by mysmsbiz** [comment]
You can use the Electrum Gold wallet for bitcoin gold  https://www.electrum-gold.org

**Comment by vattay** [comment]
@mysmsbiz SCAM SCAM SCAM

**Comment by JoelBradley** [comment]
Electrum Gold https://www.electrum-gold.org

**Comment by drandreaskrueger** [comment]
> Electrum Gold https://www.electrum-gold.org

thanks. but is that safe?

it is not mentioned on their [homepage](https://bitcoingold.org/)

**Comment by DocSnyd3r2** [comment]
**STAY AWAY It is a SCAM!!!**

**Comment by JoelBradley** [comment]
I obviously didn't post that comment. Any idea how the scam enabled them to log into my github and what I need to remove from my system to prevent anything further?

**Comment by drandreaskrueger** [comment]
good to know, thanks.

when will the electrum version for BTG be ready?

**Comment by EagleTM** [comment]
Anyone working on this? I don't think so?

**Comment by evadogstar** [comment]
It's nice that it was NOT released  on start, because everybody want to dump and sell there coins. We mast first get stable mining.

**Comment by mmmmyah** [comment]
Any updates on this - does electrum support bitcoin gold yet? thanks

**Comment by poordude** [comment]
its opposite of nice that there is no light wallet for windows for btg.
people lost (not me) money trying to claim btg on various fake btg sites.

**Comment by poordude** [comment]
There is still not even 1 working windows light wallet for this coin
And there is no way to stop this scam marathon of fake ones.
https://bitcointalk.org/index.php?topic=2396143.0;topicseen
even one that is posted on main page of coin is now suspicious and not working.
so don't even try to use it.

**Comment by leto** [comment]
ElectrumX now has Bitcoin Gold support via Coinomi: https://github.com/kyuupichan/electrumx/commit/f3fea9f8ee88305aa087bb996a3d1857708b3a20

**Comment by ingamx** [comment]
hmm

*Inga Bemman*

**Comment by darthginger** [comment]
@leto ok the server part of Electrum (ElectrumX) has BTG support but where is the client? And if there is no client, why close the issue?

**Comment by 2000lux** [comment]
https://github.com/2000lux/electrum-gold

**Comment by btgold** [comment]
> @leto ok the server part of Electrum (ElectrumX) has BTG support but where is the client? And if there is no client, why close the issue?

Yes, yes, where is easy download electrum for btc gold? srsly???

**Comment by StarbuckBG** [comment]
Here is electrum server - 46.101.156.130. Standard ports.

**Comment by btgold** [comment]
@StarbuckBG appreciate help but can u explain how to connect. which softwares is downloaded and then connected to this server u post?

**Comment by StarbuckBG** [comment]
Someone needs to modify the electrum client in order to support BTG. I’m not a python developer and it is hard for me as there are a lot of external modules and classes. However the server and the sync are the part that takes most of the time. You need about a week to sync the DB on the electrum server. On the link given it is already synched and can be tested.

**Comment by btgold** [comment]
@StarbuckBG thanks for answer...so then why u electrum team close this pull? there no wallet for me to download and use...

@StarbuckBG me and newbs we can not sync DB on electrum server it very hard.....

@leto maybe can u make easy download electrum gold that will connects to 46.101.156.130

**Comment by StarbuckBG** [comment]
Actually Duke has closed this ticket. I can reopen it by your request ?

**Comment by mmmmyah** [comment]
The ticket needs to remain open until there is a viable electrum client that supports Bitcoin Gold. Also there are upcoming forks that will have similar asks (Bitcoin Diamond, Super Bitcoin, Bitcoin 2x second attempt) so I suggest those be accounted for in separate tickets for each as well.. someone needs to loop in support@btcgpu.org for awareness as well on this ticket. I see @leto was the last person who looking into the BTG support in the electrum client for the bounty? Can we get an updated status please on this effort. Thanks so much guys!!

**Comment by Ayms** [comment]
See https://github.com/Ayms/bitcoin-transactions (+ https://github.com/Ayms/bitcoin-wallets)

Wallets are easy but dangerous you don't need them to manage things by your own

**Comment by 2000lux** [comment]
Im doing research on BTG protocol, soon i can ship a ELECTRON-GOLD, but will anyone support my work ? im scared that my work will be put on trash

**Comment by movingelectrons** [comment]
whats the current status on this project?  Anyone working on it?  If not, or if help is needed/wanted, I would like to program this feature.  2000lux, have you made any progress?

**Comment by murtyBCI** [comment]
Is the bounty still on the table or did someone close the deal? Can BTG team answer yes/no... If no, I can do this and I can really use money now for some long overdue bills

**Comment by eqjjh** [comment]
This issue was closed. Needs to be reopened if it has not been resolved - which is a lightweight wallet for bitcoin gold.
