### ISSUE TITLE
building static files under linux without the needs of system-boost-files, etc. failed

### ISSUE THREAD

**Issue by Himan2001** [BTCGPU/BTCGPU#53]
One simple question, not answered between all the (mostly async and/or outdated) doc-files:

What are the exact ./configure commands and FLAGs to just build EVERYTHING static
under Ubuntu 16.04? Means: No dependencies to system-boost-libs and other libs ?
...by using the stock (system+dev-)files that comes with ubuntu 16.04

Simple things like "--disable-shared --enable-static" results only in "half" static binarys, where boost
and other libs are still needed...

**Comment by jagottsicher** [comment]
I compiled on ubuntu 14.04 with the following command:
`./configure CPPFLAGS="-I${BDB_PREFIX}/include/ -O2" LDFLAGS="-L${BDB_PREFIX}/lib/" --without-gui --disable-shared`, but had an issue before to let libsodium be provided.

**Comment by Himan2001** [comment]
can you try ldd <binary> and take a look for any remaining boost shared libs ?
with or without -gui... every binary needs the system boost shared libs and this dependenacys i like to solve, so that the resulting files are no longer system-boost dependend. libdb is always static included on the other hand.

**Comment by jagottsicher** [comment]
If you need it completely static maybe this can help[https://bitcointalk.org/index.php?topic=1636271.0](https://bitcointalk.org/index.php?topic=1636271.0)

**Comment by Himan2001** [comment]
Thx, that link helps a lot.

A Request to the developers:
Please remove the often outdated files from the docs/contrib dirs, and provide a litte more updated documentation. There are so much changes in actual codebases, that the usual copy&paste from many 2015/2016 files are not very useful - because reading more files - they often contains different
informations. It makes really sense, that things like entire static-build for any system are little better covered by the how-to files.

The thing with using the very old db4.8, not actual 6.2-release is another open question for me.
Docs talk about portability for wallet.dat between linux and windows - but why not build windows AND linux against actual code ? - Then the files are interchangeable again...

**Comment by jagottsicher** [comment]
I guess you can exchange the wallet.dat between different OS anyway - no need to cross-compile the code for that feature. at least not from my experience with other cryptos, e.g. BTC.
and for sure people are invited to cross-compile for windows, linux and  osX against the same code. or do you mean in particular to make everything linked statically?

**Comment by Himan2001** [comment]
I first think, using db-6.2x, like other altcoins, for all platforms makes some sense. libsodium ist newer as any existing "stable" system - on the other hand, libdb is outdated a few years. When there is a new fork with a new algo, i think it is a good time to build all with some +/- nearly actual used libs ;-)

Because of the static things: like i read in the bitcointalk-thread. When you not make the "maximum" static as possible for the "official binary client" - your always found another "CentOS, RedHat, Suse or whatever user with another glibc or something else outdated".

For Windows: always static as 32 and 64bit Version. Absolutely no extra .dll dependencys.
But: Not just the usual windows-qt.exe - complete means the +goldd.exe and the cli-tools for (dos)-completeness, too ;-)

For the PowerUsers, there will self build the "absolutely optimized" Version, a little better documentation with useful ACTUAL setting-combinations is a good idea. Things like "-O3" and no debug at all is a default change for my own buildings on linux usualy.

I found on some miners (cc-miner, etc.) and Altcoins a little better solution for the Quickstarters:

a.) a file "autogen.sh" - which make the basic work with autoreconf, autogen, etc.
b.) a "build.sh" which have in front some #remarks for useful CFLAGS, etc. Then the part with the clean, a well formatted ./configure and after them the "make -j<proc>" autodectect function for parallel builds.

This way, a regular user can download the source-tarball and open the "build.sh". He found here all importent defaults and short-infos, without the need to search the entire /doc and /contrib folders, where often "bitcoin" instead "bgold" is refferenced (+many outdated code infos from older BitcoinCore...)

**Comment by bilbobits** [comment]
Most of the problems reported here are related to the build, which are all from the simple fact that nobody took the time to write a README.md that explained the dependency's, and exact cmd-line's required to build.

There are about six major hard walls you hit in this build, and only 1/2 is getting the compile,after that there are 2-3 more segmentation faults that you have to get over.

Then once you run the code, it does nothing as there is no DNS for peers, nor is there a testnet for testing miners, or wallets.

What were the people running and funding this project thinking? Is/Was the money already made/paid by the post Oct 20 exchange launch? It's clear now the dev's are just in panic mode to shutdown the truth tellers.

Did the entire BITCOIN Exchange community collude in this BTC-G "FORK"???

A couple exchanges refused to list BTC-G because the code was not released, they didn't want to release this code, and now we know why, because it doesn't exist.

**Comment by h4x3rotab** [comment]
I guess this issue is obsolete. #46 tracks the process to check libsodium version.
Feel free to reopen if the issue still exists.
