### ISSUE TITLE
Wallet crashes right after launch with assertion failed

### ISSUE THREAD

**Issue by ocminer** [BTCGPU/BTCGPU#57]
Crashes right after launch:

src/bgoldd -daemon
bgoldd: crypto/common.h:138: int init_and_check_sodium(): Assertion `crypto_sign_verify_detached(sig, message, sizeof(message), pk) != 0' failed.
Segmentation fault (Core dumped)

**Comment by StarbuckBG** [comment]
duplicates #43

**Comment by Himan2001** [comment]
do this steps before autoconf.sh/.configure, etc:

cd depends
make
cd ..

and you can try with this settings:

./autogen.sh
./configure \
    --with-daemon \
    --with-utils \
    --with-gui=auto \
    --without-libs \
    --disable-shared \
    --disable-tests \
    --disable-bench \
    --enable-reduce-exports \
    --enable-glibc-back-compat \
    --prefix=`pwd`/depends/x86_64-pc-linux-gnu \
    LDFLAGS="-static-libstdc++"

make

for me, this results in the most compatible binarys for now.

**Comment by c0deright** [comment]
Please see https://github.com/BTCGPU/BTCGPU/issues/43#issuecomment-338683228 for a workaround on Ubuntu 16.04 Xenial.
