### ISSUE TITLE
Timelock mechanism not implemented

### ISSUE THREAD

**Issue by StarbuckBG** [BTCGPU/BTCGPU#58]
Timelock mechanism must be implemented for the launch of the project. 

As discussed 60% of the premine must be released on a fixed period of time, proportionately on the next 3 years. 
This is being used for the development of the project.

**Comment by brutr** [comment]
I think all you need is the following script to generate several P2SH addresses and use them in coinbase transactions while premining:

```
<expiry time> CHECKLOCKTIMEVERIFY DROP
2 <Alice's pubkey> <Bob's pubkey> <Lenny's pubkey> 3 CHECKMULTISIG
```

It is up to you to choose parameters of multisignature scheme (M-of-N) but there are some limitations:

https://bitcoin.stackexchange.com/questions/23893/what-are-the-limits-of-m-and-n-in-m-of-n-multisig-addresses

**Comment by h4x3rotab** [comment]
@brutr Thank you. I think this works well. We should add block validation logic to enforce the time lock rule.

**Comment by h4x3rotab** [comment]
Done #168
