### ISSUE TITLE
Can't compile the code.

### ISSUE THREAD

**Issue by vogelito** [BTCGPU/BTCGPU#60]
Code doesn't even compile....

Your own build says it's failing...

Aren't you forking in roughly 27 hours? What's the deal?

![image uploaded from ios 1](https://user-images.githubusercontent.com/1325863/31870030-52c541c6-b771-11e7-863d-fd6fc13d8912.png)

**Comment by zbarge** [comment]
I've read through most of these issues. I have to say this is pretty crazy. It may be in the best interest of the community for the BTG team to let everyone know that the fork needs to be delayed. This appears to be a very unsafe project to launch right now. 

- someone who's 2 cents probably don't matter.

**Comment by gau27** [comment]
Unless you guys have a hidden dev branch, don't you think it's unreasonable to launch on October 25th even if you muscle up all the code before then? 

Even h4x3rotab's fork https://github.com/h4x3rotab/BTCGPU has build errors even though the last commit was... "Fix build errors". 

Just my opinion, but surely you guys are aware the market is up on optimism over BTG especially with confidence that the fork will happen on 25th October as planned. I'm interested to know if the team is still confident of forking on schedule, and if you aren't (I wouldn't be) you should really let it out on your public channels.

**Comment by StarbuckBG** [comment]
The fork happens on schedule. The main net will be released after the fork.

**Comment by ethan-nx** [comment]
The code compiles without an issue on my Arch Linux exactly the same way Bitcoin Core does:

```
./autogen.sh
./configure --without-gui --with-incompatible-bdb
./make
```
Just make sure you have all the dependencies installed.

Cheers,
Ethan

**Comment by sammy007** [comment]
I can compile on Xenial, but can't launch:

```
bgoldd: crypto/common.h:138: int init_and_check_sodium(): Assertion `crypto_sign_verify_detached(sig, message, sizeof(message), pk) != 0' failed.
Aborted (core dumped)
```

**Comment by ocminer** [comment]
@sammy007 thats a duplicate, your libsodium is out of date

**Comment by c0deright** [comment]
@sammy007 

Please see https://github.com/BTCGPU/BTCGPU/issues/43#issuecomment-338683228 for a workaround on Ubuntu 16.04 Xenial.

**Comment by sammy007** [comment]
I just uninstalled `libsodium-dev` and `libsodium18` and installed it from git to `/usr/local` also works. Thanks for `.deb` hint @c0deright.

**Comment by gau27** [comment]
@StarbuckBG Thanks for the clarification, I was not aware of that

**Comment by ethan-nx** [comment]
![fork](https://i.pinimg.com/736x/d9/ea/63/d9ea63cd36aa551742a93b8bcae71b87--forks-just-because.jpg)

**Comment by shamoons** [comment]
What version of g++ is needed?

**Comment by jagottsicher** [comment]
@shamoons 
`gcc --version
gcc (Ubuntu 4.8.5-2ubuntu1~14.04.1) 4.8.5
`
Also I recommend:
`sudo apt-get install build-essential
wget http://download.oracle.com/berkeley-db/db-4.8.30.NC.tar.gz
echo '12edc0df75bf9abd7f82f821795bcee50f42cb2e5f76a6a281b85732798364ef  db-4.8.30.NC.tar.gz' | sha256sum -c`
then compile it on your own:
`tar -xvf db-4.8.30.NC.tar.gz
cd db-4.8.30.NC/build_unix
mkdir -p build
BDB_PREFIX=$(pwd)/build
../dist/configure --disable-shared --enable-cxx --with-pic --prefix=$BDB_PREFIX
make install
cd ../..`
rest of dependencies you can solve with 
`sudo apt-get install autoconf libboost-all-dev libssl-dev libprotobuf-dev protobuf-compiler libqt4-dev libqrencode-dev libtool`

If while compiling BTCGPU you run into the error of missing libsodium you also have to compile,
see my comment in #43, which solves that problem. 
Enjoy! :-)
