### ISSUE TITLE
no testnet nodes

### ISSUE THREAD

**Issue by ocminer** [BTCGPU/BTCGPU#63]
there aren't any public testnet nodes to connect to, the dnsseed nodes are not working

**Comment by StarbuckBG** [comment]
testnet is WIP. You can connect manually to eu-node.bitcoingold-official.org . DNSSeed is eu-test-dnsseed.bitcoingold-official.org

**Comment by StarbuckBG** [comment]
#36 #39

**Comment by Coryvmcs1** [comment]
Even with these connected manually it will not download blocks.

**Comment by ocminer** [comment]
Works here, thx

**Comment by Coryvmcs1** [comment]
@ocminer were you able to download the blocks ?

**Comment by Coryvmcs1** [comment]
I am not able to download the blocks

http://prntscr.com/h0xzi9

**Comment by ocminer** [comment]
Check #36 and #39

**Comment by Coryvmcs1** [comment]
@ocminer so you got all blocks synced up and testnet is working now from that ?

**Comment by adhood** [comment]
Please see #39 

It appears there is no testnet or mainnet at the moment and the Bitcoin Gold team is providing a bounty for whoever wants to create it for them.

**Comment by jagottsicher** [comment]
I added 2 nodes only, no more connections are made, but seems I downloaded some blocks, diff changed already and the testnet is working, or?
``"version": 150001,
  "protocolversion": 70016,
  "walletversion": 139900,
  "balance": 0.00000000,
  "blocks": 29617,
  "timeoffset": 0,
  "connections": 2,
  "proxy": "",
  "difficulty": 13.5887641541527,
  "testnet": true,
  "keypoololdest": 1508480357,
  "keypoolsize": 2000,
  "paytxfee": 0.00000000,
  "relayfee": 0.00001000,
  "errors": ""
}`

seems working. 
But what about dnsseeds - I don't want to stay connected to 2 nodes only.

**Comment by StarbuckBG** [comment]
Which ports are you using? 
Please use this fork for the testnet: https://github.com/StarbuckBG/BTCGPU <https://github.com/StarbuckBG/BTCGPU>
I will add the changes to the DNSSeeds in a couple of minutes and rise them again.

**Comment by jagottsicher** [comment]
@StarbuckBG took your fork, compiled, start with -reindex and have 1 connection, 0 blocks now.
as I see, from -getnetworkinfo I am using Port 18338 now. 

Anyway wished for some more friends in this testnet - some lonely here.

**Comment by StarbuckBG** [comment]
I will start the nodes as soon as I get my first coffee, 3 hours of sleep are not enough :(

**Comment by cryptokat** [comment]
`eu-test-dnsseed.bitcoingold-official.org` is still not up

**Comment by StarbuckBG** [comment]
It is up, please ping and check.

**Comment by cryptokat** [comment]
@StarbuckBG There isn't even an A record returning from DNS...

https://www.digwebinterface.com/?hostnames=eu-test-dnsseed.bitcoingold-official.org&type=&ns=resolver&useresolver=8.8.8.8&nameservers=

**Comment by jagottsicher** [comment]
` ping eu-test-dnsseed.bitcoingold-official.org
ping: unknown host eu-test-dnsseed.bitcoingold-official.org
`
all other resolver I testet also schowed no entry A-record or anything. Io idea why google does. my node can't make a connection to.

by the way: I have no connections anymore and never downloaded a block.

**Comment by StarbuckBG** [comment]
You cannot ping a namespace (;

Here is the IP: 46.101.153.138

Screenshot of DNS:

**Comment by jagottsicher** [comment]
46.101.153.138 up and returning pong, but resolver can't find the name.
[http://dnscheck.pingdom.com/?domain=eu-test-dnsseed.bitcoingold-official.org](http://dnscheck.pingdom.com/?domain=eu-test-dnsseed.bitcoingold-official.org) (example)

**Comment by StarbuckBG** [comment]
The resolver is a namespace entry (NS). You must use it as a DNS.
It is hardcoded in the code, but you can add the seed to point to this address and everything will be cool!

**Comment by jagottsicher** [comment]
I clone your repository and build a new client/node. So everything should already be in, or? I started the node, but still no connections. also I grep in all files in the rep for eu-test-dnsseed.b 
and found it many times, so it is in the code. 

I think the server is up and running, and the clinet knows about it, but can't make connection. anyway i think it is a client problem, maybe on the machine I am working, so I need a solution to rule out that the connection to the seeding server is blocked. any idea?

**Comment by StarbuckBG** [comment]
I met the Sami problem upon starting node client on a new machine. I’m investigating.

**Comment by StarbuckBG** [comment]
blockchain downloads fine with the changes from my PR #49

**Comment by evgenyundefined** [comment]
make fresh build from github try start testnet but dnsseeds response 0 addresses and daemon not start sync. what i doing wrong?
```
2017-11-02 09:21:05 dnsseed thread start
2017-11-02 09:21:05 Loading addresses from DNS seeds (could take a while)
2017-11-02 09:21:05 net thread start
2017-11-02 09:21:05 addcon thread start
2017-11-02 09:21:05 init message: Done loading
2017-11-02 09:21:05 opencon thread start
2017-11-02 09:21:05 msghand thread start
2017-11-02 09:21:05 0 addresses found from DNS seeds
2017-11-02 09:21:05 dnsseed thread exit
2017-11-02 09:22:06 Adding fixed seed nodes as DNS doesn't seem to be available.
```

Daemon config
```
testnet=1
server=1
rpcuser=testuser
rpcpassword=testpass
rpcport=19701
```
try add in config but same problem not start sync
```
addnode=46.101.153.138
addnode=eu-test-dnsseed.bitcoingold-official.org
addnode=btg.dnsseed.minertopia.org
```

**Comment by evgenyundefined** [comment]
Yeaaaaaayyy dnsseeds for testnet now alive! Thanks!

**Comment by evgenyundefined** [comment]
i no add specefic nodes, build daemon with last changes and him start sync. start daemon without config file only with console argument testnet

**Comment by oliverw** [comment]
@evgenyundefined Interesting. Thanks for the info!

**Comment by StarbuckBG** [comment]
Guys, I will close this. If needed add a comment and we can reopen it. Thanks for all the support!

**Comment by sleepndevelop** [comment]
hello,
i've put this in my config but my testnet btg wallet is not connecting to any peers

addnode=46.101.153.138
addnode=eu-test-dnsseed.bitcoingold-official.org
addnode=btg.dnsseed.minertopia.org

**Comment by h4x3rotab** [comment]
I’m working on the new diff algo. After that the testnet will be reset. Currently there’s no working testnet.
