### ISSUE TITLE
Block explorer

### ISSUE THREAD

**Issue by jyap808** [BTCGPU/BTCGPU#67]
Please make sure you set up a block explorer for you Testnet and Mainnet.

**Comment by barrystyle** [comment]
why have you logged this as an issue?

**Comment by anthony19114** [comment]
If it doesn't exist, its an issue.. and it doesn't.

**Comment by barrystyle** [comment]
Anyone is free to setup a blockexplorer for BitcoinGold; not dev teams's responsibility.

**Comment by lacksfish** [comment]
From the README.md    
> Bitcoin Gold is a work in progress. If you don’t understand what you are doing, please don’t compile and run your own client from the staging tree. Your own client will NOT WORK. However, you're more than welcome to help test the code and join the development.

So what should a dev base the blockchain data of? No recommended client exists and the fork happened. It's the devs now mining their premine before launching publicly... sad sad sad.

**Comment by ed-ro0t** [comment]
first 16k blocks at min diff

**Comment by leto** [comment]
I consider it essential for a cryptocoin to run at least one block explorer for mainnet and testnet (more than that is fine, like ones on Tor/etc). If the core BTG team doesn't want to take on running a Block Explorer, maybe running a full altcoin mainnet is too much as well. This needs to be funded from the pre-mine, otherwise, this is irresponsible and greedy and just plain Not Cool.

**Comment by DarthJahus** [comment]
> stand up a BitcoinGold node and a block explorer?

@barrystyle, yeah, maybe after they release a proper wallet. Actually, no nodes, so no blockchain, and no block explorer.

**Comment by barrystyle** [comment]
@DarthJahus the code they've released here compiles fine.. after the 8000 block premine from block 491,407 is done, they'll make their chain public, and you'll be able to run it through a block explorer..

**Comment by jagottsicher** [comment]
at diff 1 the premining should be done already, but it suddenly became more and more calm. 
official start shall be november 1st, so we have to wait until then to start developing a block explorer?

**Comment by barrystyle** [comment]
@jagottsicher Just checked pow.cpp (didn't realise that they'd adjusted to per block retargetting for Equihash) and you're 100% correct. However any existing block explorer could be used without issue.

**Comment by jagottsicher** [comment]
@barrystyle u r right. I'm checking this one here: [https://github.com/Shadouts/PiNode](https://github.com/Shadouts/PiNode)

**Comment by vattay** [comment]
Simple iquidus blockchain explorer is up, running on regtest single node. I will add testnet and mainnet as they come online. http://element79.io

**Comment by DarthJahus** [comment]
@vattay, good work, there.

Are you going to index blocks since the snapshot, right? (first block would be 1 instead of 491407).

And actually, I see no ads, which is great. You should add a donation button at the bottom.

**Comment by evgenyundefined** [comment]
https://btgexp.com Now work with testnet.

**Comment by h4x3rotab** [comment]
Mainnet explorers:
btgexplorer.com
btgblocks.com
btgexp.com
btg-bitcore2.trezor.io

Testnet explorer: no. We will reset testnet soon and then we will try to bring up a testnet explorer.
