### ISSUE TITLE
BTCGPU BTG Wallet

### ISSUE THREAD

**Issue by minibitz** [BTCGPU/BTCGPU#77]
Hi, 

I can't deposit to any exchanges and there are no wallets that let me withdraw the funds. When can we expect a wallet for trading? 

-mini

This issue tracker is only for technical issues related to bitcoin-core.

General bitcoin questions and/or support requests and are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).

For reporting security issues, please see the official [Bitcoin Gold website](https://btcgpu.org/).

### Describe the issue

No way to withdraw / sell / deposit funds

**Comment by leto** [comment]
There will be a command-line wallet and QT wallet that comes with the core codebase, I believe. I am a bounty developer working on BTG support in Electrum: https://github.com/BTCGPU/BTCGPU/issues/48

**Comment by adhood** [comment]
Bitcoin Gold has not launched yet. The only thing that has happened so far is a snapshot of the Bitcoin blockchain was taken for future use with Bitcoin Gold.

There are no wallets because there isn't even a mainnet coded yet. Everything is still in very early stages of development.

**Comment by kgantchev** [comment]
So how are the exchanges crediting Bitcoin gold wallets?

**Comment by Jrrgimenezz** [comment]
@kgantchev they're off-chain operations, not working under BTG blockchain

**Comment by leto** [comment]
@kgantchev  ![hopes dreams meme - google search 2017-10-24 12-47-05](https://user-images.githubusercontent.com/30298/31964605-7433fa7a-b8b9-11e7-805c-cad4fff366bf.png)

They are promising IOUs in a SQL database. If they lose their records, there is no actual record of any of that on the Blockchain. I am sure various attackers have that in mind, if they want to erase these "fantasy transactions" from ever getting to a real blockchain.

OH YEAH, the address format is going to change, and keeping track of all these xtns between the fork date and the mainnet launch date, that is going to be REAL FUN to watch 😺

**Comment by John-Dass** [comment]
Hi!, if you want know your btg balance can check my open source website https://getbitcoingold.io

**Comment by StarbuckBG** [comment]
You have self signed or self modified certificate?
Could you please give a bit more info?

**Comment by StarbuckBG** [comment]
And the URL is a bit scammy :/
As the private keys are on the site this puts a lot of users at risk.

**Comment by John-Dass** [comment]
Hi, everyting happen in the browser of the user. You can check the code for see it!, its based on BitcoinJS like lot of tools in Bitcoin (Ian Coleman tool for example). We can said, the btg wallet its a fork of BitcoinJS.

**Comment by John-Dass** [comment]
Please... dont said Scam without see the code, its ofensive.

Everything happen in the user side and the only info sended its the address to two internet api with real confidence for check balances...

Yeah, the design its not good but i was working free for this... Anyway, in a near future i will update the design when the nodes and bitcoin gold its working (i want mount a node for the users can broadcast the transactions), but like i said... everything happen in the browser of the user, except the user have a malware or keylogger in his computer everything is safe.

**Comment by StarbuckBG** [comment]
As I have said it looks. I’m sure that it is not scam :) 
The idea is nice I could have a look on the code.

**Comment by John-Dass** [comment]
Thanks. I would appreciate a review =). If you think i can change something, just said!. I'm sure this weekend have free time to improve the design and other things.

Have some idea from where i can obtaing a more precise balance of btg ? The only idea that came to mind was search the blockcypher api and see the balance with X confirmations (Where X it's Actual Block - 491407). If you thing in a best idea... I'm listening!

**Comment by Technophant** [comment]
John-Dass, you joined two days ago with no other project.  I downloaded your code and used it offline and it doesn't work! It showed my correct current zero balance but not the correct block height balance. What assurances does anybody have that your website has the same code that you have here?  Can somebody please check over this to see that my seed didn't get sent somewhere? It seems to access blockcypher.com and  blockchain.info in application.js.

**Comment by Technophant** [comment]
I ran some tools and that's the only two sites it accesses, but the question still remains, why should we trust you? There's no way to check the code on your website.  There's another scam online wallet identified on bitcointalk: btgolds.org

**Comment by TheComputerGenie** [comment]
@StarbuckBG commented

> And the URL is a bit scammy :/

I believe this to be a good example of irony.

**Comment by StarbuckBG** [comment]
What is your problem ?

**Comment by Technophant** [comment]
Chrome is ok with the certificate but Firefox says SSL_ERROR_BAD_CERT_DOMAIN.  It's a bip39 decoder however Electrum is different so that's why it didn't work.  I _think_ the motives of the author are good but yes, quite sketchy.

**Comment by Technophant** [comment]
I think JohnDass and StarbuckBG are the same person.  Look at the grammar.

**Comment by jhabdas** [comment]
I took a quick peek at the project @John-Dass code links to and can say with confidence they're not a JS developer, probably copied most of that code from another project and either don't know how to use GitHub or are doing something shady, especially given `node_modules` and minified code have been checked into that repo.

**Comment by John-Dass** [comment]
@jhabdas Hi, that it's right. Im not a experience developer in anything, but i know everything. If you see a little more the website you can check the "Libraries and Credits" and it's said that. Its a little fork so we can use this for BTG.

@Technophant You have right too. When i change some things, i will update the code helping the user to select the correct path for seeds (Bip44 / Bip39).

Thanks for the review to everyone! If have some idea, im listing! Not a closed person here.

**Comment by Technophant** [comment]
This could be a separate issue but I'll put it here. There is a snapshot ledger of the "golden block" #491407 available for offline use. Would be nice if it was in several different database formats.

**Comment by jhabdas** [comment]
This issue wasn’t closed by commit. Is this complete @h4x3rotab?

**Comment by D3m0nKingx** [comment]
This issue has nothing in which requires a commit @jhabdas hence why it was closed. The issue started here was:

> I can't deposit to any exchanges and there are no wallets that let me withdraw the funds. When can we expect a wallet for trading?

This has nothing to do with the repo, that is question to be directed to an exchange, not here.

**Comment by jhabdas** [comment]
Hey be nice. This is the Internet you know. 😽  It’s customary to give others the benefit of the doubt and always a good idea to drop some 411 when closing issues. FWIW I thought this was the Electron wallet issue.
