### ISSUE TITLE
Problem with BTC WALLET compiling in Windows

### ISSUE THREAD

**Issue by virtualrobotix** [BTCGPU/BTCGPU#82]
I try to follow the info on github for compiling the BTC GOLD Wallet but i have this iusse. 
 CXX      libbitcoinconsensus_la-utilstrencodings.lo
make[3]: ingresso nella directory "/home/vrminer2/BTCGPU/src/secp256k1"
gcc -I. -g -O2 -Wall -Wextra -Wno-unused-function -c src/gen_context.c -o gen_context.o
gcc gen_context.o -o gen_context
./gen_context
  CC       src/libsecp256k1_la-secp256k1.lo
  CCLD     libsecp256k1.la
libtool: link: warning: undefined symbols not allowed in x86_64-w64-mingw32 shared libraries
make[3]: uscita dalla directory "/home/vrminer2/BTCGPU/src/secp256k1"
  CXXLD    libbitcoinconsensus.la
crypto/.libs/libbitcoinconsensus_la-equihash.o:equihash.cpp:(.text+0x196): undefined reference to `crypto_generichash_blake2b_update'
crypto/.libs/libbitcoinconsensus_la-equihash.o:equihash.cpp:(.text+0x1a4): undefined reference to `crypto_generichash_blake2b_final'
/usr/bin/x86_64-w64-mingw32-ld: crypto/.libs/libbitcoinconsensus_la-equihash.o: bad reloc address 0x0 in section `.data'
collect2: error: ld returned 1 exit status
make[2]: *** [libbitcoinconsensus.la] Errore 1
make[2]: uscita dalla directory "/home/vrminer2/BTCGPU/src"
make[1]: *** [all-recursive] Errore 1
make[1]: uscita dalla directory "/home/vrminer2/BTCGPU/src"
make: *** [all-recursive] Errore 1
vrminer2@DESKTOP-C6LEM3D:~/BTCGPU$
How i can solve this iusse ? Some one already compiled the Wallets  ?

**Comment by adhood** [comment]
I don't think the wallet is ready yet. Bitcoin Gold has not launched and there is no network for a wallet to even connect to. The only option of interacting with Bitcoin Gold at the moment is by using an exchange that is participating in the trading of "future" Bitcoin Gold.

**Comment by h4x3rotab** [comment]
Yes, the wallet (or full node) is not ready yet. We will announce when it's ready in Nov.

For your specific problem. I think Windows Linux System will not work according to `doc/build-windows.md`. You have to build it from Ubuntu 16.04.

Also the build script for `libbitcoinconsensus` is not well configured. I'm going to fix it soon.

**Comment by h4x3rotab** [comment]
The `libbitcoinconsensus` issue has been fixed. Any updates?

**Comment by virtualrobotix** [comment]
Hi h4x3rotab , 
what is the exact procedure for compiling the code? 
I'm using make ... for remake code but now i have this error 
checking for Berkeley DB C++ headers... no
configure: error: libdb_cxx headers missing, Bitcoin Gold requires this library for wallet functionality (--disable-wallet to disable wallet functionality)
make: *** [config.status] Errore 1
coudl be that berkley db is not install on my Linux machine ... now i try to install and retry to make.

**Comment by virtualrobotix** [comment]
I solved the problem of DB C++ 4.8 pre requisite 
following this tutorial : 
https://github.com/bitcoin/bitcoin/issues/3686
now i have a problem with boost library try to found a solution ...

**Comment by virtualrobotix** [comment]
Great Job Guys ,
now the iusse is fixed i follow the build node for Windows and i finish the compiling procedure and obtain the exe file ... now start to sincro the blochchain ... Do you have a tutorial for the next step ? The Block Chain for Bitcoing Gold now is active ? Or not yet ? If you help us we can start to help standard user for use BTC Gold
![image](https://user-images.githubusercontent.com/7107438/32240481-c07e0614-be6d-11e7-9716-70a2a94b5b59.png)
