### ISSUE TITLE
Satoshi's Dream is Dead? Did Greed Kill Bitcoin? Let's Talk about How to Make Good Code.

### ISSUE THREAD

**Issue by bilbobits** [BTCGPU/BTCGPU#85]
Two interesting points about BTCGPU.

1.) Is that all the exchanges and infrastructure went along with the 'emperor has no clothes' program, all because they were promised free BTG, based on holding BTC, and they managed to get the entire BTC world locked down for 24 hours.

2.) Engineering wise, computer software management, BTCGPU is a class example of 'low cost of entry' for BITCOIN Clones, spending $1,000's of US Dollars on marketing and websites, but spending NADA on software development who thought this would go anywhere? 

(1) is clearly a problem, it shows "FORK MADNESS" that Satoshi's BTC is dead that the 51% hell, all you have to do is promise free BTC to the majority, and they will accept anything.

(2) there are 100's of sites that show how to clone BITCOIN, and none of them were followed in this project. This clearly shows that NOBODY was in charge, that everybody just assumed the other guy would 'write the code'.

I hope the take away here is that you need to "TEST" your code before you release "MARKET" it, that promises and lies and scams are now 90% of the BTC/ALT clone universe. What happened to the good men? Where is SATOSHI?

***

Majority of problems on this GITHUB reported are of the essence "I can't compile", thus the questions beg's to be asked, why didn't anybody on TEAM-BTCGPU bother to write a readme? It's clear that little to nothing was done, perhaps all along they didn't want people to build and test the software, perhaps they just assumed if they made it real hard, nobody would figure out for weeks that the entire project is/was smoke & mirrors?

The 'devs' are in a defensive position, they don't like the truth, but remember there are 100's of us miners and developers that spend day's trying to make this stuff work, only to figure out that it was never intended to work.

**Comment by StarbuckBG** [comment]
This is not a dev related topic. Closing the issue. You can post in Slack and discuss there.
