### ISSUE TITLE
Stuck at block 366836 while syncing: ERROR: AcceptBlockHeader: Consensus::ContextualCheckBlockHeader bad-height, incorrect block height

### ISSUE THREAD

**Issue by c0deright** [BTCGPU/BTCGPU#86]
#### If so, please list the steps to reproduce below:
1. start btcgpu daemon
2. sync begins until block 366836

### Expected behaviour
New blocks being downloaded. My understanding is, that bitcoin gold should sync from any core client until block 491406.

### Actual behaviour
```
2017-10-25 08:40:02 ERROR: invalid header received
2017-10-25 08:40:02 ProcessMessages(headers, 18064 bytes) FAILED peer=1
2017-10-25 08:40:05 ERROR: AcceptBlockHeader: Consensus::ContextualCheckBlockHeader: 000000000000000000e5438564434edaf41e63829a637521a96235adf4653e1b, bad-height, incorrect block height (code 16)
```

### What version of bitcoin-core are you using?
bitcoin-gpu-master-3180ead18bcb6471bf6dd3ae18bbaf30bb344602-xenial
selfcompiled from github .zip download

### Any extra information that might be useful in the debugging process.

Node is well connected:

```
% bitcoin-cli getpeerinfo | grep subver
    "subver": "/Satoshi:0.15.0.1/",
    "subver": "/Satoshi:0.15.0.1/",
    "subver": "/Bitcoin Gold:0.15.0.1/",
    "subver": "/Satoshi:0.15.0.1/",
    "subver": "/Satoshi:0.13.2/",
    "subver": "/Satoshi:0.14.2/",
    "subver": "/Satoshi:0.14.2/",
    "subver": "/Satoshi:0.15.0.1/",
    "subver": "/Bitcoin Gold:0.15.0.1/",
```

The connected Bitcoin Gold nodes are at block 491406 and thus don't signal "new block found" since there are no new blocks public right now. That's why my node doesn't download new blocks from the Bitcoin Gold nodes.

**Comment by StarbuckBG** [comment]
I have used reconsiderblock cli comment and then again start the daemon with reindex. Fixed it.

**Comment by StarbuckBG** [comment]
@c0deright as far as I see you have participated in the development of BCC. May you DM me in Slack. I want to ask you something about the fork methodology. I have fixed that issue by reindexing the chain that I have downloaded.

**Comment by runn1ng** [comment]
I can confirm this bug.

Steps to reply:

* start node
* node is synching correctly
* stop and start node
* node stops synching with the error

More people confirmed that this exact error happens every time after restarting node.

**Comment by h4x3rotab** [comment]
Testnet is launched recently. Anyone can reproduce this issue?
