### ISSUE TITLE
How much time should be allocated to Fraudulent ICO's - Given there was no "Ready Code" at Launch

### ISSUE THREAD

**Issue by bilbobits** [BTCGPU/BTCGPU#92]
Welll here we are at the 2nd day of 'fork'

There is no code that works, there is no main-net or test net, there is no blockchain, there is NOTHING.

Just an ICO that has come&gone,

Many people studied the source code, jumped through all the hoops of getting the code to compile, then the problem is segmentation faults ( dozens ),

Then you can't downloads any blocks without doing frequent -reindex, because the block chain never existed, nor is it compatible with the original BTC block-chain

So now we wait, but next time there is a new fork or new 'buzz' about some new BULLSHIT COIN, do we all just ignore?

It's clear that MAJORITY 90% of the current BTC world don't give a shit about truth, about Satohshi's dream, people accept 'forks' because they get free shit-coin, its no lose, so the btc-core will now be forked infinite times, so much for the 21million limit on BTC

In the past 3 days the DEV's here have added exactly 2-3 lines of C++ code, almost all the change has been textual for the comments, and caveats that NOTHING WORKS.

To the Dev's that say people don't read the code, nor test, I say the DEV's are nothing more than criminals abusing the BTC legacy blockchain.

**Comment by h4x3rotab** [comment]
> There is no code that works, there is no main-net or test net, there is no blockchain, there is NOTHING.

Check our [roadmap](https://btcgpu.org/wp-content/uploads/2017/10/BitcoinGold-Roadmap.pdf) and learn about the snapshot section.

> Just an ICO that has come&gone

There's no ICO or presale.

> Many people studied the source code, jumped through all the hoops of getting the code to compile, then the problem is segmentation faults ( dozens ),

You used a wrong version of libsodium. Why don't you compile from `depends/`?

> Then you can't downloads any blocks without doing frequent -reindex, because the block chain never existed, nor is it compatible with the original BTC block-chain

The p2p network is not launched. We will bootstrap the p2p network with BTG network magic. So you will not be able to connect to Bitcoin p2p network. Then you can check if the pre-fork blocks are same as Bitcoin.

> In the past 3 days the DEV's here have added exactly 2-3 lines of C++ code, almost all the change has been textual for the comments, and caveats that NOTHING WORKS.

Did you check the pull requests?

**Comment by mjoh090** [comment]
@bilbobits 

"It's clear that MAJORITY 90% of the current BTC world don't give a shit about truth, about Satohshi's dream, people accept 'forks' because they get free shit-coin, its no lose". 

You are right! Whatever the number is, its almost certainly the majority.

There is a whole bunch of them on the the bitcoin-gold slack channel. They absolutely hate any and every comment that raises valid concerns that potentially threatens the success of this new coin that they are hoping to foundation mine in the hope of a financial return. They just don't care about the red flags, and they will tell you that followed by a personal attack.

**Comment by StarbuckBG** [comment]
Spam/Hate - not for github.
