### ISSUE TITLE
is there a z-addr?

### ISSUE THREAD

**Issue by MCrypto** [BTCGPU/BTCGPU#95]
as far as i understand this is based on equihash where one has z & t addr. I got the code compiled on ubuntu and generated a t-addr (1Q5BX5k7jQyRxaDeEJXbjZtNYWbDcU8LWz) using the cli & "getnewaddress" but when i tried "z_getnewaddress" it gave an error?!

**Comment by andre-amorim** [comment]
another day I saw a nice presentation called "Algorand: A Better Distributed Ledger" by presented by ACM A.M. Turing Award Winner, Silvio Micali ...

**Comment by OleksandrBlack** [comment]
UP
Need to modify the node-stratum-pool?

**Comment by leto** [comment]
There are no `zaddrs` in Bitcoin Gold, or any Bitcoin fork. Those only exist in coins which use zkSNARKs, such as Zcash, Komodo, Hush and a few more

**Comment by StarbuckBG** [comment]
@leto thanks!

Closing this now.

**Comment by MCrypto** [comment]
this is an equihash algo coin ... isnt it?!

**Comment by StarbuckBG** [comment]
Equihash has nothing to do with the addresses.

**Comment by andre-amorim** [comment]
Good to see that we sold out Scooby snaks problem 🍀
