### ISSUE TITLE
Why is my name being used on http://btcgwallet.org/

### ISSUE THREAD

**Issue by fyookball** [BTCGPU/BTCGPU#96]
I have no association with this and would appreciate if you removed my name.  While you're at it, you might want to use an original web template too.

**Comment by vattay** [comment]
That's an actual scam site with no connection to BTCGPU. Wallet is probably a virus.

**Comment by fyookball** [comment]
I was told it was mentioned in the gold slack channel. might wanna look into it

**Comment by h4x3rotab** [comment]
Confirmed. It's a scam site.
